; generated by Slic3r 0.9.8-dev on 2012-12-28 at 22:17:18

; layer_height = 0.4
; perimeters = 3
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 0.4
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; scale = 1
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.53mm
; infill extrusion width = 0.53mm
; first layer extrusion width = 0.80mm

M107 ; disable fan
M190 S60 ; wait for bed temperature to be reached
M104 S185 ; set temperature
M106 S100 ; fan on
M104 S185 ; set extruder temperature
G28 ; home all axes
M109 S185 ; wait for temperature to be reached
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 F1800.000 E-1.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.400 F7800.000 ; move to next layer (0)
G1 X114.820 Y102.860 ; move to first skirt point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X114.460 Y103.270 F540.000 E1.02271 ; skirt
G1 X113.860 Y103.820 E1.05660 ; skirt
G1 X113.200 Y104.290 E1.09032 ; skirt
G1 X112.490 Y104.690 E1.12425 ; skirt
G1 X111.730 Y104.990 E1.15826 ; skirt
G1 X110.950 Y105.200 E1.19189 ; skirt
G1 X110.410 Y105.290 E1.21467 ; skirt
G1 X109.600 Y105.340 E1.24846 ; skirt
G1 X90.400 Y105.340 E2.04771 ; skirt
G1 X89.590 Y105.290 E2.08149 ; skirt
G1 X89.050 Y105.200 E2.10428 ; skirt
G1 X88.530 Y105.070 E2.12659 ; skirt
G1 X88.010 Y104.900 E2.14936 ; skirt
G1 X87.510 Y104.690 E2.17194 ; skirt
G1 X87.030 Y104.430 E2.19466 ; skirt
G1 X86.570 Y104.140 E2.21730 ; skirt
G1 X86.140 Y103.820 E2.23961 ; skirt
G1 X85.730 Y103.460 E2.26232 ; skirt
G1 X85.180 Y102.860 E2.29621 ; skirt
G1 X84.860 Y102.430 E2.31852 ; skirt
G1 X84.570 Y101.970 E2.34116 ; skirt
G1 X84.310 Y101.490 E2.36388 ; skirt
G1 X84.200 Y101.240 E2.37525 ; skirt
G1 X84.010 Y100.730 E2.39790 ; skirt
G1 X83.800 Y99.950 E2.43153 ; skirt
G1 X83.710 Y99.410 E2.45432 ; skirt
G1 X83.660 Y98.600 E2.48810 ; skirt
G1 X83.670 Y79.130 E3.29859 ; skirt
G1 X83.710 Y78.590 E3.32113 ; skirt
G1 X83.800 Y78.050 E3.34392 ; skirt
G1 X83.930 Y77.530 E3.36623 ; skirt
G1 X84.100 Y77.010 E3.38901 ; skirt
G1 X84.310 Y76.510 E3.41158 ; skirt
G1 X84.570 Y76.030 E3.43431 ; skirt
G1 X85.020 Y75.350 E3.46825 ; skirt
G1 X85.540 Y74.730 E3.50193 ; skirt
G1 X86.140 Y74.180 E3.53582 ; skirt
G1 X86.800 Y73.710 E3.56954 ; skirt
G1 X87.510 Y73.310 E3.60347 ; skirt
G1 X88.270 Y73.010 E3.63748 ; skirt
G1 X89.050 Y72.800 E3.67111 ; skirt
G1 X89.590 Y72.710 E3.69390 ; skirt
G1 X90.400 Y72.660 E3.72768 ; skirt
G1 X109.600 Y72.660 E4.52693 ; skirt
G1 X110.410 Y72.710 E4.56071 ; skirt
G1 X110.950 Y72.800 E4.58350 ; skirt
G1 X111.470 Y72.930 E4.60581 ; skirt
G1 X111.990 Y73.100 E4.62858 ; skirt
G1 X112.490 Y73.310 E4.65116 ; skirt
G1 X112.970 Y73.570 E4.67388 ; skirt
G1 X113.430 Y73.860 E4.69652 ; skirt
G1 X113.860 Y74.180 E4.71883 ; skirt
G1 X114.270 Y74.540 E4.74154 ; skirt
G1 X114.820 Y75.140 E4.77543 ; skirt
G1 X115.140 Y75.570 E4.79774 ; skirt
G1 X115.430 Y76.030 E4.82038 ; skirt
G1 X115.690 Y76.510 E4.84310 ; skirt
G1 X115.800 Y76.760 E4.85447 ; skirt
G1 X115.990 Y77.270 E4.87713 ; skirt
G1 X116.200 Y78.050 E4.91075 ; skirt
G1 X116.290 Y78.590 E4.93354 ; skirt
G1 X116.340 Y79.400 E4.96732 ; skirt
G1 X116.330 Y98.870 E5.77781 ; skirt
G1 X116.290 Y99.410 E5.80035 ; skirt
G1 X116.200 Y99.950 E5.82314 ; skirt
G1 X116.070 Y100.470 E5.84545 ; skirt
G1 X115.900 Y100.990 E5.86823 ; skirt
G1 X115.690 Y101.490 E5.89080 ; skirt
G1 X115.430 Y101.970 E5.91353 ; skirt
G1 X115.140 Y102.430 E5.93616 ; skirt
G1 X114.887 Y102.772 E5.95388 ; skirt
G1 X114.820 Y102.860 E5.95848 ; skirt
G1 F1800.000 E4.95848 ; retract
G92 E0 ; reset extrusion distance
G1 X91.871 Y80.871 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.129 Y80.871 F540.000 E1.67676 ; perimeter
G1 X108.129 Y97.129 E2.35352 ; perimeter
G1 X91.871 Y97.129 E3.03028 ; perimeter
G1 X91.871 Y80.982 E3.70245 ; perimeter
G1 X91.871 Y80.871 E3.70704 ; perimeter
G1 X91.136 Y80.136 F7800.000 ; move to first perimeter point
G1 X108.864 Y80.136 F540.000 E4.44505 ; perimeter
G1 X108.864 Y97.864 E5.18305 ; perimeter
G1 X91.136 Y97.864 E5.92106 ; perimeter
G1 X91.136 Y80.246 E6.65447 ; perimeter
G1 X91.136 Y80.136 E6.65906 ; perimeter
G1 X90.400 Y79.400 F7800.000 ; move to first perimeter point
G1 X109.600 Y79.400 F540.000 E7.45831 ; perimeter
G1 X109.600 Y98.600 E8.25756 ; perimeter
G1 X90.400 Y98.600 E9.05681 ; perimeter
G1 X90.400 Y79.510 E9.85146 ; perimeter
G1 X90.400 Y79.400 E9.85606 ; perimeter
G1 X91.037 Y79.768 F7800.000 ; move inwards before travel
G1 F1800.000 E8.85606 ; retract
G92 E0 ; reset extrusion distance
G1 X92.841 Y96.627 F7800.000 ; move to first fill point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X92.373 Y96.159 F1080.000 E1.02799 ; fill
G1 X92.373 Y95.103 E1.07262 ; fill
G1 X93.897 Y96.627 E1.16374 ; fill
G1 X94.953 Y96.627 E1.20838 ; fill
G1 X92.373 Y94.047 E1.36262 ; fill
G1 X92.373 Y92.990 E1.40725 ; fill
G1 X96.010 Y96.627 E1.62461 ; fill
G1 X97.066 Y96.627 E1.66925 ; fill
G1 X92.373 Y91.934 E1.94973 ; fill
G1 X92.373 Y90.878 E1.99437 ; fill
G1 X98.122 Y96.627 E2.33798 ; fill
G1 X99.178 Y96.627 E2.38261 ; fill
G1 X92.373 Y89.822 E2.78935 ; fill
G1 X92.373 Y88.766 E2.83399 ; fill
G1 X100.234 Y96.627 E3.30384 ; fill
G1 X101.290 Y96.627 E3.34848 ; fill
G1 X92.373 Y87.710 E3.88146 ; fill
G1 X92.373 Y86.654 E3.92609 ; fill
G1 X102.346 Y96.627 E4.52219 ; fill
G1 X103.403 Y96.627 E4.56683 ; fill
G1 X92.373 Y85.597 E5.22606 ; fill
G1 X92.373 Y84.541 E5.27069 ; fill
G1 X104.459 Y96.627 E5.99304 ; fill
G1 X105.515 Y96.627 E6.03768 ; fill
G1 X92.373 Y83.485 E6.82315 ; fill
G1 X92.373 Y82.429 E6.86779 ; fill
G1 X106.571 Y96.627 E7.71638 ; fill
G1 X107.627 Y96.627 E7.76101 ; fill
G1 X92.373 Y81.373 E8.67272 ; fill
G1 X93.429 Y81.373 E8.71735 ; fill
G1 X107.627 Y95.571 E9.56595 ; fill
G1 X107.627 Y94.515 E9.61058 ; fill
G1 X94.485 Y81.373 E10.39606 ; fill
G1 X95.541 Y81.373 E10.44069 ; fill
G1 X107.627 Y93.459 E11.16304 ; fill
G1 X107.627 Y92.403 E11.20768 ; fill
G1 X96.597 Y81.373 E11.86690 ; fill
G1 X97.654 Y81.373 E11.91154 ; fill
G1 X107.627 Y91.346 E12.50764 ; fill
G1 X107.627 Y90.290 E12.55227 ; fill
G1 X98.710 Y81.373 E13.08525 ; fill
G1 X99.766 Y81.373 E13.12989 ; fill
G1 X107.627 Y89.234 E13.59974 ; fill
G1 X107.627 Y88.178 E13.64438 ; fill
G1 X100.822 Y81.373 E14.05111 ; fill
G1 X101.878 Y81.373 E14.09575 ; fill
G1 X107.627 Y87.122 E14.43935 ; fill
G1 X107.627 Y86.066 E14.48399 ; fill
G1 X102.934 Y81.373 E14.76447 ; fill
G1 X103.990 Y81.373 E14.80910 ; fill
G1 X107.627 Y85.010 E15.02647 ; fill
G1 X107.627 Y83.953 E15.07110 ; fill
G1 X105.047 Y81.373 E15.22534 ; fill
G1 X106.103 Y81.373 E15.26998 ; fill
G1 X107.627 Y82.897 E15.36109 ; fill
G1 X107.627 Y81.841 E15.40572 ; fill
G1 X107.159 Y81.373 E15.43371 ; fill
G1 F1800.000 E14.43371 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.800 F7800.000 ; move to next layer (1)
G1 X108.698 Y97.698 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X91.302 Y97.698 F1800.000 E1.51155 ; perimeter
G1 X91.302 Y80.302 E2.02310 ; perimeter
G1 X108.698 Y80.302 E2.53465 ; perimeter
G1 X108.698 Y97.620 E3.04390 ; perimeter
G1 X108.698 Y97.698 E3.04619 ; perimeter
G1 X109.218 Y98.218 F7800.000 ; move to first perimeter point
G1 X90.782 Y98.218 F1800.000 E3.58830 ; perimeter
G1 X90.782 Y79.782 E4.13041 ; perimeter
G1 X109.218 Y79.782 E4.67252 ; perimeter
G1 X109.218 Y98.140 E5.21234 ; perimeter
G1 X109.218 Y98.218 E5.21463 ; perimeter
G1 X109.737 Y98.737 F7800.000 ; move to first perimeter point
G1 X90.263 Y98.737 F1800.000 E5.78730 ; perimeter
G1 X90.263 Y79.263 E6.35997 ; perimeter
G1 X109.737 Y79.263 E6.93263 ; perimeter
G1 X109.737 Y98.660 E7.50301 ; perimeter
G1 X109.737 Y98.737 E7.50530 ; perimeter
G1 X109.287 Y98.478 F7800.000 ; move inwards before travel
G1 X108.344 Y97.013 ; move to first fill point
G1 X108.013 Y97.344 F3000.000 E7.51922 ; fill
G1 X107.270 Y97.344 E7.54134 ; fill
G1 X108.344 Y96.270 E7.58655 ; fill
G1 X108.344 Y95.526 E7.60867 ; fill
G1 X106.526 Y97.344 E7.68515 ; fill
G1 X105.783 Y97.344 E7.70728 ; fill
G1 X108.344 Y94.783 E7.81505 ; fill
G1 X108.344 Y94.039 E7.83717 ; fill
G1 X105.039 Y97.344 E7.97622 ; fill
G1 X104.296 Y97.344 E7.99834 ; fill
G1 X108.344 Y93.296 E8.16868 ; fill
G1 X108.344 Y92.552 E8.19080 ; fill
G1 X103.552 Y97.344 E8.39241 ; fill
G1 X102.809 Y97.344 E8.41453 ; fill
G1 X108.344 Y91.809 E8.64743 ; fill
G1 X108.344 Y91.065 E8.66955 ; fill
G1 X102.065 Y97.344 E8.93374 ; fill
G1 X101.322 Y97.344 E8.95586 ; fill
G1 X108.344 Y90.322 E9.25132 ; fill
G1 X108.344 Y89.578 E9.27344 ; fill
G1 X100.578 Y97.344 E9.60019 ; fill
G1 X99.835 Y97.344 E9.62231 ; fill
G1 X108.344 Y88.835 E9.98034 ; fill
G1 X108.344 Y88.091 E10.00246 ; fill
G1 X99.091 Y97.344 E10.39177 ; fill
G1 X98.348 Y97.344 E10.41389 ; fill
G1 X108.344 Y87.348 E10.83449 ; fill
G1 X108.344 Y86.604 E10.85661 ; fill
G1 X97.604 Y97.344 E11.30849 ; fill
G1 X96.860 Y97.344 E11.33061 ; fill
G1 X108.344 Y85.860 E11.81377 ; fill
G1 X108.344 Y85.117 E11.83589 ; fill
G1 X96.117 Y97.344 E12.35033 ; fill
G1 X95.373 Y97.344 E12.37245 ; fill
G1 X108.344 Y84.374 E12.91818 ; fill
G1 X108.344 Y83.630 E12.94030 ; fill
G1 X94.630 Y97.344 E13.51731 ; fill
G1 X93.886 Y97.344 E13.53943 ; fill
G1 X108.344 Y82.886 E14.14772 ; fill
G1 X108.344 Y82.143 E14.16984 ; fill
G1 X93.143 Y97.344 E14.80941 ; fill
G1 X92.399 Y97.344 E14.83153 ; fill
G1 X108.344 Y81.399 E15.50239 ; fill
G1 X108.344 Y80.656 E15.52450 ; fill
G1 X91.656 Y97.344 E16.22663 ; fill
G1 X91.656 Y96.600 E16.24875 ; fill
G1 X107.600 Y80.656 E16.91961 ; fill
G1 X106.857 Y80.656 E16.94173 ; fill
G1 X91.656 Y95.857 E17.58130 ; fill
G1 X91.656 Y95.114 E17.60342 ; fill
G1 X106.114 Y80.656 E18.21170 ; fill
G1 X105.370 Y80.656 E18.23383 ; fill
G1 X91.656 Y94.370 E18.81083 ; fill
G1 X91.656 Y93.626 E18.83295 ; fill
G1 X104.626 Y80.656 E19.37868 ; fill
G1 X103.883 Y80.656 E19.40080 ; fill
G1 X91.656 Y92.883 E19.91524 ; fill
G1 X91.656 Y92.139 E19.93736 ; fill
G1 X103.139 Y80.656 E20.42052 ; fill
G1 X102.396 Y80.656 E20.44263 ; fill
G1 X91.656 Y91.396 E20.89451 ; fill
G1 X91.656 Y90.652 E20.91663 ; fill
G1 X101.652 Y80.656 E21.33722 ; fill
G1 X100.909 Y80.656 E21.35934 ; fill
G1 X91.656 Y89.909 E21.74865 ; fill
G1 X91.656 Y89.165 E21.77077 ; fill
G1 X100.165 Y80.656 E22.12880 ; fill
G1 X99.422 Y80.656 E22.15092 ; fill
G1 X91.656 Y88.422 E22.47767 ; fill
G1 X91.656 Y87.678 E22.49979 ; fill
G1 X98.678 Y80.656 E22.79525 ; fill
G1 X97.935 Y80.656 E22.81737 ; fill
G1 X91.656 Y86.935 E23.08155 ; fill
G1 X91.656 Y86.191 E23.10367 ; fill
G1 X97.191 Y80.656 E23.33657 ; fill
G1 X96.448 Y80.656 E23.35869 ; fill
G1 X91.656 Y85.448 E23.56031 ; fill
G1 X91.656 Y84.704 E23.58243 ; fill
G1 X95.704 Y80.656 E23.75276 ; fill
G1 X94.961 Y80.656 E23.77488 ; fill
G1 X91.656 Y83.961 E23.91393 ; fill
G1 X91.656 Y83.217 E23.93605 ; fill
G1 X94.217 Y80.656 E24.04382 ; fill
G1 X93.474 Y80.656 E24.06594 ; fill
G1 X91.656 Y82.474 E24.14242 ; fill
G1 X91.656 Y81.730 E24.16454 ; fill
G1 X92.730 Y80.656 E24.20974 ; fill
G1 X91.987 Y80.656 E24.23186 ; fill
G1 X91.656 Y80.987 E24.24578 ; fill
M106 S255 ; enable fan
G1 F1800.000 E23.24578 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.200 F7800.000 ; move to next layer (2)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.600 F7800.000 ; move to next layer (3)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.000 F7800.000 ; move to next layer (4)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.400 F7800.000 ; move to next layer (5)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.800 F7800.000 ; move to next layer (6)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.200 F7800.000 ; move to next layer (7)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.600 F7800.000 ; move to next layer (8)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.000 F7800.000 ; move to next layer (9)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.400 F7800.000 ; move to next layer (10)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.800 F7800.000 ; move to next layer (11)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.200 F7800.000 ; move to next layer (12)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.600 F7800.000 ; move to next layer (13)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.000 F7800.000 ; move to next layer (14)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.400 F7800.000 ; move to next layer (15)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.800 F7800.000 ; move to next layer (16)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z7.200 F7800.000 ; move to next layer (17)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z7.600 F7800.000 ; move to next layer (18)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z8.000 F7800.000 ; move to next layer (19)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z8.400 F7800.000 ; move to next layer (20)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z8.800 F7800.000 ; move to next layer (21)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z9.200 F7800.000 ; move to next layer (22)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z9.600 F7800.000 ; move to next layer (23)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z10.000 F7800.000 ; move to next layer (24)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z10.400 F7800.000 ; move to next layer (25)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z10.800 F7800.000 ; move to next layer (26)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z11.200 F7800.000 ; move to next layer (27)
G1 X108.052 Y98.504 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.351 Y98.447 F600.000 E1.03823 ; perimeter
G1 X109.504 Y98.091 E1.04963 ; perimeter
G1 X109.504 Y79.909 E1.58427 ; perimeter
G1 X109.416 Y79.584 E1.59417 ; perimeter
G1 X109.091 Y79.496 E1.60407 ; perimeter
G1 X90.909 Y79.496 E2.13871 ; perimeter
G1 X90.584 Y79.584 E2.14861 ; perimeter
G1 X90.390 Y79.390 E2.15671 ; perimeter
G1 F1800.000 E1.15671 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y83.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.496 Y79.909 F600.000 E1.10693 ; perimeter
G1 X90.584 Y79.584 E1.11683 ; perimeter
G1 F1800.000 E0.11683 ; retract
G92 E0 ; reset extrusion distance
G1 X90.499 Y91.857 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.497 Y83.545 F600.000 E1.24441 ; perimeter
G1 F1800.000 E0.24441 ; retract
G92 E0 ; reset extrusion distance
G1 X90.498 Y93.935 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.499 Y91.857 F600.000 E1.06110 ; perimeter
G1 F1800.000 E0.06110 ; retract
G92 E0 ; reset extrusion distance
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.498 Y93.935 F600.000 E1.03055 ; perimeter
G1 X90.497 Y94.974 F7800.000 ; move to first perimeter point
G1 X90.497 Y95.494 F600.000 E1.04583 ; perimeter
G1 X90.553 Y98.351 E1.12986 ; perimeter
G1 X90.909 Y98.504 E1.14126 ; perimeter
G1 X91.652 Y98.496 E1.16311 ; perimeter
G1 X100.519 Y98.500 E1.42386 ; perimeter
G1 X108.052 Y98.504 E1.64535 ; perimeter
G1 X109.416 Y98.416 F7800.000 ; move to first perimeter point
G1 X109.610 Y98.610 F600.000 E1.65345 ; perimeter
G1 F1800.000 E0.65345 ; retract
G92 E0 ; reset extrusion distance
G1 X90.390 Y98.610 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.584 Y98.416 F600.000 E1.00810 ; perimeter
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 X109.416 Y79.584 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.610 Y79.390 F600.000 E1.00810 ; perimeter
G1 X109.610 Y79.390 ; perimeter
M106 S238 ; enable fan
G1 F1800.000 E0.00810 ; retract
G92 E0 ; reset extrusion distance
G1 Z11.600 F7800.000 ; move to next layer (28)
G1 X91.302 Y97.698 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X91.302 Y80.302 F1800.000 E1.51155 ; perimeter
G1 X108.698 Y80.302 E2.02310 ; perimeter
G1 X108.698 Y97.698 E2.53465 ; perimeter
G1 X91.380 Y97.698 E3.04390 ; perimeter
G1 X91.302 Y97.698 E3.04619 ; perimeter
G1 X90.782 Y98.218 F7800.000 ; move to first perimeter point
G1 X90.782 Y79.782 F1800.000 E3.58830 ; perimeter
G1 X109.218 Y79.782 E4.13041 ; perimeter
G1 X109.218 Y98.218 E4.67252 ; perimeter
G1 X90.860 Y98.218 E5.21234 ; perimeter
G1 X90.782 Y98.218 E5.21463 ; perimeter
G1 X90.263 Y98.737 F7800.000 ; move to first perimeter point
G1 X90.263 Y79.263 F1800.000 E5.78730 ; perimeter
G1 X109.737 Y79.263 E6.35997 ; perimeter
G1 X109.737 Y98.737 E6.93263 ; perimeter
G1 X90.340 Y98.737 E7.50301 ; perimeter
G1 X90.263 Y98.737 E7.50530 ; perimeter
G1 X90.522 Y98.287 F7800.000 ; move inwards before travel
G1 X91.946 Y97.304 ; move to first fill point
M106 S255 ; enable fan
G1 X91.696 Y97.054 F3600.000 E7.51513 ; fill
G1 X91.696 Y96.498 E7.53055 ; fill
G1 X92.502 Y97.304 E7.56219 ; fill
G1 X93.057 Y97.304 E7.57762 ; fill
G1 X91.696 Y95.943 E7.63108 ; fill
G1 X91.696 Y95.387 E7.64650 ; fill
G1 X93.613 Y97.304 E7.72178 ; fill
G1 X94.168 Y97.304 E7.73720 ; fill
G1 X91.696 Y94.832 E7.83429 ; fill
G1 X91.696 Y94.277 E7.84972 ; fill
G1 X94.723 Y97.304 E7.96862 ; fill
G1 X95.279 Y97.304 E7.98405 ; fill
G1 X91.696 Y93.721 E8.12477 ; fill
G1 X91.696 Y93.166 E8.14020 ; fill
G1 X95.834 Y97.304 E8.30274 ; fill
G1 X96.389 Y97.304 E8.31817 ; fill
G1 X91.696 Y92.611 E8.50252 ; fill
G1 X91.696 Y92.055 E8.51795 ; fill
G1 X96.945 Y97.304 E8.72412 ; fill
G1 X97.500 Y97.304 E8.73955 ; fill
G1 X91.696 Y91.500 E8.96754 ; fill
G1 X91.696 Y90.945 E8.98297 ; fill
G1 X98.055 Y97.304 E9.23277 ; fill
G1 X98.611 Y97.304 E9.24820 ; fill
G1 X91.696 Y90.389 E9.51982 ; fill
G1 X91.696 Y89.834 E9.53525 ; fill
G1 X99.166 Y97.304 E9.82869 ; fill
G1 X99.721 Y97.304 E9.84412 ; fill
G1 X91.696 Y89.279 E10.15937 ; fill
G1 X91.696 Y88.723 E10.17480 ; fill
G1 X100.277 Y97.304 E10.51187 ; fill
G1 X100.832 Y97.304 E10.52730 ; fill
G1 X91.696 Y88.168 E10.88619 ; fill
G1 X91.696 Y87.612 E10.90162 ; fill
G1 X101.388 Y97.304 E11.28232 ; fill
G1 X101.943 Y97.304 E11.29775 ; fill
G1 X91.696 Y87.057 E11.70027 ; fill
G1 X91.696 Y86.502 E11.71570 ; fill
G1 X102.498 Y97.304 E12.14004 ; fill
G1 X103.054 Y97.304 E12.15546 ; fill
G1 X91.696 Y85.946 E12.60162 ; fill
G1 X91.696 Y85.391 E12.61705 ; fill
G1 X103.609 Y97.304 E13.08502 ; fill
G1 X104.164 Y97.304 E13.10045 ; fill
G1 X91.696 Y84.836 E13.59024 ; fill
G1 X91.696 Y84.280 E13.60566 ; fill
G1 X104.720 Y97.304 E14.11727 ; fill
G1 X105.275 Y97.304 E14.13270 ; fill
G1 X91.696 Y83.725 E14.66612 ; fill
G1 X91.696 Y83.170 E14.68155 ; fill
G1 X105.830 Y97.304 E15.23679 ; fill
G1 X106.386 Y97.304 E15.25221 ; fill
G1 X91.696 Y82.614 E15.82927 ; fill
G1 X91.696 Y82.059 E15.84470 ; fill
G1 X106.941 Y97.304 E16.44357 ; fill
G1 X107.497 Y97.304 E16.45900 ; fill
G1 X91.696 Y81.503 E17.07969 ; fill
G1 X91.696 Y80.948 E17.09511 ; fill
G1 X108.052 Y97.304 E17.73762 ; fill
G1 X108.304 Y97.000 E17.74858 ; fill
G1 X92.000 Y80.696 E18.38905 ; fill
G1 X92.555 Y80.696 E18.40448 ; fill
G1 X108.304 Y96.445 E19.02313 ; fill
G1 X108.304 Y95.889 E19.03856 ; fill
G1 X93.111 Y80.696 E19.63540 ; fill
G1 X93.666 Y80.696 E19.65082 ; fill
G1 X108.304 Y95.334 E20.22585 ; fill
G1 X108.304 Y94.779 E20.24127 ; fill
G1 X94.221 Y80.696 E20.79448 ; fill
G1 X94.777 Y80.696 E20.80991 ; fill
G1 X108.304 Y94.223 E21.34129 ; fill
G1 X108.304 Y93.668 E21.35672 ; fill
G1 X95.332 Y80.696 E21.86629 ; fill
G1 X95.887 Y80.696 E21.88172 ; fill
G1 X108.304 Y93.113 E22.36948 ; fill
G1 X108.304 Y92.557 E22.38490 ; fill
G1 X96.443 Y80.696 E22.85084 ; fill
G1 X96.998 Y80.696 E22.86627 ; fill
G1 X108.304 Y92.002 E23.31039 ; fill
G1 X108.304 Y91.446 E23.32582 ; fill
G1 X97.554 Y80.696 E23.74813 ; fill
G1 X98.109 Y80.696 E23.76355 ; fill
G1 X108.304 Y90.891 E24.16404 ; fill
G1 X108.304 Y90.336 E24.17947 ; fill
G1 X98.664 Y80.696 E24.55814 ; fill
G1 X99.220 Y80.696 E24.57357 ; fill
G1 X108.304 Y89.780 E24.93043 ; fill
G1 X108.304 Y89.225 E24.94585 ; fill
G1 X99.775 Y80.696 E25.28089 ; fill
G1 X100.330 Y80.696 E25.29632 ; fill
G1 X108.304 Y88.670 E25.60954 ; fill
G1 X108.304 Y88.114 E25.62497 ; fill
G1 X100.886 Y80.696 E25.91638 ; fill
G1 X101.441 Y80.696 E25.93180 ; fill
G1 X108.304 Y87.559 E26.20139 ; fill
G1 X108.304 Y87.004 E26.21682 ; fill
G1 X101.996 Y80.696 E26.46459 ; fill
G1 X102.552 Y80.696 E26.48002 ; fill
G1 X108.304 Y86.448 E26.70597 ; fill
G1 X108.304 Y85.893 E26.72140 ; fill
G1 X103.107 Y80.696 E26.92554 ; fill
G1 X103.663 Y80.696 E26.94097 ; fill
G1 X108.304 Y85.337 E27.12329 ; fill
G1 X108.304 Y84.782 E27.13872 ; fill
G1 X104.218 Y80.696 E27.29922 ; fill
G1 X104.773 Y80.696 E27.31465 ; fill
G1 X108.304 Y84.227 E27.45334 ; fill
G1 X108.304 Y83.671 E27.46877 ; fill
G1 X105.329 Y80.696 E27.58564 ; fill
G1 X105.884 Y80.696 E27.60106 ; fill
G1 X108.304 Y83.116 E27.69612 ; fill
G1 X108.304 Y82.561 E27.71155 ; fill
G1 X106.439 Y80.696 E27.78479 ; fill
G1 X106.995 Y80.696 E27.80021 ; fill
G1 X108.304 Y82.005 E27.85164 ; fill
G1 X108.304 Y81.450 E27.86706 ; fill
G1 X107.550 Y80.696 E27.89667 ; fill
M106 S241 ; enable fan
G1 F1800.000 E26.89667 ; retract
M106 S241 ; enable fan
G92 E0 ; reset extrusion distance
G1 Z12.000 F7800.000 ; move to next layer (29)
G1 X91.302 Y80.302 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.698 Y80.302 F1800.000 E1.51155 ; perimeter
G1 X108.698 Y97.698 E2.02310 ; perimeter
G1 X91.302 Y97.698 E2.53465 ; perimeter
G1 X91.302 Y80.380 E3.04390 ; perimeter
G1 X91.302 Y80.302 E3.04619 ; perimeter
G1 X90.782 Y79.782 F7800.000 ; move to first perimeter point
G1 X109.218 Y79.782 F1800.000 E3.58830 ; perimeter
G1 X109.218 Y98.218 E4.13041 ; perimeter
G1 X90.782 Y98.218 E4.67252 ; perimeter
G1 X90.782 Y79.860 E5.21234 ; perimeter
G1 X90.782 Y79.782 E5.21463 ; perimeter
G1 X90.263 Y79.263 F7800.000 ; move to first perimeter point
G1 X109.737 Y79.263 F1800.000 E5.78730 ; perimeter
G1 X109.737 Y98.737 E6.35997 ; perimeter
G1 X90.263 Y98.737 E6.93263 ; perimeter
G1 X90.263 Y79.340 E7.50301 ; perimeter
G1 X90.263 Y79.263 E7.50530 ; perimeter
G1 X90.713 Y79.522 F7800.000 ; move inwards before travel
G1 F1800.000 E6.50530 ; retract
G92 E0 ; reset extrusion distance
G1 X108.344 Y97.013 F7800.000 ; move to first fill point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.013 Y97.344 F3000.000 E1.01392 ; fill
G1 X107.270 Y97.344 E1.03604 ; fill
G1 X108.344 Y96.270 E1.08125 ; fill
G1 X108.344 Y95.526 E1.10337 ; fill
G1 X106.526 Y97.344 E1.17985 ; fill
G1 X105.783 Y97.344 E1.20197 ; fill
G1 X108.344 Y94.783 E1.30974 ; fill
G1 X108.344 Y94.039 E1.33186 ; fill
G1 X105.039 Y97.344 E1.47092 ; fill
G1 X104.296 Y97.344 E1.49304 ; fill
G1 X108.344 Y93.296 E1.66337 ; fill
G1 X108.344 Y92.552 E1.68549 ; fill
G1 X103.552 Y97.344 E1.88711 ; fill
G1 X102.809 Y97.344 E1.90923 ; fill
G1 X108.344 Y91.809 E2.14213 ; fill
G1 X108.344 Y91.065 E2.16425 ; fill
G1 X102.065 Y97.344 E2.42843 ; fill
G1 X101.322 Y97.344 E2.45055 ; fill
G1 X108.344 Y90.322 E2.74602 ; fill
G1 X108.344 Y89.578 E2.76814 ; fill
G1 X100.578 Y97.344 E3.09489 ; fill
G1 X99.835 Y97.344 E3.11701 ; fill
G1 X108.344 Y88.835 E3.47504 ; fill
G1 X108.344 Y88.091 E3.49716 ; fill
G1 X99.091 Y97.344 E3.88647 ; fill
G1 X98.348 Y97.344 E3.90859 ; fill
G1 X108.344 Y87.348 E4.32918 ; fill
G1 X108.344 Y86.604 E4.35131 ; fill
G1 X97.604 Y97.344 E4.80318 ; fill
G1 X96.860 Y97.344 E4.82530 ; fill
G1 X108.344 Y85.860 E5.30846 ; fill
G1 X108.344 Y85.117 E5.33059 ; fill
G1 X96.117 Y97.344 E5.84503 ; fill
G1 X95.373 Y97.344 E5.86715 ; fill
G1 X108.344 Y84.374 E6.41287 ; fill
G1 X108.344 Y83.630 E6.43499 ; fill
G1 X94.630 Y97.344 E7.01200 ; fill
G1 X93.886 Y97.344 E7.03412 ; fill
G1 X108.344 Y82.886 E7.64241 ; fill
G1 X108.344 Y82.143 E7.66453 ; fill
G1 X93.143 Y97.344 E8.30411 ; fill
G1 X92.399 Y97.344 E8.32623 ; fill
G1 X108.344 Y81.399 E8.99708 ; fill
G1 X108.344 Y80.656 E9.01920 ; fill
G1 X91.656 Y97.344 E9.72133 ; fill
G1 X91.656 Y96.600 E9.74345 ; fill
G1 X107.600 Y80.656 E10.41430 ; fill
G1 X106.857 Y80.656 E10.43642 ; fill
G1 X91.656 Y95.857 E11.07599 ; fill
G1 X91.656 Y95.114 E11.09811 ; fill
G1 X106.114 Y80.656 E11.70640 ; fill
G1 X105.370 Y80.656 E11.72852 ; fill
G1 X91.656 Y94.370 E12.30553 ; fill
G1 X91.656 Y93.626 E12.32765 ; fill
G1 X104.626 Y80.656 E12.87337 ; fill
G1 X103.883 Y80.656 E12.89549 ; fill
G1 X91.656 Y92.883 E13.40994 ; fill
G1 X91.656 Y92.139 E13.43206 ; fill
G1 X103.139 Y80.656 E13.91521 ; fill
G1 X102.396 Y80.656 E13.93733 ; fill
G1 X91.656 Y91.396 E14.38921 ; fill
G1 X91.656 Y90.652 E14.41133 ; fill
G1 X101.652 Y80.656 E14.83192 ; fill
G1 X100.909 Y80.656 E14.85404 ; fill
G1 X91.656 Y89.909 E15.24335 ; fill
G1 X91.656 Y89.165 E15.26547 ; fill
G1 X100.165 Y80.656 E15.62350 ; fill
G1 X99.422 Y80.656 E15.64562 ; fill
G1 X91.656 Y88.422 E15.97237 ; fill
G1 X91.656 Y87.678 E15.99449 ; fill
G1 X98.678 Y80.656 E16.28995 ; fill
G1 X97.935 Y80.656 E16.31207 ; fill
G1 X91.656 Y86.935 E16.57625 ; fill
G1 X91.656 Y86.191 E16.59837 ; fill
G1 X97.191 Y80.656 E16.83126 ; fill
G1 X96.448 Y80.656 E16.85339 ; fill
G1 X91.656 Y85.448 E17.05500 ; fill
G1 X91.656 Y84.704 E17.07712 ; fill
G1 X95.704 Y80.656 E17.24745 ; fill
G1 X94.961 Y80.656 E17.26958 ; fill
G1 X91.656 Y83.961 E17.40863 ; fill
G1 X91.656 Y83.217 E17.43075 ; fill
G1 X94.217 Y80.656 E17.53851 ; fill
G1 X93.474 Y80.656 E17.56063 ; fill
G1 X91.656 Y82.474 E17.63712 ; fill
G1 X91.656 Y81.730 E17.65924 ; fill
G1 X92.730 Y80.656 E17.70444 ; fill
G1 X91.987 Y80.656 E17.72656 ; fill
G1 X91.656 Y80.987 E17.74048 ; fill
G1 F1800.000 E16.74048 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used = 160.1mm (1.1cm3)

; acceleration = 0
; bed_size = 200,200
; bed_temperature = 60
; bottom_solid_layers = 3
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_width = 0
; complete_objects = 0
; cooling = 1
; disable_fan_first_layers = 2
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors
; external_perimeter_speed = 100%
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_diameter = 3
; fill_angle = 45
; fill_density = 0.4
; fill_pattern = rectilinear
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 200%
; first_layer_height = 100%
; first_layer_speed = 30%
; first_layer_temperature = 185
; g0 = 0
; gap_fill_speed = 20
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_speed = 60
; layer_gcode = 
; layer_height = 0.4
; max_fan_speed = 100
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.5
; only_retract_when_crossing_perimeters = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 25
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 30
; perimeters = 3
; post_process = 
; print_center = 100,89
; randomize_start = 1
; retract_before_travel = 2
; retract_length = 1
; retract_length_toolchange = 3
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 30
; rotate = 0
; scale = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_speed = 60
; start_gcode = M106 S100 ; fan on\nM104 S185 ; set extruder temperature\nG28 ; home all axes
; support_material = 0
; support_material_angle = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 45
; temperature = 185
; threads = 2
; top_solid_infill_speed = 50
; top_solid_layers = 3
; travel_speed = 130
; use_relative_e_distances = 0
; vibration_limit = 0
; z_offset = 0
