; generated by Slic3r 0.9.8-dev on 2012-12-29 at 20:44:32

; layer_height = 0.4
; perimeters = 3
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 0.4
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; scale = 1
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.53mm
; infill extrusion width = 0.53mm
; first layer extrusion width = 0.80mm

M107 ; disable fan
M190 S60 ; wait for bed temperature to be reached
M104 S185 ; set temperature
M104 S185 ; set extruder temperature
G28 ; home all axes
M109 S185 ; wait for temperature to be reached
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 F1800.000 E-1.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.400 F7800.000 ; move to next layer (0)
G1 X118.590 Y106.100 ; move to first skirt point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X118.390 Y106.350 F540.000 E1.01333 ; skirt
G1 X117.960 Y106.820 E1.03985 ; skirt
G1 X117.370 Y107.370 E1.07342 ; skirt
G1 X116.860 Y107.760 E1.10015 ; skirt
G1 X116.030 Y108.240 E1.14006 ; skirt
G1 X102.700 Y114.720 E1.75705 ; skirt
G1 X101.920 Y115.010 E1.79169 ; skirt
G1 X101.380 Y115.140 E1.81481 ; skirt
G1 X100.560 Y115.260 E1.84931 ; skirt
G1 X100.000 Y115.290 E1.87265 ; skirt
G1 X99.450 Y115.260 E1.89558 ; skirt
G1 X98.900 Y115.200 E1.91861 ; skirt
G1 X98.360 Y115.080 E1.94164 ; skirt
G1 X98.090 Y115.010 E1.95325 ; skirt
G1 X97.560 Y114.830 E1.97655 ; skirt
G1 X97.060 Y114.610 E1.99929 ; skirt
G1 X83.990 Y108.260 E2.60418 ; skirt
G1 X83.700 Y108.110 E2.61777 ; skirt
G1 X83.150 Y107.780 E2.64447 ; skirt
G1 X82.890 Y107.590 E2.65787 ; skirt
G1 X82.400 Y107.180 E2.68447 ; skirt
G1 X81.830 Y106.610 E2.71802 ; skirt
G1 X81.420 Y106.120 E2.74462 ; skirt
G1 X81.060 Y105.590 E2.77129 ; skirt
G1 X80.750 Y105.030 E2.79794 ; skirt
G1 X74.380 Y91.940 E3.40394 ; skirt
G1 X74.160 Y91.430 E3.42706 ; skirt
G1 X73.910 Y90.640 E3.46155 ; skirt
G1 X73.760 Y89.820 E3.49625 ; skirt
G1 X73.700 Y88.990 E3.53089 ; skirt
G1 X73.760 Y88.160 E3.56553 ; skirt
G1 X73.910 Y87.340 E3.60023 ; skirt
G1 X73.980 Y87.070 E3.61184 ; skirt
G1 X74.160 Y86.550 E3.63475 ; skirt
G1 X74.380 Y86.040 E3.65787 ; skirt
G1 X80.750 Y72.960 E4.26350 ; skirt
G1 X81.230 Y72.130 E4.30341 ; skirt
G1 X81.420 Y71.870 E4.31681 ; skirt
G1 X81.830 Y71.380 E4.34341 ; skirt
G1 X82.150 Y71.050 E4.36255 ; skirt
G1 X82.620 Y70.620 E4.38906 ; skirt
G1 X83.130 Y70.230 E4.41579 ; skirt
G1 X83.960 Y69.750 E4.45570 ; skirt
G1 X97.040 Y63.380 E5.06133 ; skirt
G1 X97.550 Y63.160 E5.08445 ; skirt
G1 X98.070 Y62.980 E5.10735 ; skirt
G1 X98.340 Y62.910 E5.11897 ; skirt
G1 X98.880 Y62.800 E5.14191 ; skirt
G1 X99.710 Y62.710 E5.17666 ; skirt
G1 X99.990 Y62.700 E5.18832 ; skirt
G1 X100.540 Y62.730 E5.21125 ; skirt
G1 X101.370 Y62.850 E5.24616 ; skirt
G1 X101.900 Y62.980 E5.26888 ; skirt
G1 X102.170 Y63.070 E5.28073 ; skirt
G1 X102.430 Y63.160 E5.29218 ; skirt
G1 X102.940 Y63.380 E5.31530 ; skirt
G1 X116.030 Y69.750 E5.92130 ; skirt
G1 X116.860 Y70.230 E5.96121 ; skirt
G1 X117.120 Y70.420 E5.97462 ; skirt
G1 X117.610 Y70.830 E6.00121 ; skirt
G1 X118.160 Y71.380 E6.03359 ; skirt
G1 X118.570 Y71.870 E6.06019 ; skirt
G1 X118.930 Y72.400 E6.08686 ; skirt
G1 X119.240 Y72.960 E6.11350 ; skirt
G1 X125.610 Y86.050 E6.71950 ; skirt
G1 X125.830 Y86.560 E6.74262 ; skirt
G1 X126.080 Y87.350 E6.77712 ; skirt
G1 X126.230 Y88.170 E6.81182 ; skirt
G1 X126.290 Y89.000 E6.84646 ; skirt
G1 X126.230 Y89.830 E6.88110 ; skirt
G1 X126.080 Y90.650 E6.91580 ; skirt
G1 X125.830 Y91.440 E6.95029 ; skirt
G1 X125.610 Y91.950 E6.97341 ; skirt
G1 X119.260 Y105.010 E7.57793 ; skirt
G1 X118.950 Y105.570 E7.60457 ; skirt
G1 X118.655 Y106.011 E7.62665 ; skirt
G1 X118.590 Y106.100 E7.63125 ; skirt
G1 F1800.000 E6.63125 ; retract
G92 E0 ; reset extrusion distance
G1 X100.000 Y108.553 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.858 Y108.267 F540.000 E1.01331 ; perimeter
G1 X100.000 Y108.479 F7800.000 ; move to first perimeter point
G1 X100.142 Y108.267 F540.000 E1.02392 ; perimeter
G1 X100.000 Y108.553 F7800.000 ; move to first perimeter point
G1 X100.000 Y108.553 F540.000 E1.02392 ; perimeter
G1 F1800.000 E0.02392 ; retract
G92 E0 ; reset extrusion distance
G1 X99.395 Y103.879 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X100.130 Y103.965 F540.000 E1.03080 ; perimeter
G1 X103.999 Y103.422 E1.19343 ; perimeter
G1 X107.423 Y101.995 E1.34784 ; perimeter
G1 X110.148 Y99.924 E1.49036 ; perimeter
G1 X110.536 Y99.536 E1.51318 ; perimeter
G1 X107.530 Y96.325 E1.69629 ; perimeter
G1 F1800.000 E0.69629 ; retract
G92 E0 ; reset extrusion distance
G1 X99.887 Y99.427 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.589 Y99.101 F540.000 E1.11331 ; perimeter
G1 X105.115 Y98.086 E1.22663 ; perimeter
G1 X107.327 Y96.327 E1.34428 ; perimeter
G1 F1800.000 E0.34428 ; retract
G92 E0 ; reset extrusion distance
G1 X97.765 Y99.147 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.887 Y99.427 F540.000 E1.08909 ; perimeter
G1 F1800.000 E0.08909 ; retract
G92 E0 ; reset extrusion distance
G1 X94.885 Y98.086 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.765 Y99.147 F540.000 E1.12774 ; perimeter
G1 F1800.000 E0.12774 ; retract
G92 E0 ; reset extrusion distance
G1 X94.364 Y97.722 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X94.885 Y98.086 F540.000 E1.02646 ; perimeter
G1 X94.324 Y97.666 F7800.000 ; move to first perimeter point
G1 X94.364 Y97.722 F540.000 E1.02933 ; perimeter
G1 X93.745 Y97.240 F7800.000 ; move to first perimeter point
G1 X94.324 Y97.666 F540.000 E1.05925 ; perimeter
G1 X93.430 Y97.006 F7800.000 ; move to first perimeter point
G1 X93.745 Y97.240 F540.000 E1.07558 ; perimeter
G1 X93.117 Y96.770 F7800.000 ; move to first perimeter point
G1 X93.430 Y97.006 F540.000 E1.09191 ; perimeter
G1 X92.673 Y96.327 F7800.000 ; move to first perimeter point
G1 X93.117 Y96.770 F540.000 E1.11802 ; perimeter
G1 X92.673 Y96.327 F7800.000 ; move to first perimeter point
G1 X93.165 Y95.835 F540.000 E1.14697 ; perimeter
G1 X93.165 Y95.835 E1.14697 ; perimeter
G1 X93.436 Y95.564 E1.16289 ; perimeter
G1 X93.976 Y95.024 E1.19473 ; perimeter
G1 X95.443 Y93.557 E1.28107 ; perimeter
G1 X95.882 Y93.024 E1.30980 ; perimeter
G1 X95.883 Y93.117 F7800.000 ; move to first perimeter point
G1 X96.325 Y93.560 F540.000 E1.33585 ; perimeter
G1 X96.640 Y93.789 E1.35207 ; perimeter
G1 X97.144 Y94.150 E1.37788 ; perimeter
G1 X98.906 Y94.750 E1.45536 ; perimeter
G1 X100.102 Y94.888 E1.50546 ; perimeter
G1 X101.622 Y94.661 E1.56945 ; perimeter
G1 X103.057 Y94.034 E1.63461 ; perimeter
G1 X104.117 Y93.117 E1.69297 ; perimeter
G1 X101.764 Y90.764 E1.83150 ; perimeter
G1 X101.336 Y90.696 E1.84955 ; perimeter
G1 X101.764 Y90.764 F7800.000 ; move to first perimeter point
G1 X101.687 Y90.382 F540.000 E1.86578 ; perimeter
G1 X101.696 Y90.336 E1.86774 ; perimeter
G1 F1800.000 E0.86774 ; retract
G92 E0 ; reset extrusion distance
G1 X101.752 Y87.248 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.676 Y87.623 F540.000 E1.01593 ; perimeter
G1 X101.377 Y87.324 F7800.000 ; move to first perimeter point
G1 X101.752 Y87.248 F540.000 E1.03185 ; perimeter
G1 X102.754 Y86.246 E1.09082 ; perimeter
G1 X104.118 Y84.976 E1.16842 ; perimeter
G1 X104.117 Y84.883 F7800.000 ; move to first perimeter point
G1 X105.152 Y83.853 F540.000 E1.22921 ; perimeter
G1 X105.163 Y83.829 E1.23030 ; perimeter
G1 X107.328 Y81.882 E1.35150 ; perimeter
G1 X107.327 Y81.673 F7800.000 ; move to first perimeter point
G1 X107.818 Y81.182 F540.000 E1.38045 ; perimeter
G1 X107.823 Y81.179 E1.38067 ; perimeter
G1 X108.102 Y80.903 E1.39700 ; perimeter
G1 X108.626 Y80.367 E1.42823 ; perimeter
G1 X110.536 Y78.464 E1.54046 ; perimeter
G1 F1800.000 E0.54046 ; retract
G92 E0 ; reset extrusion distance
G1 X114.618 Y91.545 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X114.965 Y88.931 F540.000 E1.10979 ; perimeter
G1 X114.438 Y85.060 E1.27242 ; perimeter
G1 X112.934 Y81.472 E1.43436 ; perimeter
G1 X110.536 Y78.464 E1.59449 ; perimeter
G1 F1800.000 E0.59449 ; retract
G92 E0 ; reset extrusion distance
G1 X111.060 Y98.956 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X112.995 Y96.423 F540.000 E1.13269 ; perimeter
G1 X114.422 Y92.999 E1.28710 ; perimeter
G1 X114.618 Y91.545 E1.34816 ; perimeter
G1 F1800.000 E0.34816 ; retract
G92 E0 ; reset extrusion distance
G1 X110.536 Y99.536 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X111.060 Y98.956 F540.000 E1.03255 ; perimeter
G1 X110.536 Y99.536 F7800.000 ; move to first perimeter point
G1 X111.040 Y100.016 F540.000 E1.06152 ; perimeter
G1 X113.210 Y102.069 E1.18586 ; perimeter
G1 X113.083 Y102.083 F7800.000 ; move to first perimeter point
G1 X113.088 Y102.188 F540.000 E1.19023 ; perimeter
G1 F1800.000 E0.19023 ; retract
G92 E0 ; reset extrusion distance
G1 X106.887 Y95.887 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.327 Y96.327 F540.000 E1.02589 ; perimeter
G1 X107.530 Y96.325 E1.03435 ; perimeter
G1 X109.097 Y93.962 E1.15239 ; perimeter
G1 X109.874 Y92.126 E1.23538 ; perimeter
G1 X110.347 Y89.464 E1.34793 ; perimeter
G1 X110.114 Y86.770 E1.46048 ; perimeter
G1 X109.407 Y84.749 E1.54962 ; perimeter
G1 X108.762 Y83.465 E1.60941 ; perimeter
G1 X106.883 Y81.230 E1.73097 ; perimeter
G1 X105.115 Y79.914 E1.82273 ; perimeter
G1 X102.808 Y78.958 E1.92667 ; perimeter
G1 X99.887 Y78.573 E2.04934 ; perimeter
G1 X97.192 Y78.958 E2.16266 ; perimeter
G1 X94.885 Y79.914 E2.26659 ; perimeter
G1 X92.673 Y81.673 E2.38425 ; perimeter
G1 X92.470 Y81.675 E2.39270 ; perimeter
G1 X91.920 Y80.902 E2.43220 ; perimeter
G1 X89.464 Y78.464 E2.57627 ; perimeter
G1 X92.577 Y76.005 E2.74142 ; perimeter
G1 X96.001 Y74.578 E2.89584 ; perimeter
G1 X99.870 Y74.035 E3.05847 ; perimeter
G1 X103.748 Y74.511 E3.22111 ; perimeter
G1 X106.652 Y75.676 E3.35137 ; perimeter
G1 X107.528 Y76.066 E3.39128 ; perimeter
G1 X110.536 Y78.464 E3.55141 ; perimeter
G1 X113.088 Y75.812 E3.70463 ; perimeter
G1 X113.083 Y75.917 F7800.000 ; move to first perimeter point
G1 X113.188 Y75.912 F540.000 E3.70902 ; perimeter
G1 F1800.000 E2.70902 ; retract
G92 E0 ; reset extrusion distance
G1 X119.267 Y89.142 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X119.479 Y89.000 F540.000 E1.01061 ; perimeter
G1 X119.267 Y88.858 E1.02123 ; perimeter
G1 X119.479 Y89.000 F7800.000 ; move to first perimeter point
G1 X119.502 Y89.000 F540.000 E1.02220 ; perimeter
G1 X119.553 Y89.000 E1.02434 ; perimeter
G1 F1800.000 E0.02434 ; retract
G92 E0 ; reset extrusion distance
G1 X105.237 Y94.187 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X106.887 Y95.887 F540.000 E1.09859 ; perimeter
G1 F1800.000 E0.09859 ; retract
G92 E0 ; reset extrusion distance
G1 X105.170 Y94.073 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X105.237 Y94.187 F540.000 E1.00555 ; perimeter
G1 X104.636 Y93.515 F7800.000 ; move to first perimeter point
G1 X105.170 Y94.073 F540.000 E1.03765 ; perimeter
G1 X104.613 Y93.501 F7800.000 ; move to first perimeter point
G1 X104.636 Y93.515 F540.000 E1.03879 ; perimeter
G1 X104.215 Y93.116 F7800.000 ; move to first perimeter point
G1 X104.613 Y93.501 F540.000 E1.06183 ; perimeter
G1 X104.117 Y93.117 F7800.000 ; move to first perimeter point
G1 X105.215 Y91.661 F540.000 E1.13774 ; perimeter
G1 X105.592 Y90.738 E1.17927 ; perimeter
G1 X105.852 Y89.231 E1.24291 ; perimeter
G1 X105.549 Y87.161 E1.32997 ; perimeter
G1 X104.939 Y85.853 E1.39008 ; perimeter
G1 X104.117 Y84.883 E1.44299 ; perimeter
G1 X102.856 Y83.850 E1.51086 ; perimeter
G1 X101.425 Y83.286 E1.57486 ; perimeter
G1 X99.898 Y83.112 E1.63885 ; perimeter
G1 X98.575 Y83.286 E1.69442 ; perimeter
G1 X97.144 Y83.850 E1.75841 ; perimeter
G1 X95.785 Y84.884 E1.82949 ; perimeter
G1 X92.673 Y81.673 E2.01561 ; perimeter
G1 F1800.000 E1.01561 ; retract
G92 E0 ; reset extrusion distance
G1 X86.975 Y96.370 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.464 Y99.536 F540.000 E1.16764 ; perimeter
G1 X92.673 Y96.327 E1.35658 ; perimeter
G1 X90.903 Y93.982 E1.47888 ; perimeter
G1 X90.134 Y92.152 E1.56149 ; perimeter
G1 X89.655 Y89.468 E1.67501 ; perimeter
G1 X89.653 Y88.536 E1.71378 ; perimeter
G1 X90.126 Y85.874 E1.82633 ; perimeter
G1 X90.903 Y84.038 E1.90932 ; perimeter
G1 X92.470 Y81.675 E2.02736 ; perimeter
G1 F1800.000 E1.02736 ; retract
G92 E0 ; reset extrusion distance
G1 X86.628 Y95.447 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.975 Y96.370 F540.000 E1.04106 ; perimeter
G1 F1800.000 E0.04106 ; retract
G92 E0 ; reset extrusion distance
G1 X86.068 Y94.105 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.628 Y95.447 F540.000 E1.06053 ; perimeter
G1 F1800.000 E0.06053 ; retract
G92 E0 ; reset extrusion distance
G1 X85.790 Y93.494 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.068 Y94.105 F540.000 E1.02795 ; perimeter
G1 X85.511 Y92.748 F7800.000 ; move to first perimeter point
G1 X85.790 Y93.494 F540.000 E1.06110 ; perimeter
G1 X85.511 Y92.748 F7800.000 ; move to first perimeter point
G1 X85.059 Y88.810 F540.000 E1.22611 ; perimeter
G1 X85.526 Y85.194 E1.37790 ; perimeter
G1 X86.472 Y82.846 E1.48325 ; perimeter
G1 X87.103 Y81.407 E1.54865 ; perimeter
G1 X89.464 Y78.464 E1.70572 ; perimeter
G1 X86.812 Y75.912 E1.85890 ; perimeter
G1 X86.912 Y75.812 F7800.000 ; move to first perimeter point
G1 X86.917 Y75.917 F540.000 E1.86324 ; perimeter
G1 F1800.000 E0.86324 ; retract
G92 E0 ; reset extrusion distance
G1 X94.634 Y86.781 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X95.028 Y85.899 F540.000 E1.04021 ; perimeter
G1 X95.785 Y84.884 E1.09294 ; perimeter
G1 F1800.000 E0.09294 ; retract
G92 E0 ; reset extrusion distance
G1 X94.238 Y88.110 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X94.634 Y86.781 F540.000 E1.05771 ; perimeter
G1 X94.193 Y88.439 F7800.000 ; move to first perimeter point
G1 X94.238 Y88.110 F540.000 E1.07156 ; perimeter
G1 X94.151 Y89.103 F7800.000 ; move to first perimeter point
G1 X94.193 Y88.439 F540.000 E1.09925 ; perimeter
G1 X94.151 Y89.103 F7800.000 ; move to first perimeter point
G1 X94.162 Y89.301 F540.000 E1.10751 ; perimeter
G1 X94.242 Y89.732 E1.12573 ; perimeter
G1 X94.246 Y89.961 E1.13530 ; perimeter
G1 X94.931 Y91.936 E1.22230 ; perimeter
G1 X95.882 Y93.024 E1.28246 ; perimeter
G1 X98.248 Y90.752 E1.41901 ; perimeter
G1 X98.324 Y90.377 E1.43493 ; perimeter
G1 X98.248 Y90.752 F7800.000 ; move to first perimeter point
G1 X98.623 Y90.676 F540.000 E1.45086 ; perimeter
G1 F1800.000 E0.45086 ; retract
G92 E0 ; reset extrusion distance
G1 X98.226 Y87.304 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.304 Y87.664 F540.000 E1.01534 ; perimeter
G1 X98.226 Y87.304 F7800.000 ; move to first perimeter point
G1 X98.236 Y87.236 F540.000 E1.01821 ; perimeter
G1 F1800.000 E0.01821 ; retract
G92 E0 ; reset extrusion distance
G1 X96.643 Y85.643 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.236 Y87.236 F540.000 E1.09377 ; perimeter
G1 X98.664 Y87.304 E1.11182 ; perimeter
G1 F1800.000 E0.11182 ; retract
G92 E0 ; reset extrusion distance
G1 X96.373 Y85.373 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X96.643 Y85.643 F540.000 E1.01591 ; perimeter
G1 X95.883 Y84.883 F7800.000 ; move to first perimeter point
G1 X96.373 Y85.373 F540.000 E1.04477 ; perimeter
G1 F1800.000 E0.04477 ; retract
G92 E0 ; reset extrusion distance
G1 X80.521 Y89.000 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X80.733 Y88.858 F540.000 E1.01061 ; perimeter
G1 X80.498 Y89.000 F7800.000 ; move to first perimeter point
G1 X80.733 Y89.142 F540.000 E1.02205 ; perimeter
G1 X80.447 Y89.000 F7800.000 ; move to first perimeter point
G1 X80.498 Y89.000 F540.000 E1.02419 ; perimeter
G1 F1800.000 E0.02419 ; retract
G92 E0 ; reset extrusion distance
G1 X87.819 Y101.163 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.464 Y99.536 F540.000 E1.09631 ; perimeter
G1 F1800.000 E0.09631 ; retract
G92 E0 ; reset extrusion distance
G1 X87.629 Y101.389 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X87.819 Y101.163 F540.000 E1.01229 ; perimeter
G1 X86.917 Y102.083 F7800.000 ; move to first perimeter point
G1 X87.629 Y101.389 F540.000 E1.05369 ; perimeter
G1 X86.917 Y102.083 F7800.000 ; move to first perimeter point
G1 X86.931 Y102.210 F540.000 E1.05901 ; perimeter
G1 X86.812 Y102.088 F7800.000 ; move to first perimeter point
G1 X86.917 Y102.083 F540.000 E1.06338 ; perimeter
G1 F1800.000 E0.06338 ; retract
G92 E0 ; reset extrusion distance
G1 X89.464 Y99.536 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.951 Y99.996 F540.000 E1.02789 ; perimeter
G1 X90.128 Y100.124 E1.03699 ; perimeter
G1 X90.363 Y100.288 E1.04893 ; perimeter
G1 X90.644 Y100.505 E1.06370 ; perimeter
G1 X91.735 Y101.369 E1.12161 ; perimeter
G1 X92.630 Y102.025 E1.16781 ; perimeter
G1 X96.060 Y103.438 E1.32222 ; perimeter
G1 X99.395 Y103.879 E1.46228 ; perimeter
G1 F1800.000 E0.46228 ; retract
G92 E0 ; reset extrusion distance
G1 X99.858 Y69.733 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X100.000 Y69.498 F540.000 E1.01143 ; perimeter
G1 X100.000 Y69.447 E1.01357 ; perimeter
G1 X100.000 Y69.521 F7800.000 ; move to first perimeter point
G1 X100.142 Y69.733 F540.000 E1.02419 ; perimeter
G1 F1800.000 E0.02419 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.800 F7800.000 ; move to next layer (1)
G1 X86.832 Y75.925 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.931 Y75.790 F1056.435 E1.00491 ; perimeter
G1 F1800.000 E0.00491 ; retract
G92 E0 ; reset extrusion distance
G1 X110.096 Y99.096 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X110.536 Y99.536 F1056.435 E1.01829 ; perimeter
G1 X112.985 Y96.439 E1.13439 ; perimeter
G1 X114.441 Y92.927 E1.24618 ; perimeter
G1 X114.965 Y89.056 E1.36107 ; perimeter
G1 X114.470 Y85.181 E1.47595 ; perimeter
G1 X112.988 Y81.566 E1.59083 ; perimeter
G1 X110.924 Y78.852 E1.69110 ; perimeter
G1 X110.148 Y78.076 E1.72335 ; perimeter
G1 X107.434 Y76.012 E1.82362 ; perimeter
G1 X103.922 Y74.557 E1.93541 ; perimeter
G1 X100.050 Y74.035 E2.05029 ; perimeter
G1 X96.175 Y74.532 E2.16517 ; perimeter
G1 X92.561 Y76.015 E2.28006 ; perimeter
G1 X89.464 Y78.464 E2.39615 ; perimeter
G1 X86.916 Y75.919 E2.50204 ; perimeter
G1 F1800.000 E1.50204 ; retract
G92 E0 ; reset extrusion distance
G1 X108.266 Y97.266 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X110.096 Y99.096 F1056.435 E1.07612 ; perimeter
G1 F1800.000 E0.07612 ; retract
G92 E0 ; reset extrusion distance
G1 X107.933 Y96.933 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.266 Y97.266 F1056.435 E1.01384 ; perimeter
G1 X107.766 Y96.766 F7800.000 ; move to first perimeter point
G1 X107.933 Y96.933 F1056.435 E1.02076 ; perimeter
G1 X107.327 Y96.327 F7800.000 ; move to first perimeter point
G1 X107.766 Y96.766 F1056.435 E1.03905 ; perimeter
G1 X107.327 Y96.327 F7800.000 ; move to first perimeter point
G1 X107.714 Y95.939 F1056.435 E1.05517 ; perimeter
G1 X108.922 Y94.345 E1.11397 ; perimeter
G1 X110.057 Y91.754 E1.19716 ; perimeter
G1 X110.427 Y88.951 E1.28028 ; perimeter
G1 X110.086 Y86.356 E1.35724 ; perimeter
G1 X109.058 Y83.836 E1.43728 ; perimeter
G1 X107.327 Y81.673 E1.51874 ; perimeter
G1 X107.766 Y81.234 E1.53703 ; perimeter
G1 X107.934 Y81.068 E1.54395 ; perimeter
G1 X110.536 Y78.464 E1.65221 ; perimeter
G1 X110.976 Y78.024 E1.67050 ; perimeter
G1 X111.157 Y77.837 E1.67816 ; perimeter
G1 X111.868 Y77.121 E1.70782 ; perimeter
G1 X112.939 Y76.053 E1.75231 ; perimeter
G1 X112.975 Y76.030 E1.75357 ; perimeter
G1 X113.076 Y75.827 E1.76022 ; perimeter
G1 X113.081 Y75.916 F7800.000 ; move to first perimeter point
G1 X113.177 Y75.920 F1056.435 E1.76306 ; perimeter
G1 X113.210 Y75.931 E1.76406 ; perimeter
G1 F1800.000 E0.76406 ; retract
G92 E0 ; reset extrusion distance
G1 X106.719 Y82.278 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.327 Y81.673 F1056.435 E1.02521 ; perimeter
G1 X105.164 Y79.942 E1.10668 ; perimeter
G1 X102.644 Y78.914 E1.18672 ; perimeter
G1 X100.049 Y78.573 E1.26367 ; perimeter
G1 X97.348 Y78.916 E1.34371 ; perimeter
G1 X94.829 Y79.946 E1.42375 ; perimeter
G1 X92.673 Y81.673 E1.50498 ; perimeter
G1 X92.212 Y82.180 F7800.000 ; move to first perimeter point
G1 X92.673 Y81.673 F1056.435 E1.52512 ; perimeter
G1 F1800.000 E0.52512 ; retract
G92 E0 ; reset extrusion distance
G1 X90.509 Y84.892 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.996 Y83.741 F1056.435 E1.03675 ; perimeter
G1 X92.212 Y82.180 E1.09494 ; perimeter
G1 F1800.000 E0.09494 ; retract
G92 E0 ; reset extrusion distance
G1 X90.037 Y86.020 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.509 Y84.892 F1056.435 E1.03596 ; perimeter
G1 F1800.000 E0.03596 ; retract
G92 E0 ; reset extrusion distance
G1 X89.769 Y87.489 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.037 Y86.020 F1056.435 E1.04388 ; perimeter
G1 X89.703 Y87.973 F7800.000 ; move to first perimeter point
G1 X89.769 Y87.489 F1056.435 E1.05827 ; perimeter
G1 X89.638 Y88.458 F7800.000 ; move to first perimeter point
G1 X89.703 Y87.973 F1056.435 E1.07265 ; perimeter
G1 X89.638 Y88.458 F7800.000 ; move to first perimeter point
G1 X89.573 Y89.049 F1056.435 E1.09012 ; perimeter
G1 X89.808 Y90.734 E1.14015 ; perimeter
G1 X89.877 Y91.247 E1.15538 ; perimeter
G1 X89.941 Y91.746 E1.17016 ; perimeter
G1 X90.848 Y93.938 E1.23993 ; perimeter
G1 X90.996 Y94.259 E1.25031 ; perimeter
G1 X92.673 Y96.327 E1.32861 ; perimeter
G1 X94.016 Y94.995 E1.38422 ; perimeter
G1 X95.883 Y93.117 E1.46207 ; perimeter
G1 X94.871 Y91.892 E1.50879 ; perimeter
G1 X94.297 Y90.466 E1.55399 ; perimeter
G1 X94.112 Y88.940 E1.59919 ; perimeter
G1 X94.328 Y87.418 E1.64439 ; perimeter
G1 X94.878 Y86.096 E1.68651 ; perimeter
G1 X95.883 Y84.883 E1.73282 ; perimeter
G1 X96.487 Y85.487 E1.75796 ; perimeter
G1 X97.485 Y86.485 E1.79946 ; perimeter
G1 X98.252 Y87.252 E1.83134 ; perimeter
G1 X98.664 Y87.304 E1.84356 ; perimeter
G1 X98.249 Y87.386 F7800.000 ; move to first perimeter point
G1 X98.252 Y87.252 F1056.435 E1.84750 ; perimeter
G1 X98.304 Y87.664 F7800.000 ; move to first perimeter point
G1 X98.249 Y87.386 F1056.435 E1.85585 ; perimeter
G1 F1800.000 E0.85585 ; retract
G92 E0 ; reset extrusion distance
G1 X97.652 Y91.348 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.252 Y90.748 F1056.435 E1.02496 ; perimeter
G1 X98.304 Y90.336 E1.03719 ; perimeter
G1 X97.319 Y91.681 F7800.000 ; move to first perimeter point
G1 X97.652 Y91.348 F1056.435 E1.05102 ; perimeter
G1 F1800.000 E0.05102 ; retract
G92 E0 ; reset extrusion distance
G1 X95.883 Y93.117 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.319 Y91.681 F1056.435 E1.05972 ; perimeter
G1 F1800.000 E0.05972 ; retract
G92 E0 ; reset extrusion distance
G1 X95.883 Y93.117 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X96.270 Y93.504 F1056.435 E1.01609 ; perimeter
G1 X96.456 Y93.646 E1.02296 ; perimeter
G1 X96.643 Y93.786 E1.02984 ; perimeter
G1 X96.790 Y93.892 E1.03516 ; perimeter
G1 X97.108 Y94.129 E1.04683 ; perimeter
G1 X98.432 Y94.675 E1.08895 ; perimeter
G1 X99.954 Y94.888 E1.13415 ; perimeter
G1 X101.480 Y94.699 E1.17935 ; perimeter
G1 X102.589 Y94.240 E1.21464 ; perimeter
G1 X102.988 Y94.073 E1.22738 ; perimeter
G1 X104.117 Y93.117 E1.27088 ; perimeter
G1 X101.748 Y90.748 E1.36939 ; perimeter
G1 X101.336 Y90.696 E1.38162 ; perimeter
G1 X101.687 Y90.382 F7800.000 ; move to first perimeter point
G1 X101.748 Y90.748 F1056.435 E1.39254 ; perimeter
G1 X101.687 Y90.382 F7800.000 ; move to first perimeter point
G1 X101.696 Y90.336 F1056.435 E1.39393 ; perimeter
G1 F1800.000 E0.39393 ; retract
G92 E0 ; reset extrusion distance
G1 X101.748 Y87.252 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.696 Y87.664 F1056.435 E1.01223 ; perimeter
G1 X101.382 Y87.313 F7800.000 ; move to first perimeter point
G1 X101.748 Y87.252 F1056.435 E1.02315 ; perimeter
G1 X104.117 Y84.883 E1.12166 ; perimeter
G1 X104.117 Y84.883 F7800.000 ; move to first perimeter point
G1 X104.722 Y84.275 F1056.435 E1.14687 ; perimeter
G1 X105.883 Y83.107 E1.19531 ; perimeter
G1 X106.719 Y82.278 E1.22992 ; perimeter
G1 F1800.000 E0.22992 ; retract
G92 E0 ; reset extrusion distance
G1 X101.336 Y87.304 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.382 Y87.313 F1056.435 E1.00139 ; perimeter
G1 F1800.000 E0.00139 ; retract
G92 E0 ; reset extrusion distance
G1 X98.252 Y90.748 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.664 Y90.696 F1056.435 E1.01223 ; perimeter
G1 F1800.000 E0.01223 ; retract
G92 E0 ; reset extrusion distance
G1 X104.117 Y93.117 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.117 Y93.117 F1800.000 ; perimeter
G1 F1800.000 E0.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X107.327 Y96.327 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.327 Y96.327 F1800.000 ; perimeter
G1 F1800.000 E0.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X105.445 Y97.860 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.327 Y96.327 F1056.435 E1.07137 ; perimeter
G1 X104.117 Y93.117 E1.20484 ; perimeter
G1 X105.122 Y91.904 E1.25115 ; perimeter
G1 X105.672 Y90.582 E1.29327 ; perimeter
G1 X105.888 Y89.060 E1.33847 ; perimeter
G1 X105.675 Y87.432 E1.38675 ; perimeter
G1 X105.129 Y86.108 E1.42886 ; perimeter
G1 X104.504 Y85.270 E1.45960 ; perimeter
G1 X103.730 Y84.496 E1.49179 ; perimeter
G1 X102.892 Y83.871 E1.52253 ; perimeter
G1 X101.466 Y83.297 E1.56773 ; perimeter
G1 X100.046 Y83.112 E1.60984 ; perimeter
G1 X98.520 Y83.301 E1.65504 ; perimeter
G1 X97.096 Y83.878 E1.70024 ; perimeter
G1 X95.883 Y84.883 E1.74655 ; perimeter
G1 X89.464 Y78.464 E2.01348 ; perimeter
G1 F1800.000 E1.01348 ; retract
G92 E0 ; reset extrusion distance
G1 X87.066 Y81.472 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.464 Y78.464 F1056.435 E1.11312 ; perimeter
G1 F1800.000 E0.11312 ; retract
G92 E0 ; reset extrusion distance
G1 X86.580 Y82.629 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X87.066 Y81.472 F1056.435 E1.03692 ; perimeter
G1 X86.398 Y83.060 F7800.000 ; move to first perimeter point
G1 X86.580 Y82.629 F1056.435 E1.05066 ; perimeter
G1 X86.304 Y83.283 F7800.000 ; move to first perimeter point
G1 X86.398 Y83.060 F1056.435 E1.05779 ; perimeter
G1 F1800.000 E0.05779 ; retract
G92 E0 ; reset extrusion distance
G1 X85.459 Y85.816 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X85.559 Y85.073 F1056.435 E1.02206 ; perimeter
G1 X86.304 Y83.283 E1.07906 ; perimeter
G1 F1800.000 E0.07906 ; retract
G92 E0 ; reset extrusion distance
G1 X85.416 Y86.091 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X85.459 Y85.816 F1056.435 E1.00817 ; perimeter
G1 X85.388 Y86.320 F7800.000 ; move to first perimeter point
G1 X85.416 Y86.091 F1056.435 E1.01495 ; perimeter
G1 X85.357 Y86.548 F7800.000 ; move to first perimeter point
G1 X85.388 Y86.320 F1056.435 E1.02174 ; perimeter
G1 X85.357 Y86.548 F7800.000 ; move to first perimeter point
G1 X85.324 Y86.783 F1056.435 E1.02869 ; perimeter
G1 X85.130 Y88.224 E1.07144 ; perimeter
G1 X85.035 Y88.944 E1.09282 ; perimeter
G1 X85.128 Y89.736 E1.11626 ; perimeter
G1 X85.557 Y92.922 E1.21079 ; perimeter
G1 X87.012 Y96.434 E1.32258 ; perimeter
G1 X89.464 Y99.536 E1.43885 ; perimeter
G1 X92.673 Y96.327 E1.57232 ; perimeter
G1 X93.061 Y96.714 E1.58843 ; perimeter
G1 X93.162 Y96.777 E1.59193 ; perimeter
G1 X93.328 Y96.904 E1.59808 ; perimeter
G1 X94.182 Y97.572 E1.62998 ; perimeter
G1 X94.836 Y98.058 E1.65393 ; perimeter
G1 X97.254 Y99.059 E1.73088 ; perimeter
G1 X99.036 Y99.297 E1.78375 ; perimeter
G1 X100.057 Y99.427 E1.81400 ; perimeter
G1 X102.652 Y99.084 E1.89096 ; perimeter
G1 X105.445 Y97.860 E1.98065 ; perimeter
G1 F1800.000 E0.98065 ; retract
G92 E0 ; reset extrusion distance
G1 X107.012 Y102.161 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.528 Y101.934 F1056.435 E1.01657 ; perimeter
G1 X110.536 Y99.536 E1.12968 ; perimeter
G1 X110.976 Y99.976 E1.14797 ; perimeter
G1 X113.083 Y102.083 E1.23562 ; perimeter
G1 X113.210 Y102.069 E1.23936 ; perimeter
G1 X113.080 Y102.177 F7800.000 ; move to first perimeter point
G1 X113.083 Y102.083 F1056.435 E1.24212 ; perimeter
G1 X113.069 Y102.210 F7800.000 ; move to first perimeter point
G1 X113.080 Y102.177 F1056.435 E1.24313 ; perimeter
G1 F1800.000 E0.24313 ; retract
G92 E0 ; reset extrusion distance
G1 X95.015 Y102.994 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X96.181 Y103.470 F1056.435 E1.03701 ; perimeter
G1 X100.056 Y103.965 E1.15189 ; perimeter
G1 X103.825 Y103.468 E1.26369 ; perimeter
G1 X107.012 Y102.161 E1.36500 ; perimeter
G1 F1800.000 E0.36500 ; retract
G92 E0 ; reset extrusion distance
G1 X89.976 Y100.000 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X92.472 Y101.934 F1056.435 E1.09286 ; perimeter
G1 X95.015 Y102.994 E1.17388 ; perimeter
G1 F1800.000 E0.17388 ; retract
G92 E0 ; reset extrusion distance
G1 X89.852 Y99.924 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.976 Y100.000 F1056.435 E1.00428 ; perimeter
G1 X89.464 Y99.536 F7800.000 ; move to first perimeter point
G1 X89.852 Y99.924 F1056.435 E1.02040 ; perimeter
G1 F1800.000 E0.02040 ; retract
G92 E0 ; reset extrusion distance
G1 X87.698 Y101.312 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.464 Y99.536 F1056.435 E1.07365 ; perimeter
G1 F1800.000 E0.07365 ; retract
G92 E0 ; reset extrusion distance
G1 X86.916 Y102.081 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X87.698 Y101.312 F1056.435 E1.03223 ; perimeter
G1 X86.916 Y102.081 F7800.000 ; move to first perimeter point
G1 X86.931 Y102.210 F1056.435 E1.03604 ; perimeter
G1 X86.827 Y102.076 F7800.000 ; move to first perimeter point
G1 X86.916 Y102.081 F1056.435 E1.03867 ; perimeter
G1 F1800.000 E0.03867 ; retract
G92 E0 ; reset extrusion distance
G1 X86.827 Y75.924 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.832 Y75.925 F1056.435 E1.00015 ; perimeter
M106 S255 ; enable fan
G1 F1800.000 E0.00015 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.200 F7800.000 ; move to next layer (2)
G1 X86.919 Y75.919 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.924 Y75.827 F1055.303 E1.00270 ; perimeter
G1 F1800.000 E0.00270 ; retract
G92 E0 ; reset extrusion distance
G1 X87.353 Y81.098 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.464 Y78.464 F1055.303 E1.09925 ; perimeter
G1 X86.827 Y75.924 E1.20690 ; perimeter
G1 F1800.000 E0.20690 ; retract
G92 E0 ; reset extrusion distance
G1 X85.213 Y87.609 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X85.557 Y85.081 F1055.303 E1.07500 ; perimeter
G1 X87.011 Y81.567 E1.18685 ; perimeter
G1 X87.353 Y81.098 E1.20392 ; perimeter
G1 F1800.000 E0.20392 ; retract
G92 E0 ; reset extrusion distance
G1 X85.096 Y88.509 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X85.213 Y87.609 F1055.303 E1.02669 ; perimeter
G1 X85.035 Y88.953 F7800.000 ; move to first perimeter point
G1 X85.096 Y88.509 F1055.303 E1.03988 ; perimeter
G1 X85.035 Y89.061 F7800.000 ; move to first perimeter point
G1 X85.035 Y88.953 F1055.303 E1.04305 ; perimeter
G1 X85.035 Y89.061 F7800.000 ; move to first perimeter point
G1 X85.067 Y89.189 F1055.303 E1.04694 ; perimeter
G1 X85.100 Y89.439 E1.05434 ; perimeter
G1 X85.133 Y89.812 E1.06535 ; perimeter
G1 X85.199 Y90.187 E1.07656 ; perimeter
G1 X85.331 Y91.313 E1.10990 ; perimeter
G1 X85.429 Y91.934 E1.12837 ; perimeter
G1 X85.559 Y92.928 E1.15787 ; perimeter
G1 X87.016 Y96.442 E1.26973 ; perimeter
G1 X89.076 Y99.148 E1.36974 ; perimeter
G1 X89.464 Y99.536 E1.38586 ; perimeter
G1 X91.207 Y97.793 E1.45836 ; perimeter
G1 X92.673 Y96.327 E1.51932 ; perimeter
G1 X90.943 Y94.167 E1.60069 ; perimeter
G1 X89.915 Y91.647 E1.68073 ; perimeter
G1 X89.573 Y88.946 E1.76077 ; perimeter
G1 X89.942 Y86.250 E1.84081 ; perimeter
G1 X90.943 Y83.833 E1.91773 ; perimeter
G1 X92.673 Y81.673 E1.99909 ; perimeter
G1 X92.673 Y81.673 F7800.000 ; move to first perimeter point
G1 X93.113 Y82.113 F1055.303 E2.01738 ; perimeter
G1 X95.883 Y84.883 E2.13256 ; perimeter
G1 X97.096 Y83.878 E2.17887 ; perimeter
G1 X98.520 Y83.301 E2.22407 ; perimeter
G1 X100.046 Y83.112 E2.26927 ; perimeter
G1 X101.568 Y83.325 E2.31447 ; perimeter
G1 X102.920 Y83.887 E2.35754 ; perimeter
G1 X104.117 Y84.883 E2.40331 ; perimeter
G1 X107.327 Y81.673 E2.53678 ; perimeter
G1 X107.766 Y81.234 E2.55507 ; perimeter
G1 X108.432 Y80.568 E2.58275 ; perimeter
G1 X108.608 Y80.392 E2.59005 ; perimeter
G1 X109.902 Y79.098 E2.64388 ; perimeter
G1 X110.536 Y78.464 E2.67024 ; perimeter
G1 F1800.000 E1.67024 ; retract
G92 E0 ; reset extrusion distance
G1 X113.509 Y95.140 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X114.470 Y92.818 F1055.303 E1.07390 ; perimeter
G1 X114.965 Y89.047 E1.18576 ; perimeter
G1 X114.468 Y85.172 E1.30064 ; perimeter
G1 X112.928 Y81.460 E1.41880 ; perimeter
G1 X110.536 Y78.464 E1.53153 ; perimeter
G1 F1800.000 E0.53153 ; retract
G92 E0 ; reset extrusion distance
G1 X111.571 Y98.307 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X112.934 Y96.528 F1055.303 E1.06590 ; perimeter
G1 X113.509 Y95.140 E1.11007 ; perimeter
G1 F1800.000 E0.11007 ; retract
G92 E0 ; reset extrusion distance
G1 X111.392 Y98.527 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X111.571 Y98.307 F1055.303 E1.00834 ; perimeter
G1 X110.536 Y99.536 F7800.000 ; move to first perimeter point
G1 X111.392 Y98.527 F1055.303 E1.04725 ; perimeter
G1 X110.536 Y99.536 F7800.000 ; move to first perimeter point
G1 X111.646 Y100.637 F1055.303 E1.09322 ; perimeter
G1 X113.176 Y102.079 E1.15504 ; perimeter
G1 X113.080 Y102.177 F7800.000 ; move to first perimeter point
G1 X113.084 Y102.079 F1055.303 E1.15793 ; perimeter
G1 X113.069 Y102.210 F7800.000 ; move to first perimeter point
G1 X113.080 Y102.177 F1055.303 E1.15894 ; perimeter
G1 F1800.000 E0.15894 ; retract
G92 E0 ; reset extrusion distance
G1 X107.327 Y96.327 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.327 Y96.327 F1800.000 ; perimeter
G1 F1800.000 E0.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X104.117 Y93.117 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.117 Y93.117 F1800.000 ; perimeter
G1 F1800.000 E0.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X102.340 Y94.343 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.988 Y94.073 F1055.303 E1.02066 ; perimeter
G1 X104.117 Y93.117 E1.06415 ; perimeter
G1 X101.754 Y90.754 E1.16241 ; perimeter
G1 X101.386 Y90.697 E1.17337 ; perimeter
G1 X101.754 Y90.754 F7800.000 ; move to first perimeter point
G1 X101.697 Y90.386 F1055.303 E1.18433 ; perimeter
G1 F1800.000 E0.18433 ; retract
G92 E0 ; reset extrusion distance
G1 X101.687 Y87.618 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.696 Y87.664 F1055.303 E1.00139 ; perimeter
G1 X101.687 Y87.618 F7800.000 ; move to first perimeter point
G1 X101.748 Y87.252 F1055.303 E1.01231 ; perimeter
G1 X101.336 Y87.304 E1.02454 ; perimeter
G1 X101.748 Y87.252 F7800.000 ; move to first perimeter point
G1 X102.016 Y86.984 F1055.303 E1.03567 ; perimeter
G1 X102.191 Y86.809 E1.04297 ; perimeter
G1 X104.117 Y84.883 E1.12305 ; perimeter
G1 F1800.000 E0.12305 ; retract
G92 E0 ; reset extrusion distance
G1 X99.828 Y99.398 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.750 Y99.058 F1055.303 E1.08650 ; perimeter
G1 X105.270 Y97.997 E1.16689 ; perimeter
G1 X107.327 Y96.327 E1.24480 ; perimeter
G1 X104.117 Y93.117 E1.37826 ; perimeter
G1 X105.122 Y91.904 E1.42458 ; perimeter
G1 X105.699 Y90.480 E1.46977 ; perimeter
G1 X105.888 Y88.954 E1.51497 ; perimeter
G1 X105.675 Y87.432 E1.56017 ; perimeter
G1 X105.113 Y86.080 E1.60324 ; perimeter
G1 X104.117 Y84.883 E1.64901 ; perimeter
G1 F1800.000 E0.64901 ; retract
G92 E0 ; reset extrusion distance
G1 X98.768 Y99.269 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.828 Y99.398 F1055.303 E1.03142 ; perimeter
G1 F1800.000 E0.03142 ; retract
G92 E0 ; reset extrusion distance
G1 X94.964 Y98.095 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.250 Y99.058 F1055.303 E1.07292 ; perimeter
G1 X98.768 Y99.269 E1.11799 ; perimeter
G1 F1800.000 E0.11799 ; retract
G92 E0 ; reset extrusion distance
G1 X93.278 Y96.882 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X94.964 Y98.095 F1055.303 E1.06108 ; perimeter
G1 F1800.000 E0.06108 ; retract
G92 E0 ; reset extrusion distance
G1 X92.673 Y96.327 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X93.278 Y96.882 F1055.303 E1.02415 ; perimeter
G1 X92.673 Y96.327 F7800.000 ; move to first perimeter point
G1 X93.113 Y95.887 F1055.303 E1.04244 ; perimeter
G1 X93.118 Y95.879 E1.04269 ; perimeter
G1 X93.472 Y95.521 E1.05752 ; perimeter
G1 X93.783 Y95.225 E1.07013 ; perimeter
G1 X95.883 Y93.117 E1.15762 ; perimeter
G1 X95.883 Y93.117 F7800.000 ; move to first perimeter point
G1 X96.256 Y93.490 F1055.303 E1.17314 ; perimeter
G1 X96.528 Y93.688 E1.18302 ; perimeter
G1 X96.588 Y93.750 E1.18558 ; perimeter
G1 X96.823 Y93.923 E1.19414 ; perimeter
G1 X98.432 Y94.675 E1.24637 ; perimeter
G1 X99.954 Y94.888 E1.29157 ; perimeter
G1 X101.480 Y94.699 E1.33677 ; perimeter
G1 X102.340 Y94.343 E1.36414 ; perimeter
G1 F1800.000 E0.36414 ; retract
G92 E0 ; reset extrusion distance
G1 X98.386 Y90.751 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.664 Y90.696 F1055.303 E1.00835 ; perimeter
G1 X98.252 Y90.748 F7800.000 ; move to first perimeter point
G1 X98.386 Y90.751 F1055.303 E1.01229 ; perimeter
G1 F1800.000 E0.01229 ; retract
G92 E0 ; reset extrusion distance
G1 X94.667 Y91.390 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X94.933 Y92.000 F1055.303 E1.01958 ; perimeter
G1 X95.883 Y93.117 E1.06270 ; perimeter
G1 X98.252 Y90.748 E1.16121 ; perimeter
G1 X98.304 Y90.336 E1.17344 ; perimeter
G1 F1800.000 E0.17344 ; retract
G92 E0 ; reset extrusion distance
G1 X94.325 Y90.568 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X94.667 Y91.390 F1055.303 E1.02617 ; perimeter
G1 X94.294 Y90.342 F7800.000 ; move to first perimeter point
G1 X94.325 Y90.568 F1055.303 E1.03288 ; perimeter
G1 X94.201 Y89.707 F7800.000 ; move to first perimeter point
G1 X94.294 Y90.342 F1055.303 E1.05174 ; perimeter
G1 X94.201 Y89.707 F7800.000 ; move to first perimeter point
G1 X94.142 Y89.266 F1055.303 E1.06483 ; perimeter
G1 X94.187 Y88.403 E1.09025 ; perimeter
G1 X94.320 Y87.450 E1.11855 ; perimeter
G1 X94.878 Y86.096 E1.16162 ; perimeter
G1 X95.883 Y84.883 E1.20793 ; perimeter
G1 F1800.000 E0.20793 ; retract
G92 E0 ; reset extrusion distance
G1 X98.240 Y87.301 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X95.883 Y84.883 F1055.303 E1.09931 ; perimeter
G1 F1800.000 E0.09931 ; retract
G92 E0 ; reset extrusion distance
G1 X98.240 Y87.301 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.301 Y87.611 F1055.303 E1.00929 ; perimeter
G1 X98.303 Y87.614 E1.00939 ; perimeter
G1 X98.246 Y87.246 F7800.000 ; move to first perimeter point
G1 X98.301 Y87.240 F1055.303 E1.01103 ; perimeter
G1 X98.611 Y87.301 E1.02032 ; perimeter
G1 X98.614 Y87.303 E1.02042 ; perimeter
G1 F1800.000 E0.02042 ; retract
G92 E0 ; reset extrusion distance
G1 X93.113 Y82.113 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X93.113 Y82.113 F1800.000 ; perimeter
G1 F1800.000 E0.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X92.673 Y96.327 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X92.673 Y96.327 F1800.000 ; perimeter
G1 F1800.000 E0.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X87.189 Y101.802 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.464 Y99.536 F1055.303 E1.09441 ; perimeter
G1 F1800.000 E0.09441 ; retract
G92 E0 ; reset extrusion distance
G1 X87.024 Y101.969 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X87.189 Y101.802 F1055.303 E1.00692 ; perimeter
G1 X86.790 Y102.069 F7800.000 ; move to first perimeter point
G1 X87.024 Y101.969 F1055.303 E1.01438 ; perimeter
G1 X86.921 Y102.084 F7800.000 ; move to first perimeter point
G1 X86.921 Y102.176 F1055.303 E1.01710 ; perimeter
G1 F1800.000 E0.01710 ; retract
G92 E0 ; reset extrusion distance
G1 X89.464 Y99.536 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.967 Y99.995 F1055.303 E1.02003 ; perimeter
G1 X92.558 Y101.984 F1055.303 E1.11606 ; perimeter
G1 X96.072 Y103.441 E1.22792 ; perimeter
G1 X99.943 Y103.965 E1.34280 ; perimeter
G1 X103.818 Y103.470 E1.45768 ; perimeter
G1 X107.433 Y101.989 E1.57256 ; perimeter
G1 X110.536 Y99.536 E1.68887 ; perimeter
G1 X107.327 Y96.327 E1.82233 ; perimeter
G1 X109.057 Y94.167 E1.90370 ; perimeter
G1 X110.085 Y91.647 E1.98374 ; perimeter
G1 X110.427 Y88.946 E2.06378 ; perimeter
G1 X110.058 Y86.250 E2.14382 ; perimeter
G1 X108.997 Y83.730 E2.22420 ; perimeter
G1 X107.723 Y82.070 E2.28572 ; perimeter
G1 X106.930 Y81.277 E2.31873 ; perimeter
G1 X105.167 Y79.943 E2.38372 ; perimeter
G1 X102.750 Y78.942 E2.46063 ; perimeter
G1 X100.289 Y78.604 E2.53368 ; perimeter
G1 X97.353 Y78.915 E2.62050 ; perimeter
G1 X94.730 Y80.003 E2.70401 ; perimeter
G1 X92.673 Y81.673 E2.78192 ; perimeter
G1 X89.464 Y78.464 E2.91538 ; perimeter
G1 X92.567 Y76.011 E3.03169 ; perimeter
G1 X96.182 Y74.530 E3.14657 ; perimeter
G1 X99.953 Y74.035 E3.25842 ; perimeter
G1 X103.815 Y74.529 E3.37289 ; perimeter
G1 X107.442 Y76.016 E3.48818 ; perimeter
G1 X110.536 Y78.464 E3.60419 ; perimeter
G1 X113.083 Y75.917 E3.71012 ; perimeter
G1 X113.069 Y75.790 E3.71386 ; perimeter
G1 X113.083 Y75.917 F7800.000 ; move to first perimeter point
G1 X113.177 Y75.920 F1055.303 E3.71663 ; perimeter
G1 X113.210 Y75.931 E3.71763 ; perimeter
G1 F1800.000 E2.71763 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.600 F7800.000 ; move to next layer (3)
G1 X113.056 Y75.861 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X113.173 Y75.924 F1049.869 E1.00388 ; perimeter
G1 F1800.000 E0.00388 ; retract
G92 E0 ; reset extrusion distance
G1 X104.285 Y74.724 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.521 Y76.090 F1049.869 E1.10328 ; perimeter
G1 X110.535 Y78.313 E1.21340 ; perimeter
G1 X113.059 Y75.917 E1.31574 ; perimeter
G1 F1800.000 E0.31574 ; retract
G92 E0 ; reset extrusion distance
G1 X103.137 Y92.140 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.119 Y92.950 F1049.869 E1.03742 ; perimeter
G1 X105.073 Y91.988 E1.07726 ; perimeter
G1 X105.701 Y90.472 E1.12553 ; perimeter
G1 X105.888 Y88.946 E1.17073 ; perimeter
G1 X105.701 Y87.528 E1.21278 ; perimeter
G1 X105.126 Y86.103 E1.25798 ; perimeter
G1 X104.504 Y85.270 E1.28855 ; perimeter
G1 X103.730 Y84.496 E1.32072 ; perimeter
G1 X102.906 Y83.894 E1.35075 ; perimeter
G1 X101.471 Y83.321 E1.39618 ; perimeter
G1 X100.190 Y83.142 E1.43422 ; perimeter
G1 X98.334 Y83.378 E1.48922 ; perimeter
G1 X97.046 Y83.925 E1.53037 ; perimeter
G1 X95.883 Y84.883 E1.57469 ; perimeter
G1 X89.464 Y78.464 E1.84162 ; perimeter
G1 X92.617 Y76.049 E1.95840 ; perimeter
G1 X96.434 Y74.496 E2.07958 ; perimeter
G1 X100.309 Y74.067 E2.19423 ; perimeter
G1 X103.868 Y74.575 E2.29993 ; perimeter
G1 X104.285 Y74.724 E2.31296 ; perimeter
G1 F1800.000 E1.31296 ; retract
G92 E0 ; reset extrusion distance
G1 X102.074 Y91.073 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.137 Y92.140 F1049.869 E1.04429 ; perimeter
G1 X101.891 Y90.891 F7800.000 ; move to first perimeter point
G1 X102.074 Y91.073 F1049.869 E1.05187 ; perimeter
G1 X101.752 Y90.751 F7800.000 ; move to first perimeter point
G1 X101.891 Y90.891 F1049.869 E1.05767 ; perimeter
G1 X101.385 Y90.694 F7800.000 ; move to first perimeter point
G1 X101.752 Y90.751 F1049.869 E1.06859 ; perimeter
G1 X101.698 Y90.373 E1.07983 ; perimeter
G1 X101.370 Y90.698 F7800.000 ; move to first perimeter point
G1 X101.385 Y90.694 F1049.869 E1.08028 ; perimeter
G1 F1800.000 E0.08028 ; retract
G92 E0 ; reset extrusion distance
G1 X98.615 Y90.694 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.630 Y90.698 F1049.869 E1.00044 ; perimeter
G1 X98.250 Y90.752 F7800.000 ; move to first perimeter point
G1 X98.615 Y90.694 F1049.869 E1.01132 ; perimeter
G1 F1800.000 E0.01132 ; retract
G92 E0 ; reset extrusion distance
G1 X96.506 Y92.493 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.250 Y90.752 F1049.869 E1.07247 ; perimeter
G1 X98.251 Y90.621 E1.07631 ; perimeter
G1 F1800.000 E0.07631 ; retract
G92 E0 ; reset extrusion distance
G1 X96.327 Y92.673 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X96.506 Y92.493 F1049.869 E1.00747 ; perimeter
G1 X95.883 Y93.117 F7800.000 ; move to first perimeter point
G1 X96.327 Y92.673 F1049.869 E1.02594 ; perimeter
G1 F1800.000 E0.02594 ; retract
G92 E0 ; reset extrusion distance
G1 X103.902 Y98.548 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X105.273 Y97.958 F1049.869 E1.04388 ; perimeter
G1 X106.929 Y96.708 E1.10490 ; perimeter
G1 X107.220 Y96.328 E1.11899 ; perimeter
G1 X104.117 Y93.117 E1.25028 ; perimeter
G1 X102.886 Y94.127 E1.29709 ; perimeter
G1 X101.566 Y94.654 E1.33890 ; perimeter
G1 X100.047 Y94.881 E1.38405 ; perimeter
G1 X98.529 Y94.679 E1.42909 ; perimeter
G1 X97.201 Y94.155 E1.47106 ; perimeter
G1 X95.883 Y93.117 E1.52040 ; perimeter
G1 F1800.000 E0.52040 ; retract
G92 E0 ; reset extrusion distance
G1 X95.017 Y98.113 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.424 Y99.067 F1049.869 E1.07612 ; perimeter
G1 X100.115 Y99.410 E1.15589 ; perimeter
G1 X102.551 Y99.074 E1.22820 ; perimeter
G1 X103.902 Y98.548 E1.27083 ; perimeter
G1 F1800.000 E0.27083 ; retract
G92 E0 ; reset extrusion distance
G1 X93.759 Y97.229 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X95.017 Y98.113 F1049.869 E1.04522 ; perimeter
G1 F1800.000 E0.04522 ; retract
G92 E0 ; reset extrusion distance
G1 X93.183 Y96.799 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X93.759 Y97.229 F1049.869 E1.02116 ; perimeter
G1 X93.175 Y96.789 F7800.000 ; move to first perimeter point
G1 X93.183 Y96.799 F1049.869 E1.02152 ; perimeter
G1 X92.674 Y96.425 F7800.000 ; move to first perimeter point
G1 X93.175 Y96.789 F1049.869 E1.03972 ; perimeter
G1 X91.883 Y97.120 F7800.000 ; move to first perimeter point
G1 X92.673 Y96.327 F1049.869 E1.07265 ; perimeter
G1 F1800.000 E0.07265 ; retract
G92 E0 ; reset extrusion distance
G1 X90.801 Y98.198 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X91.883 Y97.120 F1049.869 E1.04493 ; perimeter
G1 X90.622 Y98.377 F7800.000 ; move to first perimeter point
G1 X90.801 Y98.198 F1049.869 E1.05234 ; perimeter
G1 X90.269 Y98.732 F7800.000 ; move to first perimeter point
G1 X90.622 Y98.377 F1049.869 E1.06708 ; perimeter
G1 X90.088 Y98.912 F7800.000 ; move to first perimeter point
G1 X90.269 Y98.732 F1049.869 E1.07459 ; perimeter
G1 X89.464 Y99.536 F7800.000 ; move to first perimeter point
G1 X90.088 Y98.912 F1049.869 E1.10054 ; perimeter
G1 X89.465 Y99.677 F7800.000 ; move to first perimeter point
G1 X90.045 Y100.074 F1049.869 E1.12120 ; perimeter
G1 X90.449 Y100.383 E1.13614 ; perimeter
G1 X90.579 Y100.463 E1.14064 ; perimeter
G1 X92.263 Y101.775 E1.20340 ; perimeter
G1 X92.828 Y102.070 E1.22216 ; perimeter
G1 X95.836 Y103.344 E1.31822 ; perimeter
G1 X97.700 Y103.653 E1.37377 ; perimeter
G1 X100.001 Y103.965 E1.44207 ; perimeter
G1 X103.863 Y103.427 E1.55672 ; perimeter
G1 X107.706 Y101.763 E1.67985 ; perimeter
G1 X109.940 Y100.084 E1.76203 ; perimeter
G1 X110.382 Y99.537 E1.78272 ; perimeter
G1 X110.536 Y99.536 F7800.000 ; move to first perimeter point
G1 X110.982 Y99.982 F1049.869 E1.80126 ; perimeter
G1 X111.160 Y100.160 E1.80867 ; perimeter
G1 X111.338 Y100.338 E1.81609 ; perimeter
G1 X111.517 Y100.517 E1.82350 ; perimeter
G1 X112.052 Y101.052 E1.84574 ; perimeter
G1 X113.173 Y102.076 E1.89040 ; perimeter
G1 X113.075 Y102.168 F7800.000 ; move to first perimeter point
G1 X113.081 Y102.081 F1049.869 E1.89296 ; perimeter
G1 X113.075 Y102.168 F7800.000 ; move to first perimeter point
G1 X113.076 Y102.173 F1049.869 E1.89311 ; perimeter
G1 F1800.000 E0.89311 ; retract
G92 E0 ; reset extrusion distance
G1 X109.733 Y98.730 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X110.382 Y99.537 F1049.869 E1.03047 ; perimeter
G1 X110.536 Y99.536 E1.03499 ; perimeter
G1 X112.991 Y96.430 E1.15139 ; perimeter
G1 X114.471 Y92.815 E1.26627 ; perimeter
G1 X114.965 Y89.001 E1.37935 ; perimeter
G1 X114.456 Y85.128 E1.49423 ; perimeter
G1 X113.094 Y81.818 E1.59948 ; perimeter
G1 X112.930 Y81.464 E1.61094 ; perimeter
G1 X110.536 Y78.464 E1.72381 ; perimeter
G1 X110.535 Y78.313 E1.72824 ; perimeter
G1 F1800.000 E0.72824 ; retract
G92 E0 ; reset extrusion distance
G1 X108.786 Y80.151 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X110.536 Y78.464 F1049.869 E1.07146 ; perimeter
G1 F1800.000 E0.07146 ; retract
G92 E0 ; reset extrusion distance
G1 X108.419 Y80.502 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.786 Y80.151 F1049.869 E1.01493 ; perimeter
G1 F1800.000 E0.01493 ; retract
G92 E0 ; reset extrusion distance
G1 X107.383 Y81.617 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.419 Y80.502 F1049.869 E1.04476 ; perimeter
G1 F1800.000 E0.04476 ; retract
G92 E0 ; reset extrusion distance
G1 X106.524 Y82.476 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.383 Y81.617 F1049.869 E1.03572 ; perimeter
G1 F1800.000 E0.03572 ; retract
G92 E0 ; reset extrusion distance
G1 X104.117 Y84.883 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X106.524 Y82.476 F1049.869 E1.10010 ; perimeter
G1 F1800.000 E0.10010 ; retract
G92 E0 ; reset extrusion distance
G1 X101.883 Y87.120 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.117 Y84.883 F1049.869 E1.09297 ; perimeter
G1 F1800.000 E0.09297 ; retract
G92 E0 ; reset extrusion distance
G1 X101.750 Y87.248 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.883 Y87.120 F1049.869 E1.00543 ; perimeter
G1 X101.749 Y87.379 F7800.000 ; move to first perimeter point
G1 X101.750 Y87.248 F1049.869 E1.00927 ; perimeter
G1 X101.370 Y87.302 E1.02056 ; perimeter
G1 F1800.000 E0.02056 ; retract
G92 E0 ; reset extrusion distance
G1 X97.568 Y86.569 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.248 Y87.249 F1049.869 E1.02828 ; perimeter
G1 X98.630 Y87.302 E1.03961 ; perimeter
G1 F1800.000 E0.03961 ; retract
G92 E0 ; reset extrusion distance
G1 X96.672 Y85.674 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.568 Y86.569 F1049.869 E1.03724 ; perimeter
G1 X96.506 Y85.504 F7800.000 ; move to first perimeter point
G1 X96.672 Y85.674 F1049.869 E1.04422 ; perimeter
G1 X96.328 Y85.326 F7800.000 ; move to first perimeter point
G1 X96.506 Y85.504 F1049.869 E1.05163 ; perimeter
G1 X95.881 Y85.050 F7800.000 ; move to first perimeter point
G1 X96.328 Y85.326 F1049.869 E1.06706 ; perimeter
G1 F1800.000 E0.06706 ; retract
G92 E0 ; reset extrusion distance
G1 X94.367 Y94.633 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X95.883 Y93.117 F1049.869 E1.06303 ; perimeter
G1 X94.874 Y91.897 E1.10957 ; perimeter
G1 X94.299 Y90.472 E1.15477 ; perimeter
G1 X94.112 Y89.054 E1.19683 ; perimeter
G1 X94.299 Y87.528 E1.24203 ; perimeter
G1 X94.874 Y86.103 E1.28723 ; perimeter
G1 X95.881 Y85.050 E1.33007 ; perimeter
G1 X95.883 Y84.883 E1.33499 ; perimeter
G1 F1800.000 E0.33499 ; retract
G92 E0 ; reset extrusion distance
G1 X90.011 Y91.876 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X91.003 Y94.270 F1049.869 E1.07620 ; perimeter
G1 X92.673 Y96.327 E1.15411 ; perimeter
G1 X94.367 Y94.633 E1.22455 ; perimeter
G1 F1800.000 E0.22455 ; retract
G92 E0 ; reset extrusion distance
G1 X89.709 Y89.963 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X90.011 Y91.876 F1049.869 E1.05695 ; perimeter
G1 F1800.000 E0.05695 ; retract
G92 E0 ; reset extrusion distance
G1 X89.641 Y89.579 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.709 Y89.963 F1049.869 E1.01147 ; perimeter
G1 X89.607 Y89.193 F7800.000 ; move to first perimeter point
G1 X89.641 Y89.579 F1049.869 E1.02287 ; perimeter
G1 X89.573 Y89.064 F7800.000 ; move to first perimeter point
G1 X89.607 Y89.193 F1049.869 E1.02677 ; perimeter
G1 X89.573 Y89.064 F7800.000 ; move to first perimeter point
G1 X89.912 Y86.364 F1049.869 E1.10681 ; perimeter
G1 X90.541 Y84.801 E1.15634 ; perimeter
G1 X91.003 Y83.730 E1.19064 ; perimeter
G1 X91.516 Y83.135 E1.21375 ; perimeter
G1 X92.200 Y82.341 E1.24455 ; perimeter
G1 X92.736 Y81.778 E1.26742 ; perimeter
G1 F1800.000 E0.26742 ; retract
G92 E0 ; reset extrusion distance
G1 X108.585 Y94.779 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X109.062 Y94.158 F1049.869 E1.02302 ; perimeter
G1 X110.055 Y91.761 E1.09930 ; perimeter
G1 X110.427 Y88.936 E1.18310 ; perimeter
G1 X110.055 Y86.239 E1.26314 ; perimeter
G1 X109.062 Y83.842 E1.33942 ; perimeter
G1 X107.383 Y81.617 E1.42140 ; perimeter
G1 X105.296 Y80.056 E1.49805 ; perimeter
G1 X102.828 Y79.000 E1.57697 ; perimeter
G1 X99.883 Y78.610 E1.66433 ; perimeter
G1 X97.449 Y78.926 E1.73649 ; perimeter
G1 X94.951 Y79.914 E1.81549 ; perimeter
G1 X93.071 Y81.292 E1.88403 ; perimeter
G1 X92.734 Y81.734 E1.90037 ; perimeter
G1 F1800.000 E0.90037 ; retract
G92 E0 ; reset extrusion distance
G1 X107.327 Y96.327 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X108.585 Y94.779 F1049.869 E1.05867 ; perimeter
G1 X107.327 Y96.327 F7800.000 ; move to first perimeter point
G1 X107.771 Y96.774 F1049.869 E1.07722 ; perimeter
G1 X108.847 Y97.850 E1.12194 ; perimeter
G1 X109.733 Y98.730 E1.15867 ; perimeter
G1 F1800.000 E0.15867 ; retract
G92 E0 ; reset extrusion distance
G1 X107.220 Y96.328 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.327 Y96.327 F1049.869 E1.00314 ; perimeter
G1 F1800.000 E0.00314 ; retract
G92 E0 ; reset extrusion distance
G1 X104.117 Y93.117 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.119 Y92.950 F1049.869 E1.00492 ; perimeter
G1 F1800.000 E0.00492 ; retract
G92 E0 ; reset extrusion distance
G1 X98.242 Y87.328 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.302 Y87.627 F1049.869 E1.00897 ; perimeter
G1 X98.242 Y87.328 F7800.000 ; move to first perimeter point
G1 X98.248 Y87.249 F1049.869 E1.01131 ; perimeter
G1 F1800.000 E0.01131 ; retract
G92 E0 ; reset extrusion distance
G1 X86.919 Y75.919 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X86.924 Y75.827 F1049.869 E1.00270 ; perimeter
G1 F1800.000 E0.00270 ; retract
G92 E0 ; reset extrusion distance
G1 X87.591 Y101.408 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X89.017 Y99.980 F1049.869 E1.05932 ; perimeter
G1 X89.465 Y99.677 E1.07524 ; perimeter
G1 X89.464 Y99.536 E1.07938 ; perimeter
G1 X87.070 Y96.536 E1.19225 ; perimeter
G1 X86.906 Y96.182 E1.20372 ; perimeter
G1 X85.544 Y92.872 E1.30897 ; perimeter
G1 X85.035 Y88.999 E1.42385 ; perimeter
G1 X85.529 Y85.185 E1.53692 ; perimeter
G1 X87.009 Y81.570 E1.65181 ; perimeter
G1 X89.464 Y78.464 E1.76821 ; perimeter
G1 X86.827 Y75.924 E1.87586 ; perimeter
G1 F1800.000 E0.87586 ; retract
G92 E0 ; reset extrusion distance
G1 X87.239 Y101.762 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X87.591 Y101.408 F1049.869 E1.01470 ; perimeter
G1 X86.832 Y102.075 F7800.000 ; move to first perimeter point
G1 X87.239 Y101.762 F1049.869 E1.02978 ; perimeter
G1 X86.827 Y102.076 F7800.000 ; move to first perimeter point
G1 X86.832 Y102.075 F1049.869 E1.02994 ; perimeter
G1 X86.919 Y102.081 F7800.000 ; move to first perimeter point
G1 X86.923 Y102.173 F1049.869 E1.03265 ; perimeter
G1 F1800.000 E0.03265 ; retract
G92 E0 ; reset extrusion distance
G1 X113.056 Y75.861 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X113.059 Y75.850 F1049.869 E1.00035 ; perimeter
G1 F1800.000 E0.00035 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used = 40.9mm (0.3cm3)

; acceleration = 0
; bed_size = 200,200
; bed_temperature = 60
; bottom_solid_layers = 3
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_width = 0
; complete_objects = 0
; cooling = 1
; disable_fan_first_layers = 2
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors
; external_perimeter_speed = 100%
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_diameter = 3
; fill_angle = 45
; fill_density = 0.4
; fill_pattern = rectilinear
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 200%
; first_layer_height = 100%
; first_layer_speed = 30%
; first_layer_temperature = 185
; g0 = 0
; gap_fill_speed = 20
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_speed = 60
; layer_gcode = 
; layer_height = 0.4
; max_fan_speed = 100
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.5
; only_retract_when_crossing_perimeters = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 25
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 30
; perimeters = 3
; post_process = 
; print_center = 100,89
; randomize_start = 1
; retract_before_travel = 2
; retract_length = 1
; retract_length_toolchange = 3
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 30
; rotate = 0
; scale = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_speed = 60
; start_gcode = M104 S185 ; set extruder temperature\nG28 ; home all axes
; support_material = 0
; support_material_angle = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 45
; temperature = 185
; threads = 2
; top_solid_infill_speed = 50
; top_solid_layers = 3
; travel_speed = 130
; use_relative_e_distances = 0
; vibration_limit = 0
; z_offset = 0
