; generated by Slic3r 0.9.8-dev on 2013-02-16 at 14:32:04

; layer_height = 0.4
; perimeters = 3
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 0.40
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; scale = 1
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.53mm
; infill extrusion width = 0.53mm
; first layer extrusion width = 0.80mm

M190 S60 ; wait for bed temperature to be reached
M104 S185 ; set temperature
G28 ; home all axes
G92 E0 ;reset extruder
M109 S185 ; wait for temperature to be reached
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 F1800.000 E-1.00000 ; retract
G1 Z1.400 ; move to next layer (0) and lift
G92 E0 ; reset extrusion distance
G1 X107.933 Y97.467 F7800.000 ; move to first skirt point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X107.483 Y97.777 F900.000 E1.02275 ; skirt
G1 X106.773 Y98.177 E1.05667 ; skirt
G1 X106.013 Y98.477 E1.09068 ; skirt
G1 X105.493 Y98.627 E1.11321 ; skirt
G1 X104.963 Y98.737 E1.13574 ; skirt
G1 X104.693 Y98.777 E1.14711 ; skirt
G1 X103.883 Y98.827 E1.18089 ; skirt
G1 X75.843 Y98.817 E2.34813 ; skirt
G1 X75.303 Y98.777 E2.37067 ; skirt
G1 X75.032 Y98.737 E2.38203 ; skirt
G1 X74.503 Y98.627 E2.40456 ; skirt
G1 X73.983 Y98.477 E2.42709 ; skirt
G1 X73.223 Y98.177 E2.46110 ; skirt
G1 X72.743 Y97.917 E2.48383 ; skirt
G1 X72.282 Y97.627 E2.50646 ; skirt
G1 X71.853 Y97.307 E2.52878 ; skirt
G1 X71.443 Y96.947 E2.55149 ; skirt
G1 X70.893 Y96.347 E2.58537 ; skirt
G1 X70.422 Y95.687 E2.61910 ; skirt
G1 X70.023 Y94.977 E2.65302 ; skirt
G1 X69.723 Y94.217 E2.68703 ; skirt
G1 X69.513 Y93.437 E2.72066 ; skirt
G1 X69.422 Y92.897 E2.74345 ; skirt
G1 X69.373 Y92.087 E2.77723 ; skirt
G1 X69.373 Y77.907 E3.36751 ; skirt
G1 X69.422 Y77.097 E3.40129 ; skirt
G1 X69.513 Y76.557 E3.42408 ; skirt
G1 X69.723 Y75.777 E3.45771 ; skirt
G1 X70.023 Y75.017 E3.49172 ; skirt
G1 X70.282 Y74.537 E3.51444 ; skirt
G1 X70.573 Y74.077 E3.53708 ; skirt
G1 X70.893 Y73.647 E3.55939 ; skirt
G1 X71.253 Y73.237 E3.58211 ; skirt
G1 X71.853 Y72.687 E3.61599 ; skirt
G1 X72.282 Y72.367 E3.63830 ; skirt
G1 X72.743 Y72.077 E3.66094 ; skirt
G1 X73.223 Y71.817 E3.68366 ; skirt
G1 X73.723 Y71.607 E3.70624 ; skirt
G1 X74.503 Y71.367 E3.74021 ; skirt
G1 X75.032 Y71.257 E3.76274 ; skirt
G1 X75.303 Y71.217 E3.77410 ; skirt
G1 X76.113 Y71.167 E3.80789 ; skirt
G1 X104.153 Y71.177 E4.97512 ; skirt
G1 X104.693 Y71.217 E4.99766 ; skirt
G1 X104.963 Y71.257 E5.00902 ; skirt
G1 X105.493 Y71.367 E5.03156 ; skirt
G1 X106.013 Y71.517 E5.05409 ; skirt
G1 X106.773 Y71.817 E5.08810 ; skirt
G1 X107.252 Y72.077 E5.11082 ; skirt
G1 X107.713 Y72.367 E5.13346 ; skirt
G1 X108.143 Y72.687 E5.15577 ; skirt
G1 X108.553 Y73.047 E5.17848 ; skirt
G1 X109.103 Y73.647 E5.21237 ; skirt
G1 X109.573 Y74.307 E5.24610 ; skirt
G1 X109.972 Y75.017 E5.28002 ; skirt
G1 X110.273 Y75.777 E5.31403 ; skirt
G1 X110.483 Y76.557 E5.34766 ; skirt
G1 X110.573 Y77.097 E5.37045 ; skirt
G1 X110.623 Y77.907 E5.40423 ; skirt
G1 X110.623 Y92.087 E5.99451 ; skirt
G1 X110.573 Y92.897 E6.02829 ; skirt
G1 X110.483 Y93.437 E6.05108 ; skirt
G1 X110.273 Y94.217 E6.08470 ; skirt
G1 X109.972 Y94.977 E6.11872 ; skirt
G1 X109.713 Y95.457 E6.14144 ; skirt
G1 X109.423 Y95.917 E6.16408 ; skirt
G1 X109.103 Y96.347 E6.18639 ; skirt
G1 X108.923 Y96.557 E6.19790 ; skirt
G1 X108.553 Y96.947 E6.22028 ; skirt
G1 X108.020 Y97.400 E6.24938 ; skirt
G1 X107.933 Y97.467 E6.25397 ; skirt
G1 F1800.000 E5.25397 ; retract
G1 Z1.400 ; move to next layer (0) and lift
G92 E0 ; reset extrusion distance
G1 X101.837 Y90.049 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.437 Y90.355 F720.000 E1.02095 ; perimeter
G1 X100.972 Y90.546 E1.04189 ; perimeter
G1 X100.473 Y90.610 E1.06284 ; perimeter
G1 X99.974 Y90.544 E1.08378 ; perimeter
G1 X99.510 Y90.350 E1.10473 ; perimeter
G1 X99.111 Y90.043 E1.12567 ; perimeter
G1 X98.806 Y89.643 E1.14662 ; perimeter
G1 X98.615 Y89.177 E1.16756 ; perimeter
G1 X98.550 Y88.678 E1.18851 ; perimeter
G1 X98.617 Y88.180 E1.20946 ; perimeter
G1 X98.811 Y87.715 E1.23040 ; perimeter
G1 X98.874 Y87.634 E1.23470 ; perimeter
G1 X99.118 Y87.317 E1.25135 ; perimeter
G1 X99.518 Y87.011 E1.27229 ; perimeter
G1 X99.983 Y86.820 E1.29324 ; perimeter
G1 X100.482 Y86.756 E1.31418 ; perimeter
G1 X100.981 Y86.822 E1.33513 ; perimeter
G1 X101.445 Y87.016 E1.35607 ; perimeter
G1 X101.844 Y87.323 E1.37702 ; perimeter
G1 X102.149 Y87.723 E1.39797 ; perimeter
G1 X102.340 Y88.189 E1.41891 ; perimeter
G1 X102.405 Y88.688 E1.43986 ; perimeter
G1 X102.338 Y89.186 E1.46080 ; perimeter
G1 X102.144 Y89.651 E1.48175 ; perimeter
G1 X101.905 Y89.962 E1.49810 ; perimeter
G1 X101.837 Y90.049 E1.50269 ; perimeter
G1 X101.995 Y90.768 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50269 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.229 Y84.122 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X100.478 Y84.220 F720.000 E1.03155 ; perimeter
G1 X99.726 Y84.122 E1.06310 ; perimeter
G1 X99.026 Y83.831 E1.09466 ; perimeter
G1 X98.424 Y83.370 E1.12621 ; perimeter
G1 X97.963 Y82.769 E1.15776 ; perimeter
G1 X97.673 Y82.068 E1.18931 ; perimeter
G1 X97.655 Y81.934 E1.19495 ; perimeter
G1 X97.574 Y81.317 E1.22086 ; perimeter
G1 X97.673 Y80.566 E1.25241 ; perimeter
G1 X97.963 Y79.865 E1.28397 ; perimeter
G1 X98.424 Y79.264 E1.31552 ; perimeter
G1 X99.026 Y78.803 E1.34707 ; perimeter
G1 X100.478 Y78.201 E1.41248 ; perimeter
G1 X101.929 Y78.803 E1.47789 ; perimeter
G1 X102.531 Y79.264 E1.50944 ; perimeter
G1 X102.992 Y79.865 E1.54099 ; perimeter
G1 X103.593 Y81.317 E1.60641 ; perimeter
G1 X102.992 Y82.769 E1.67182 ; perimeter
G1 X102.531 Y83.370 E1.70337 ; perimeter
G1 X101.929 Y83.831 E1.73492 ; perimeter
G1 X101.331 Y84.079 E1.76188 ; perimeter
G1 X101.229 Y84.122 E1.76647 ; perimeter
G1 X101.008 Y84.823 F7800.000 ; move inwards before travel
G1 F1800.000 E0.76647 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X81.394 Y81.777 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X81.211 Y82.246 F720.000 E1.02095 ; perimeter
G1 X80.913 Y82.651 E1.04189 ; perimeter
G1 X80.521 Y82.966 E1.06284 ; perimeter
G1 X80.060 Y83.168 E1.08378 ; perimeter
G1 X79.563 Y83.244 E1.10473 ; perimeter
G1 X79.165 Y83.200 E1.12138 ; perimeter
G1 X79.062 Y83.189 E1.12567 ; perimeter
G1 X78.594 Y83.006 E1.14662 ; perimeter
G1 X78.188 Y82.708 E1.16756 ; perimeter
G1 X77.874 Y82.315 E1.18851 ; perimeter
G1 X77.671 Y81.854 E1.20946 ; perimeter
G1 X77.595 Y81.357 E1.23040 ; perimeter
G1 X77.651 Y80.857 E1.25135 ; perimeter
G1 X77.688 Y80.761 E1.25564 ; perimeter
G1 X77.834 Y80.388 E1.27229 ; perimeter
G1 X78.132 Y79.983 E1.29324 ; perimeter
G1 X78.524 Y79.668 E1.31418 ; perimeter
G1 X78.891 Y79.507 E1.33083 ; perimeter
G1 X78.985 Y79.466 E1.33513 ; perimeter
G1 X79.482 Y79.390 E1.35607 ; perimeter
G1 X79.983 Y79.445 E1.37702 ; perimeter
G1 X80.355 Y79.591 E1.39367 ; perimeter
G1 X80.451 Y79.628 E1.39797 ; perimeter
G1 X80.857 Y79.926 E1.41891 ; perimeter
G1 X81.171 Y80.319 E1.43986 ; perimeter
G1 X81.373 Y80.780 E1.46080 ; perimeter
G1 X81.450 Y81.277 E1.48175 ; perimeter
G1 X81.406 Y81.667 E1.49810 ; perimeter
G1 X81.394 Y81.777 E1.50269 ; perimeter
G1 X81.902 Y82.309 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50269 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.274 Y85.878 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X80.974 Y86.169 F720.000 E1.03155 ; perimeter
G1 X81.576 Y86.630 E1.06310 ; perimeter
G1 X81.658 Y86.737 E1.06875 ; perimeter
G1 X82.037 Y87.231 E1.09466 ; perimeter
G1 X82.327 Y87.932 E1.12621 ; perimeter
G1 X82.426 Y88.683 E1.15776 ; perimeter
G1 X82.327 Y89.434 E1.18931 ; perimeter
G1 X82.275 Y89.560 E1.19495 ; perimeter
G1 X82.037 Y90.135 E1.22086 ; perimeter
G1 X81.576 Y90.736 E1.25241 ; perimeter
G1 X80.974 Y91.197 E1.28397 ; perimeter
G1 X79.522 Y91.799 E1.34938 ; perimeter
G1 X78.071 Y91.197 E1.41479 ; perimeter
G1 X77.469 Y90.736 E1.44634 ; perimeter
G1 X77.008 Y90.135 E1.47789 ; perimeter
G1 X76.407 Y88.683 E1.54330 ; perimeter
G1 X77.008 Y87.231 E1.60871 ; perimeter
G1 X77.469 Y86.630 E1.64026 ; perimeter
G1 X78.071 Y86.169 E1.67182 ; perimeter
G1 X78.771 Y85.878 E1.70337 ; perimeter
G1 X79.522 Y85.780 E1.73492 ; perimeter
G1 X80.165 Y85.864 E1.76188 ; perimeter
G1 X80.274 Y85.878 E1.76647 ; perimeter
G1 X80.816 Y85.382 F7800.000 ; move inwards before travel
G1 F1800.000 E0.76647 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X97.618 Y90.622 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X83.428 Y90.622 F900.000 E1.59070 ; perimeter
G1 X83.760 Y89.819 E1.62689 ; perimeter
G1 X83.910 Y88.683 E1.67457 ; perimeter
G1 X83.760 Y87.547 E1.72225 ; perimeter
G1 X83.322 Y86.489 E1.76993 ; perimeter
G1 X82.625 Y85.581 E1.81760 ; perimeter
G1 X81.716 Y84.883 E1.86528 ; perimeter
G1 X80.901 Y84.546 E1.90199 ; perimeter
G1 X81.984 Y83.679 E1.95975 ; perimeter
G1 X82.512 Y82.961 E1.99682 ; perimeter
G1 X82.835 Y82.131 E2.03390 ; perimeter
G1 X82.933 Y81.246 E2.07097 ; perimeter
G1 X82.799 Y80.366 E2.10804 ; perimeter
G1 X82.365 Y79.378 E2.15293 ; perimeter
G1 X96.572 Y79.378 E2.74433 ; perimeter
G1 X96.240 Y80.181 E2.78053 ; perimeter
G1 X96.090 Y81.317 E2.82820 ; perimeter
G1 X96.240 Y82.453 E2.87588 ; perimeter
G1 X96.678 Y83.511 E2.92356 ; perimeter
G1 X97.375 Y84.419 E2.97124 ; perimeter
G1 X98.284 Y85.117 E3.01891 ; perimeter
G1 X99.121 Y85.463 E3.05664 ; perimeter
G1 X98.071 Y86.265 E3.11162 ; perimeter
G1 X97.527 Y86.970 E3.14870 ; perimeter
G1 X97.184 Y87.792 E3.18577 ; perimeter
G1 X97.066 Y88.675 E3.22284 ; perimeter
G1 X97.180 Y89.558 E3.25991 ; perimeter
G1 X97.576 Y90.520 E3.30320 ; perimeter
G1 X97.618 Y90.622 E3.30779 ; perimeter
G1 F1800.000 E2.30779 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.336 Y91.357 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.361 Y90.575 F720.000 E1.05366 ; perimeter
G1 X103.152 Y89.549 E1.10761 ; perimeter
G1 X103.152 Y91.357 E1.18289 ; perimeter
G1 X101.446 Y91.357 E1.25389 ; perimeter
G1 X101.336 Y91.357 E1.25848 ; perimeter
G1 X99.612 Y91.357 F7800.000 ; move to first perimeter point
G1 X82.026 Y91.357 F900.000 E1.99053 ; perimeter
G1 X82.680 Y90.506 E2.03522 ; perimeter
G1 X83.044 Y89.627 E2.07483 ; perimeter
G1 X83.168 Y88.683 E2.11444 ; perimeter
G1 X83.044 Y87.739 E2.15406 ; perimeter
G1 X82.768 Y87.075 E2.18400 ; perimeter
G1 X82.680 Y86.860 E2.19367 ; perimeter
G1 X82.100 Y86.105 E2.23329 ; perimeter
G1 X81.345 Y85.526 E2.27290 ; perimeter
G1 X80.466 Y85.162 E2.31252 ; perimeter
G1 X79.522 Y85.038 E2.35213 ; perimeter
G1 X78.579 Y85.162 E2.39175 ; perimeter
G1 X77.700 Y85.526 E2.43136 ; perimeter
G1 X76.848 Y86.179 E2.47605 ; perimeter
G1 X76.848 Y82.211 E2.64123 ; perimeter
G1 X77.675 Y83.243 E2.69626 ; perimeter
G1 X78.236 Y83.656 E2.72527 ; perimeter
G1 X78.885 Y83.909 E2.75428 ; perimeter
G1 X79.578 Y83.986 E2.78329 ; perimeter
G1 X80.267 Y83.881 E2.81230 ; perimeter
G1 X80.905 Y83.601 E2.84130 ; perimeter
G1 X81.449 Y83.165 E2.87031 ; perimeter
G1 X81.862 Y82.603 E2.89932 ; perimeter
G1 X82.115 Y81.954 E2.92833 ; perimeter
G1 X82.191 Y81.261 E2.95734 ; perimeter
G1 X82.086 Y80.573 E2.98635 ; perimeter
G1 X81.806 Y79.935 E3.01536 ; perimeter
G1 X81.370 Y79.391 E3.04436 ; perimeter
G1 X80.352 Y78.643 E3.09695 ; perimeter
G1 X97.974 Y78.643 E3.83049 ; perimeter
G1 X97.320 Y79.494 E3.87517 ; perimeter
G1 X96.956 Y80.374 E3.91479 ; perimeter
G1 X96.832 Y81.317 E3.95440 ; perimeter
G1 X96.956 Y82.261 E3.99402 ; perimeter
G1 X97.320 Y83.140 E4.03363 ; perimeter
G1 X97.900 Y83.895 E4.07325 ; perimeter
G1 X98.655 Y84.474 E4.11286 ; perimeter
G1 X99.534 Y84.838 E4.15248 ; perimeter
G1 X100.478 Y84.962 E4.19209 ; perimeter
G1 X101.421 Y84.838 E4.23171 ; perimeter
G1 X102.300 Y84.474 E4.27132 ; perimeter
G1 X103.152 Y83.821 E4.31601 ; perimeter
G1 X103.152 Y87.825 E4.48269 ; perimeter
G1 X102.370 Y86.800 E4.53635 ; perimeter
G1 X101.818 Y86.374 E4.56536 ; perimeter
G1 X101.175 Y86.106 E4.59437 ; perimeter
G1 X100.484 Y86.014 E4.62338 ; perimeter
G1 X99.793 Y86.103 E4.65238 ; perimeter
G1 X99.148 Y86.368 E4.68139 ; perimeter
G1 X98.594 Y86.791 E4.71040 ; perimeter
G1 X98.169 Y87.343 E4.73941 ; perimeter
G1 X97.901 Y87.986 E4.76842 ; perimeter
G1 X97.808 Y88.677 E4.79743 ; perimeter
G1 X97.897 Y89.368 E4.82643 ; perimeter
G1 X98.163 Y90.012 E4.85544 ; perimeter
G1 X98.585 Y90.566 E4.88445 ; perimeter
G1 X99.524 Y91.290 E4.93380 ; perimeter
G1 X99.612 Y91.357 E4.93840 ; perimeter
G1 F1800.000 E3.93840 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X78.628 Y78.643 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.596 Y79.469 F720.000 E1.05504 ; perimeter
G1 X76.848 Y80.487 E1.10762 ; perimeter
G1 X76.848 Y78.643 E1.18440 ; perimeter
G1 X78.518 Y78.643 E1.25390 ; perimeter
G1 X78.628 Y78.643 E1.25849 ; perimeter
G1 F1800.000 E0.25849 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.113 Y77.907 F7800.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.888 Y77.907 F900.000 E2.15621 ; perimeter
G1 X103.888 Y92.093 E2.74673 ; perimeter
G1 X76.113 Y92.093 E3.90294 ; perimeter
G1 X76.113 Y78.017 E4.48887 ; perimeter
G1 X76.113 Y77.907 E4.49347 ; perimeter
G1 X76.750 Y78.275 F7800.000 ; move inwards before travel
G1 F1800.000 E3.49347 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X84.728 Y90.120 F7800.000 ; move to first fill point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X84.259 Y89.652 F1800.000 E1.02899 ; fill
G1 X84.387 Y88.685 E1.07168 ; fill
G1 X85.822 Y90.120 E1.16052 ; fill
G1 X86.916 Y90.120 E1.20840 ; fill
G1 X84.292 Y87.497 E1.37080 ; fill
G1 X83.589 Y85.699 E1.45531 ; fill
G1 X88.010 Y90.120 E1.72899 ; fill
G1 X89.103 Y90.120 E1.77688 ; fill
G1 X82.563 Y83.580 E2.18176 ; fill
G1 X82.993 Y82.916 E2.21639 ; fill
G1 X90.197 Y90.120 E2.66237 ; fill
G1 X91.291 Y90.120 E2.71026 ; fill
G1 X83.300 Y82.129 E3.20496 ; fill
G1 X83.423 Y81.158 E3.24782 ; fill
G1 X92.385 Y90.120 E3.80265 ; fill
G1 X93.479 Y90.120 E3.85053 ; fill
G1 X83.261 Y79.902 E4.48313 ; fill
G1 X84.333 Y79.880 E4.53006 ; fill
G1 X94.573 Y90.120 E5.16402 ; fill
G1 X95.667 Y90.120 E5.21191 ; fill
G1 X85.427 Y79.880 E5.84586 ; fill
G1 X86.521 Y79.880 E5.89375 ; fill
G1 X96.708 Y90.067 E6.52442 ; fill
G1 X96.568 Y88.833 E6.57879 ; fill
G1 X87.615 Y79.880 E7.13307 ; fill
G1 X88.709 Y79.880 E7.18095 ; fill
G1 X96.698 Y87.869 E7.67553 ; fill
G1 X97.012 Y87.089 E7.71232 ; fill
G1 X89.803 Y79.880 E8.15864 ; fill
G1 X90.897 Y79.880 E8.20653 ; fill
G1 X97.437 Y86.420 E8.61143 ; fill
G1 X96.411 Y84.301 E8.71452 ; fill
G1 X91.990 Y79.880 E8.98819 ; fill
G1 X93.084 Y79.880 E9.03608 ; fill
G1 X95.708 Y82.503 E9.19847 ; fill
G1 X95.613 Y81.315 E9.25064 ; fill
G1 X94.178 Y79.880 E9.33948 ; fill
G1 X95.272 Y79.880 E9.38737 ; fill
G1 X95.741 Y80.348 E9.41636 ; fill
G1 F1800.000 E8.41636 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.022 Y84.647 F7800.000 ; move to first fill point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X79.753 Y84.379 F600.000 E1.00905 ; fill
G1 X77.850 Y84.964 F7800.000 ; move to first fill point
G1 X77.382 Y84.495 F600.000 E1.03662 ; fill
G1 F1800.000 E0.03662 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X77.115 Y91.559 F7800.000 ; move to first fill point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.646 Y91.091 F600.000 E1.02757 ; fill
G1 F1800.000 E0.02757 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X100.139 Y85.637 F7800.000 ; move to first fill point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.871 Y85.369 F600.000 E1.00905 ; fill
G1 F1800.000 E0.00905 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X102.007 Y85.758 F7800.000 ; move to first fill point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.538 Y85.290 F600.000 E1.02757 ; fill
G1 F1800.000 E0.02757 ; retract
G1 Z1.400 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.354 Y79.005 F7800.000 ; move to first fill point
G1 Z0.400 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.885 Y78.536 F600.000 E1.02759 ; fill
G1 X102.790 Y78.441 F7800.000 ; move to first fill point
G1 X103.259 Y78.909 F600.000 E1.05518 ; fill
G1 F1800.000 E0.05518 ; retract
G1 Z1.800 ; move to next layer (1) and lift
G92 E0 ; reset extrusion distance
G1 X101.082 Y86.450 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.639 Y86.683 F1440.000 E1.01775 ; perimeter
G1 X101.915 Y86.896 E1.02802 ; perimeter
G1 X102.117 Y87.051 E1.03551 ; perimeter
G1 X102.483 Y87.531 E1.05326 ; perimeter
G1 X102.713 Y88.090 E1.07102 ; perimeter
G1 X102.790 Y88.689 E1.08877 ; perimeter
G1 X102.710 Y89.287 E1.10653 ; perimeter
G1 X102.612 Y89.522 E1.11401 ; perimeter
G1 X102.478 Y89.844 E1.12428 ; perimeter
G1 X102.109 Y90.322 E1.14204 ; perimeter
G1 X101.629 Y90.689 E1.15979 ; perimeter
G1 X101.306 Y90.822 E1.17006 ; perimeter
G1 X101.071 Y90.919 E1.17754 ; perimeter
G1 X100.472 Y90.996 E1.19530 ; perimeter
G1 X99.873 Y90.916 E1.21305 ; perimeter
G1 X99.316 Y90.683 E1.23081 ; perimeter
G1 X98.838 Y90.315 E1.24856 ; perimeter
G1 X98.472 Y89.835 E1.26632 ; perimeter
G1 X98.242 Y89.276 E1.28407 ; perimeter
G1 X98.165 Y88.677 E1.30183 ; perimeter
G1 X98.245 Y88.079 E1.31958 ; perimeter
G1 X98.343 Y87.844 E1.32707 ; perimeter
G1 X98.477 Y87.522 E1.33733 ; perimeter
G1 X98.846 Y87.044 E1.35509 ; perimeter
G1 X99.326 Y86.677 E1.37284 ; perimeter
G1 X99.884 Y86.447 E1.39060 ; perimeter
G1 X100.483 Y86.370 E1.40835 ; perimeter
G1 X101.004 Y86.440 E1.42382 ; perimeter
G1 X101.082 Y86.450 E1.42611 ; perimeter
G1 X100.945 Y86.956 F7800.000 ; move to first perimeter point
G1 X101.376 Y87.136 F1440.000 E1.43984 ; perimeter
G1 X101.598 Y87.308 E1.44810 ; perimeter
G1 X101.745 Y87.421 E1.45357 ; perimeter
G1 X102.029 Y87.792 E1.46730 ; perimeter
G1 X102.206 Y88.224 E1.48103 ; perimeter
G1 X102.266 Y88.687 E1.49476 ; perimeter
G1 X102.204 Y89.150 E1.50849 ; perimeter
G1 X102.024 Y89.581 E1.52223 ; perimeter
G1 X101.739 Y89.951 E1.53596 ; perimeter
G1 X101.368 Y90.234 E1.54969 ; perimeter
G1 X101.108 Y90.341 E1.55795 ; perimeter
G1 X100.936 Y90.412 E1.56342 ; perimeter
G1 X100.473 Y90.472 E1.57715 ; perimeter
G1 X100.010 Y90.410 E1.59088 ; perimeter
G1 X99.579 Y90.230 E1.60461 ; perimeter
G1 X99.210 Y89.945 E1.61834 ; perimeter
G1 X98.926 Y89.574 E1.63207 ; perimeter
G1 X98.749 Y89.142 E1.64581 ; perimeter
G1 X98.689 Y88.679 E1.65954 ; perimeter
G1 X98.751 Y88.216 E1.67327 ; perimeter
G1 X98.931 Y87.785 E1.68700 ; perimeter
G1 X99.216 Y87.415 E1.70073 ; perimeter
G1 X99.587 Y87.132 E1.71446 ; perimeter
G1 X100.019 Y86.954 E1.72819 ; perimeter
G1 X100.482 Y86.894 E1.74192 ; perimeter
G1 X100.867 Y86.946 E1.75336 ; perimeter
G1 X100.945 Y86.956 E1.75565 ; perimeter
G1 X101.329 Y86.606 F7800.000 ; move inwards before travel
G1 F1800.000 E0.75565 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.193 Y83.988 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X100.477 Y84.082 F1440.000 E1.02122 ; perimeter
G1 X99.762 Y83.988 E1.04245 ; perimeter
G1 X99.095 Y83.711 E1.06367 ; perimeter
G1 X98.747 Y83.444 E1.07657 ; perimeter
G1 X98.523 Y83.272 E1.08489 ; perimeter
G1 X98.083 Y82.699 E1.10612 ; perimeter
G1 X97.807 Y82.033 E1.12734 ; perimeter
G1 X97.713 Y81.317 E1.14856 ; perimeter
G1 X97.807 Y80.601 E1.16979 ; perimeter
G1 X98.083 Y79.935 E1.19101 ; perimeter
G1 X98.256 Y79.710 E1.19934 ; perimeter
G1 X98.523 Y79.362 E1.21223 ; perimeter
G1 X99.095 Y78.923 E1.23346 ; perimeter
G1 X99.762 Y78.646 E1.25468 ; perimeter
G1 X100.477 Y78.552 E1.27590 ; perimeter
G1 X101.193 Y78.646 E1.29713 ; perimeter
G1 X101.860 Y78.923 E1.31835 ; perimeter
G1 X102.208 Y79.190 E1.33124 ; perimeter
G1 X102.432 Y79.362 E1.33957 ; perimeter
G1 X102.872 Y79.935 E1.36080 ; perimeter
G1 X103.148 Y80.601 E1.38202 ; perimeter
G1 X103.242 Y81.317 E1.40324 ; perimeter
G1 X103.148 Y82.033 E1.42446 ; perimeter
G1 X102.872 Y82.699 E1.44569 ; perimeter
G1 X102.432 Y83.272 E1.46691 ; perimeter
G1 X101.860 Y83.711 E1.48813 ; perimeter
G1 X101.265 Y83.958 E1.50707 ; perimeter
G1 X101.193 Y83.988 E1.50936 ; perimeter
G1 X101.037 Y84.483 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50936 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X81.769 Y81.869 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X81.549 Y82.432 F1440.000 E1.01775 ; perimeter
G1 X81.192 Y82.918 E1.03551 ; perimeter
G1 X80.720 Y83.296 E1.05326 ; perimeter
G1 X80.167 Y83.538 E1.07102 ; perimeter
G1 X79.571 Y83.629 E1.08877 ; perimeter
G1 X78.970 Y83.563 E1.10653 ; perimeter
G1 X78.408 Y83.344 E1.12428 ; perimeter
G1 X77.921 Y82.986 E1.14204 ; perimeter
G1 X77.544 Y82.515 E1.15979 ; perimeter
G1 X77.301 Y81.962 E1.17754 ; perimeter
G1 X77.210 Y81.365 E1.19530 ; perimeter
G1 X77.276 Y80.765 E1.21305 ; perimeter
G1 X77.496 Y80.202 E1.23081 ; perimeter
G1 X77.647 Y79.997 E1.23829 ; perimeter
G1 X77.853 Y79.716 E1.24856 ; perimeter
G1 X78.325 Y79.338 E1.26632 ; perimeter
G1 X78.878 Y79.096 E1.28407 ; perimeter
G1 X79.474 Y79.005 E1.30183 ; perimeter
G1 X80.075 Y79.071 E1.31958 ; perimeter
G1 X80.637 Y79.290 E1.33733 ; perimeter
G1 X80.918 Y79.497 E1.34760 ; perimeter
G1 X81.124 Y79.648 E1.35509 ; perimeter
G1 X81.501 Y80.119 E1.37284 ; perimeter
G1 X81.744 Y80.672 E1.39060 ; perimeter
G1 X81.835 Y81.269 E1.40835 ; perimeter
G1 X81.777 Y81.792 E1.42382 ; perimeter
G1 X81.769 Y81.869 E1.42611 ; perimeter
G1 X81.260 Y81.744 F7800.000 ; move to first perimeter point
G1 X81.090 Y82.179 F1440.000 E1.43984 ; perimeter
G1 X80.813 Y82.555 E1.45357 ; perimeter
G1 X80.449 Y82.847 E1.46730 ; perimeter
G1 X80.021 Y83.035 E1.48103 ; perimeter
G1 X79.560 Y83.105 E1.49476 ; perimeter
G1 X79.096 Y83.054 E1.50849 ; perimeter
G1 X78.661 Y82.884 E1.52223 ; perimeter
G1 X78.434 Y82.718 E1.53048 ; perimeter
G1 X78.284 Y82.608 E1.53596 ; perimeter
G1 X77.992 Y82.243 E1.54969 ; perimeter
G1 X77.805 Y81.816 E1.56342 ; perimeter
G1 X77.734 Y81.354 E1.57715 ; perimeter
G1 X77.785 Y80.890 E1.59088 ; perimeter
G1 X77.955 Y80.455 E1.60461 ; perimeter
G1 X78.065 Y80.305 E1.61009 ; perimeter
G1 X78.232 Y80.079 E1.61834 ; perimeter
G1 X78.596 Y79.787 E1.63207 ; perimeter
G1 X79.024 Y79.599 E1.64581 ; perimeter
G1 X79.485 Y79.529 E1.65954 ; perimeter
G1 X79.949 Y79.580 E1.67327 ; perimeter
G1 X80.384 Y79.750 E1.68700 ; perimeter
G1 X80.611 Y79.916 E1.69526 ; perimeter
G1 X80.761 Y80.026 E1.70073 ; perimeter
G1 X81.053 Y80.391 E1.71446 ; perimeter
G1 X81.240 Y80.818 E1.72819 ; perimeter
G1 X81.311 Y81.280 E1.74192 ; perimeter
G1 X81.268 Y81.666 E1.75336 ; perimeter
G1 X81.260 Y81.744 E1.75565 ; perimeter
G1 X81.619 Y82.120 F7800.000 ; move inwards before travel
G1 F1800.000 E0.75565 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.238 Y86.012 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X80.905 Y86.289 F1440.000 E1.02122 ; perimeter
G1 X81.477 Y86.728 E1.04245 ; perimeter
G1 X81.917 Y87.301 E1.06367 ; perimeter
G1 X82.193 Y87.967 E1.08489 ; perimeter
G1 X82.287 Y88.683 E1.10612 ; perimeter
G1 X82.250 Y88.964 E1.11444 ; perimeter
G1 X82.193 Y89.399 E1.12734 ; perimeter
G1 X81.917 Y90.065 E1.14856 ; perimeter
G1 X81.477 Y90.638 E1.16979 ; perimeter
G1 X80.905 Y91.077 E1.19101 ; perimeter
G1 X80.238 Y91.354 E1.21223 ; perimeter
G1 X79.522 Y91.448 E1.23346 ; perimeter
G1 X78.807 Y91.354 E1.25468 ; perimeter
G1 X78.140 Y91.077 E1.27590 ; perimeter
G1 X77.568 Y90.638 E1.29713 ; perimeter
G1 X77.128 Y90.065 E1.31835 ; perimeter
G1 X76.852 Y89.399 E1.33957 ; perimeter
G1 X76.758 Y88.683 E1.36080 ; perimeter
G1 X76.852 Y87.967 E1.38202 ; perimeter
G1 X77.128 Y87.301 E1.40324 ; perimeter
G1 X77.568 Y86.728 E1.42447 ; perimeter
G1 X78.140 Y86.289 E1.44569 ; perimeter
G1 X78.807 Y86.012 E1.46691 ; perimeter
G1 X79.522 Y85.918 E1.48813 ; perimeter
G1 X80.161 Y86.002 E1.50707 ; perimeter
G1 X80.238 Y86.012 E1.50936 ; perimeter
G1 X80.621 Y85.661 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50936 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X102.986 Y91.191 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.827 Y91.191 F1440.000 E1.03406 ; perimeter
G1 X102.479 Y90.694 E1.05816 ; perimeter
G1 X102.986 Y90.036 E1.08258 ; perimeter
G1 X102.986 Y91.113 E1.11424 ; perimeter
G1 X102.986 Y91.191 E1.11653 ; perimeter
G1 F1800.000 E0.11653 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.859 Y78.809 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.637 Y78.809 F1800.000 E1.49336 ; perimeter
G1 X97.175 Y79.410 E1.51566 ; perimeter
G1 X96.794 Y80.330 E1.54493 ; perimeter
G1 X96.664 Y81.317 E1.57420 ; perimeter
G1 X96.794 Y82.304 E1.60347 ; perimeter
G1 X97.175 Y83.223 E1.63274 ; perimeter
G1 X97.781 Y84.013 E1.66201 ; perimeter
G1 X98.571 Y84.619 E1.69128 ; perimeter
G1 X99.491 Y85.000 E1.72055 ; perimeter
G1 X100.477 Y85.130 E1.74982 ; perimeter
G1 X101.464 Y85.000 E1.77909 ; perimeter
G1 X102.384 Y84.619 E1.80836 ; perimeter
G1 X102.986 Y84.157 E1.83066 ; perimeter
G1 X102.986 Y87.333 E1.92405 ; perimeter
G1 X102.488 Y86.682 E1.94815 ; perimeter
G1 X101.902 Y86.230 E1.96992 ; perimeter
G1 X101.218 Y85.944 E1.99170 ; perimeter
G1 X100.484 Y85.846 E2.01348 ; perimeter
G1 X99.750 Y85.941 E2.03526 ; perimeter
G1 X99.065 Y86.223 E2.05703 ; perimeter
G1 X98.476 Y86.672 E2.07881 ; perimeter
G1 X98.024 Y87.259 E2.10059 ; perimeter
G1 X97.739 Y87.942 E2.12237 ; perimeter
G1 X97.641 Y88.676 E2.14414 ; perimeter
G1 X97.735 Y89.411 E2.16592 ; perimeter
G1 X98.017 Y90.096 E2.18770 ; perimeter
G1 X98.467 Y90.684 E2.20948 ; perimeter
G1 X99.124 Y91.191 E2.23389 ; perimeter
G1 X82.363 Y91.191 E2.72676 ; perimeter
G1 X82.825 Y90.589 E2.74906 ; perimeter
G1 X83.206 Y89.670 E2.77833 ; perimeter
G1 X83.336 Y88.683 E2.80760 ; perimeter
G1 X83.206 Y87.696 E2.83687 ; perimeter
G1 X82.825 Y86.776 E2.86614 ; perimeter
G1 X82.219 Y85.987 E2.89541 ; perimeter
G1 X81.429 Y85.381 E2.92468 ; perimeter
G1 X80.509 Y85.000 E2.95395 ; perimeter
G1 X79.522 Y84.870 E2.98322 ; perimeter
G1 X78.536 Y85.000 E3.01249 ; perimeter
G1 X77.616 Y85.381 E3.04176 ; perimeter
G1 X77.014 Y85.843 E3.06406 ; perimeter
G1 X77.014 Y82.685 E3.15692 ; perimeter
G1 X77.559 Y83.364 E3.18252 ; perimeter
G1 X78.155 Y83.803 E3.20430 ; perimeter
G1 X78.845 Y84.072 E3.22608 ; perimeter
G1 X79.581 Y84.153 E3.24786 ; perimeter
G1 X80.314 Y84.041 E3.26964 ; perimeter
G1 X80.992 Y83.744 E3.29141 ; perimeter
G1 X81.570 Y83.281 E3.31319 ; perimeter
G1 X82.008 Y82.684 E3.33497 ; perimeter
G1 X82.278 Y81.994 E3.35675 ; perimeter
G1 X82.323 Y81.579 E3.36903 ; perimeter
G1 X82.359 Y81.258 E3.37852 ; perimeter
G1 X82.247 Y80.526 E3.40030 ; perimeter
G1 X81.949 Y79.848 E3.42208 ; perimeter
G1 X81.486 Y79.270 E3.44386 ; perimeter
G1 X80.922 Y78.855 E3.46445 ; perimeter
G1 X80.859 Y78.809 E3.46674 ; perimeter
G1 F1800.000 E2.46674 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X78.155 Y78.809 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.475 Y79.353 F1440.000 E1.02560 ; perimeter
G1 X77.014 Y79.980 E1.04849 ; perimeter
G1 X77.014 Y78.809 E1.08294 ; perimeter
G1 X78.077 Y78.809 E1.11419 ; perimeter
G1 X78.155 Y78.809 E1.11648 ; perimeter
G1 X76.495 Y78.289 F7800.000 ; move to first perimeter point
G1 X99.067 Y78.289 F1800.000 E1.78023 ; perimeter
G1 X98.152 Y78.991 E1.81415 ; perimeter
G1 X97.629 Y79.673 E1.83940 ; perimeter
G1 X97.301 Y80.466 E1.86464 ; perimeter
G1 X97.189 Y81.317 E1.88989 ; perimeter
G1 X97.301 Y82.168 E1.91514 ; perimeter
G1 X97.629 Y82.961 E1.94038 ; perimeter
G1 X98.152 Y83.643 E1.96563 ; perimeter
G1 X98.833 Y84.165 E1.99088 ; perimeter
G1 X99.626 Y84.494 E2.01612 ; perimeter
G1 X100.477 Y84.606 E2.04137 ; perimeter
G1 X101.329 Y84.494 E2.06662 ; perimeter
G1 X102.122 Y84.165 E2.09186 ; perimeter
G1 X102.803 Y83.643 E2.11711 ; perimeter
G1 X103.505 Y82.727 E2.15103 ; perimeter
G1 X103.505 Y91.711 E2.41519 ; perimeter
G1 X80.933 Y91.711 E3.07895 ; perimeter
G1 X81.848 Y91.009 E3.11287 ; perimeter
G1 X82.371 Y90.327 E3.13811 ; perimeter
G1 X82.699 Y89.534 E3.16336 ; perimeter
G1 X82.765 Y89.032 E3.17827 ; perimeter
G1 X82.811 Y88.683 E3.18861 ; perimeter
G1 X82.699 Y87.832 E3.21385 ; perimeter
G1 X82.371 Y87.039 E3.23910 ; perimeter
G1 X81.848 Y86.357 E3.26435 ; perimeter
G1 X81.167 Y85.835 E3.28959 ; perimeter
G1 X80.374 Y85.506 E3.31484 ; perimeter
G1 X79.522 Y85.394 E3.34009 ; perimeter
G1 X78.671 Y85.506 E3.36533 ; perimeter
G1 X77.878 Y85.835 E3.39058 ; perimeter
G1 X77.197 Y86.357 E3.41583 ; perimeter
G1 X76.495 Y87.273 E3.44975 ; perimeter
G1 X76.495 Y78.367 E3.71162 ; perimeter
G1 X76.495 Y78.289 E3.71391 ; perimeter
G1 F1800.000 E2.71391 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.495 Y90.093 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.197 Y91.009 F1440.000 E1.03392 ; perimeter
G1 X78.112 Y91.711 E1.06784 ; perimeter
G1 X76.495 Y91.711 E1.11541 ; perimeter
G1 X76.495 Y90.171 E1.16068 ; perimeter
G1 X76.495 Y90.093 E1.16297 ; perimeter
G1 F1800.000 E0.16297 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.888 Y78.289 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.505 Y78.289 F1440.000 E1.04756 ; perimeter
G1 X103.505 Y79.907 E1.09513 ; perimeter
G1 X102.803 Y78.991 E1.12905 ; perimeter
G1 X101.950 Y78.337 E1.16068 ; perimeter
G1 X101.888 Y78.289 E1.16297 ; perimeter
G1 F1800.000 E0.16297 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X104.025 Y77.770 F7800.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.025 Y92.230 F1800.000 E1.42523 ; perimeter
G1 X75.975 Y92.230 E2.25005 ; perimeter
G1 X75.975 Y77.770 E2.67528 ; perimeter
G1 X103.947 Y77.770 E3.49781 ; perimeter
G1 X104.025 Y77.770 E3.50010 ; perimeter
G1 X103.765 Y78.220 F7800.000 ; move inwards before travel
G1 F1800.000 E2.50010 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X98.910 Y85.822 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.429 Y85.303 F3600.000 E1.02197 ; fill
G1 X98.900 Y85.084 E1.03913 ; fill
G1 X93.147 Y90.837 E1.28283 ; fill
G1 X92.398 Y90.837 E1.30525 ; fill
G1 X98.391 Y84.844 E1.55911 ; fill
G1 X97.968 Y84.519 E1.57511 ; fill
G1 X91.649 Y90.837 E1.84273 ; fill
G1 X90.901 Y90.837 E1.86515 ; fill
G1 X97.552 Y84.186 E2.14687 ; fill
G1 X97.227 Y83.763 E2.16286 ; fill
G1 X90.152 Y90.837 E2.46251 ; fill
G1 X89.404 Y90.837 E2.48493 ; fill
G1 X96.902 Y83.339 E2.80252 ; fill
G1 X96.678 Y82.815 E2.81961 ; fill
G1 X88.655 Y90.837 E3.15942 ; fill
G1 X87.907 Y90.837 E3.18184 ; fill
G1 X96.458 Y82.286 E3.54406 ; fill
G1 X96.368 Y81.627 E3.56398 ; fill
G1 X87.158 Y90.837 E3.95410 ; fill
G1 X86.410 Y90.837 E3.97652 ; fill
G1 X96.338 Y80.909 E4.39706 ; fill
G1 X96.451 Y80.047 E4.42310 ; fill
G1 X85.661 Y90.837 E4.88015 ; fill
G1 X84.913 Y90.837 E4.90257 ; fill
G1 X96.587 Y79.163 E5.39707 ; fill
G1 X95.838 Y79.163 E5.41949 ; fill
G1 X84.164 Y90.837 E5.91399 ; fill
G1 X83.416 Y90.837 E5.93641 ; fill
G1 X95.090 Y79.163 E6.43091 ; fill
G1 X94.341 Y79.163 E6.45333 ; fill
G1 X83.548 Y89.956 E6.91050 ; fill
G1 X83.662 Y89.094 E6.93654 ; fill
G1 X93.593 Y79.163 E7.35719 ; fill
G1 X92.844 Y79.163 E7.37961 ; fill
G1 X83.632 Y88.375 E7.76983 ; fill
G1 X83.542 Y87.716 E7.78975 ; fill
G1 X92.096 Y79.163 E8.15205 ; fill
G1 X91.347 Y79.163 E8.17447 ; fill
G1 X83.323 Y87.187 E8.51435 ; fill
G1 X83.099 Y86.662 E8.53144 ; fill
G1 X90.598 Y79.163 E8.84909 ; fill
G1 X89.850 Y79.163 E8.87151 ; fill
G1 X82.774 Y86.238 E9.17122 ; fill
G1 X82.449 Y85.815 E9.18721 ; fill
G1 X89.101 Y79.163 E9.46897 ; fill
G1 X88.353 Y79.163 E9.49139 ; fill
G1 X82.034 Y85.482 E9.75907 ; fill
G1 X81.610 Y85.157 E9.77506 ; fill
G1 X87.604 Y79.163 E10.02896 ; fill
G1 X86.856 Y79.163 E10.05138 ; fill
G1 X81.102 Y84.917 E10.29511 ; fill
G1 X80.573 Y84.698 E10.31227 ; fill
G1 X81.099 Y84.171 E10.33456 ; fill
G1 X82.388 Y82.882 F7800.000 ; move to first fill point
G1 X86.107 Y79.163 F3600.000 E10.49211 ; fill
G1 X85.359 Y79.163 E10.51453 ; fill
G1 X82.669 Y81.853 E10.62847 ; fill
G1 X82.670 Y81.103 E10.65093 ; fill
G1 X84.610 Y79.163 E10.73311 ; fill
G1 X83.862 Y79.163 E10.75553 ; fill
G1 X82.553 Y80.472 E10.81098 ; fill
G1 X82.324 Y79.952 E10.82799 ; fill
G1 X83.113 Y79.163 E10.86140 ; fill
G1 X82.365 Y79.163 E10.88382 ; fill
G1 X82.034 Y79.494 E10.89784 ; fill
G1 F1800.000 E9.89784 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X97.969 Y90.506 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.638 Y90.837 F3600.000 E1.01402 ; fill
G1 X96.889 Y90.837 E1.03644 ; fill
G1 X97.672 Y90.054 E1.06959 ; fill
G1 X97.454 Y89.524 E1.08677 ; fill
G1 X96.141 Y90.837 E1.14238 ; fill
G1 X95.392 Y90.837 E1.16480 ; fill
G1 X97.332 Y88.897 E1.24697 ; fill
G1 X97.330 Y88.151 E1.26933 ; fill
G1 X94.644 Y90.837 E1.38312 ; fill
G1 X93.895 Y90.837 E1.40554 ; fill
G1 X97.618 Y87.115 E1.56322 ; fill
G1 F1800.000 E0.56322 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X100.045 Y91.220 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.845 Y91.420 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.212 Y89.132 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.012 Y89.332 F1200.000 E1.00502 ; fill
G1 F1800.000 E0.00502 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X102.632 Y85.799 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.301 Y86.130 F3600.000 E1.02582 ; fill
G1 X101.703 Y85.349 E1.08007 ; fill
G1 X101.372 Y85.680 E1.10587 ; fill
G1 X102.563 Y85.505 F7800.000 ; move to first fill point
G1 X102.101 Y85.967 F1200.000 E1.13271 ; fill
G1 F1800.000 E0.13271 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.642 Y81.937 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.442 Y82.137 F1200.000 E1.00687 ; fill
G1 X103.534 Y81.438 E1.02401 ; fill
G1 X103.734 Y81.238 E1.03087 ; fill
G1 X103.734 Y81.196 F7800.000 ; move to first fill point
G1 X103.534 Y81.396 F1200.000 E1.03981 ; fill
G1 X103.442 Y80.696 E1.06215 ; fill
G1 X103.642 Y80.497 E1.07109 ; fill
G1 F1800.000 E0.07109 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.298 Y78.153 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.098 Y78.352 F1200.000 E1.00894 ; fill
G1 X100.598 Y78.061 E1.02726 ; fill
G1 X100.399 Y78.260 E1.03620 ; fill
G1 X100.556 Y78.061 F7800.000 ; move to first fill point
G1 X100.357 Y78.260 F1200.000 E1.04306 ; fill
G1 X99.857 Y78.152 E1.05547 ; fill
G1 X99.657 Y78.352 E1.06234 ; fill
G1 F1800.000 E0.06234 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X79.108 Y78.580 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X78.909 Y78.780 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.998 Y81.815 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.799 Y82.014 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X78.319 Y84.247 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.857 Y84.709 F1200.000 E1.02684 ; fill
G1 X78.637 Y84.319 F7800.000 ; move to first fill point
G1 X78.307 Y84.650 F3600.000 E1.05143 ; fill
G1 X77.699 Y83.943 E1.10040 ; fill
G1 X77.368 Y84.274 E1.12502 ; fill
G1 F1800.000 E0.12502 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.466 Y88.562 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.266 Y88.762 F1200.000 E1.00686 ; fill
G1 X76.358 Y88.063 E1.02399 ; fill
G1 X76.558 Y87.863 E1.03086 ; fill
G1 X76.558 Y89.304 F7800.000 ; move to first fill point
G1 X76.358 Y89.503 F1200.000 E1.03980 ; fill
G1 X76.266 Y88.804 E1.06213 ; fill
G1 X76.466 Y88.604 E1.07107 ; fill
G1 F1800.000 E0.07107 ; retract
G1 Z1.800 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X79.601 Y91.740 F7800.000 ; move to first fill point
G1 Z0.800 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X79.402 Y91.939 F1200.000 E1.00894 ; fill
G1 X78.902 Y91.648 E1.02726 ; fill
G1 X78.702 Y91.847 E1.03620 ; fill
G1 X80.343 Y91.648 F7800.000 ; move to first fill point
G1 X80.143 Y91.848 F1200.000 E1.04307 ; fill
G1 X79.643 Y91.740 E1.05549 ; fill
G1 X79.444 Y91.939 E1.06234 ; fill
G1 F1800.000 E0.06234 ; retract
G1 Z2.200 ; move to next layer (2) and lift
G92 E0 ; reset extrusion distance
G1 X98.242 Y89.276 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X98.165 Y88.677 F1440.000 E1.01775 ; perimeter
G1 X98.245 Y88.079 E1.03551 ; perimeter
G1 X98.477 Y87.522 E1.05326 ; perimeter
G1 X98.846 Y87.044 E1.07102 ; perimeter
G1 X99.326 Y86.677 E1.08877 ; perimeter
G1 X99.884 Y86.447 E1.10653 ; perimeter
G1 X100.483 Y86.370 E1.12428 ; perimeter
G1 X101.082 Y86.450 E1.14204 ; perimeter
G1 X101.639 Y86.683 E1.15979 ; perimeter
G1 X101.835 Y86.834 E1.16709 ; perimeter
G1 X102.117 Y87.051 E1.17754 ; perimeter
G1 X102.483 Y87.531 E1.19530 ; perimeter
G1 X102.713 Y88.090 E1.21305 ; perimeter
G1 X102.790 Y88.689 E1.23081 ; perimeter
G1 X102.710 Y89.287 E1.24856 ; perimeter
G1 X102.478 Y89.844 E1.26632 ; perimeter
G1 X102.261 Y90.126 E1.27677 ; perimeter
G1 X102.109 Y90.322 E1.28407 ; perimeter
G1 X101.629 Y90.689 E1.30183 ; perimeter
G1 X101.071 Y90.919 E1.31958 ; perimeter
G1 X100.472 Y90.996 E1.33733 ; perimeter
G1 X99.873 Y90.916 E1.35509 ; perimeter
G1 X99.316 Y90.683 E1.37284 ; perimeter
G1 X98.838 Y90.315 E1.39060 ; perimeter
G1 X98.472 Y89.835 E1.40835 ; perimeter
G1 X98.272 Y89.348 E1.42382 ; perimeter
G1 X98.242 Y89.276 E1.42611 ; perimeter
G1 X98.749 Y89.142 F7800.000 ; move to first perimeter point
G1 X98.689 Y88.679 F1440.000 E1.43984 ; perimeter
G1 X98.751 Y88.216 E1.45357 ; perimeter
G1 X98.931 Y87.785 E1.46730 ; perimeter
G1 X99.216 Y87.415 E1.48103 ; perimeter
G1 X99.587 Y87.132 E1.49476 ; perimeter
G1 X100.019 Y86.954 E1.50849 ; perimeter
G1 X100.482 Y86.894 E1.52223 ; perimeter
G1 X100.945 Y86.956 E1.53596 ; perimeter
G1 X101.376 Y87.136 E1.54969 ; perimeter
G1 X101.518 Y87.246 E1.55497 ; perimeter
G1 X101.745 Y87.421 E1.56342 ; perimeter
G1 X102.029 Y87.792 E1.57715 ; perimeter
G1 X102.206 Y88.224 E1.59088 ; perimeter
G1 X102.266 Y88.687 E1.60461 ; perimeter
G1 X102.204 Y89.150 E1.61834 ; perimeter
G1 X102.024 Y89.581 E1.63207 ; perimeter
G1 X101.849 Y89.809 E1.64052 ; perimeter
G1 X101.739 Y89.951 E1.64581 ; perimeter
G1 X101.368 Y90.234 E1.65954 ; perimeter
G1 X100.936 Y90.412 E1.67327 ; perimeter
G1 X100.473 Y90.472 E1.68700 ; perimeter
G1 X100.010 Y90.410 E1.70073 ; perimeter
G1 X99.579 Y90.230 E1.71446 ; perimeter
G1 X99.210 Y89.945 E1.72819 ; perimeter
G1 X98.926 Y89.574 E1.74192 ; perimeter
G1 X98.778 Y89.214 E1.75336 ; perimeter
G1 X98.749 Y89.142 E1.75565 ; perimeter
G1 X98.253 Y88.984 F7800.000 ; move inwards before travel
G1 F1800.000 E0.75565 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X99.762 Y83.988 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.095 Y83.711 F1440.000 E1.02122 ; perimeter
G1 X98.879 Y83.545 E1.02924 ; perimeter
G1 X98.523 Y83.272 E1.04245 ; perimeter
G1 X98.083 Y82.699 E1.06367 ; perimeter
G1 X97.807 Y82.033 E1.08489 ; perimeter
G1 X97.713 Y81.317 E1.10612 ; perimeter
G1 X97.807 Y80.601 E1.12734 ; perimeter
G1 X98.083 Y79.935 E1.14856 ; perimeter
G1 X98.356 Y79.578 E1.16177 ; perimeter
G1 X98.523 Y79.362 E1.16979 ; perimeter
G1 X99.095 Y78.923 E1.19101 ; perimeter
G1 X99.762 Y78.646 E1.21223 ; perimeter
G1 X100.478 Y78.552 E1.23346 ; perimeter
G1 X101.193 Y78.646 E1.25468 ; perimeter
G1 X101.860 Y78.923 E1.27590 ; perimeter
G1 X102.076 Y79.089 E1.28392 ; perimeter
G1 X102.432 Y79.362 E1.29713 ; perimeter
G1 X102.872 Y79.935 E1.31835 ; perimeter
G1 X103.148 Y80.601 E1.33957 ; perimeter
G1 X103.242 Y81.317 E1.36080 ; perimeter
G1 X103.148 Y82.033 E1.38202 ; perimeter
G1 X102.872 Y82.699 E1.40324 ; perimeter
G1 X102.432 Y83.272 E1.42446 ; perimeter
G1 X101.860 Y83.711 E1.44569 ; perimeter
G1 X101.193 Y83.988 E1.46691 ; perimeter
G1 X100.477 Y84.082 E1.48813 ; perimeter
G1 X99.839 Y83.998 E1.50707 ; perimeter
G1 X99.762 Y83.988 E1.50936 ; perimeter
G1 X99.379 Y84.339 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50936 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X81.769 Y81.869 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X81.549 Y82.432 F1440.000 E1.01775 ; perimeter
G1 X81.192 Y82.918 E1.03551 ; perimeter
G1 X80.720 Y83.296 E1.05326 ; perimeter
G1 X80.167 Y83.538 E1.07102 ; perimeter
G1 X79.571 Y83.629 E1.08877 ; perimeter
G1 X78.971 Y83.563 E1.10652 ; perimeter
G1 X78.408 Y83.344 E1.12428 ; perimeter
G1 X77.921 Y82.986 E1.14204 ; perimeter
G1 X77.544 Y82.515 E1.15979 ; perimeter
G1 X77.301 Y81.962 E1.17754 ; perimeter
G1 X77.210 Y81.365 E1.19530 ; perimeter
G1 X77.249 Y81.012 E1.20576 ; perimeter
G1 X77.276 Y80.765 E1.21305 ; perimeter
G1 X77.496 Y80.202 E1.23081 ; perimeter
G1 X77.853 Y79.716 E1.24856 ; perimeter
G1 X78.325 Y79.338 E1.26632 ; perimeter
G1 X78.878 Y79.096 E1.28407 ; perimeter
G1 X79.474 Y79.005 E1.30183 ; perimeter
G1 X80.075 Y79.071 E1.31958 ; perimeter
G1 X80.637 Y79.290 E1.33733 ; perimeter
G1 X81.124 Y79.648 E1.35509 ; perimeter
G1 X81.501 Y80.119 E1.37284 ; perimeter
G1 X81.744 Y80.672 E1.39060 ; perimeter
G1 X81.835 Y81.269 E1.40835 ; perimeter
G1 X81.777 Y81.792 E1.42382 ; perimeter
G1 X81.769 Y81.869 E1.42611 ; perimeter
G1 X81.260 Y81.744 F7800.000 ; move to first perimeter point
G1 X81.090 Y82.179 F1440.000 E1.43984 ; perimeter
G1 X80.813 Y82.555 E1.45357 ; perimeter
G1 X80.449 Y82.847 E1.46730 ; perimeter
G1 X80.021 Y83.035 E1.48103 ; perimeter
G1 X79.560 Y83.105 E1.49476 ; perimeter
G1 X79.096 Y83.054 E1.50849 ; perimeter
G1 X78.661 Y82.884 E1.52223 ; perimeter
G1 X78.516 Y82.778 E1.52751 ; perimeter
G1 X78.284 Y82.608 E1.53596 ; perimeter
G1 X77.992 Y82.243 E1.54969 ; perimeter
G1 X77.805 Y81.816 E1.56342 ; perimeter
G1 X77.734 Y81.354 E1.57715 ; perimeter
G1 X77.766 Y81.069 E1.58559 ; perimeter
G1 X77.785 Y80.890 E1.59088 ; perimeter
G1 X77.955 Y80.455 E1.60461 ; perimeter
G1 X78.232 Y80.079 E1.61834 ; perimeter
G1 X78.596 Y79.787 E1.63207 ; perimeter
G1 X79.024 Y79.599 E1.64581 ; perimeter
G1 X79.485 Y79.529 E1.65954 ; perimeter
G1 X79.949 Y79.580 E1.67327 ; perimeter
G1 X80.384 Y79.750 E1.68700 ; perimeter
G1 X80.761 Y80.026 E1.70073 ; perimeter
G1 X81.053 Y80.391 E1.71446 ; perimeter
G1 X81.240 Y80.818 E1.72819 ; perimeter
G1 X81.311 Y81.280 E1.74192 ; perimeter
G1 X81.268 Y81.666 E1.75336 ; perimeter
G1 X81.260 Y81.744 E1.75565 ; perimeter
G1 X81.619 Y82.120 F7800.000 ; move inwards before travel
G1 F1800.000 E0.75565 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.238 Y86.012 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X80.905 Y86.289 F1440.000 E1.02122 ; perimeter
G1 X81.121 Y86.455 E1.02924 ; perimeter
G1 X81.477 Y86.728 E1.04245 ; perimeter
G1 X81.917 Y87.301 E1.06367 ; perimeter
G1 X82.193 Y87.967 E1.08489 ; perimeter
G1 X82.252 Y88.413 E1.09810 ; perimeter
G1 X82.287 Y88.683 E1.10612 ; perimeter
G1 X82.193 Y89.399 E1.12734 ; perimeter
G1 X81.917 Y90.065 E1.14856 ; perimeter
G1 X81.644 Y90.422 E1.16177 ; perimeter
G1 X81.477 Y90.638 E1.16979 ; perimeter
G1 X80.905 Y91.077 E1.19101 ; perimeter
G1 X80.238 Y91.354 E1.21223 ; perimeter
G1 X79.522 Y91.448 E1.23346 ; perimeter
G1 X78.807 Y91.354 E1.25468 ; perimeter
G1 X78.555 Y91.249 E1.26270 ; perimeter
G1 X78.140 Y91.077 E1.27590 ; perimeter
G1 X77.568 Y90.638 E1.29713 ; perimeter
G1 X77.128 Y90.065 E1.31835 ; perimeter
G1 X76.852 Y89.399 E1.33957 ; perimeter
G1 X76.758 Y88.683 E1.36080 ; perimeter
G1 X76.852 Y87.967 E1.38202 ; perimeter
G1 X77.128 Y87.301 E1.40324 ; perimeter
G1 X77.568 Y86.728 E1.42447 ; perimeter
G1 X78.140 Y86.289 E1.44569 ; perimeter
G1 X78.807 Y86.012 E1.46691 ; perimeter
G1 X79.522 Y85.918 E1.48813 ; perimeter
G1 X80.161 Y86.002 E1.50707 ; perimeter
G1 X80.238 Y86.012 E1.50936 ; perimeter
G1 X80.621 Y85.661 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50936 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.827 Y91.191 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.479 Y90.694 F1440.000 E1.02410 ; perimeter
G1 X102.986 Y90.036 E1.04851 ; perimeter
G1 X102.986 Y91.191 E1.08247 ; perimeter
G1 X101.905 Y91.191 E1.11424 ; perimeter
G1 X101.827 Y91.191 E1.11653 ; perimeter
G1 F1800.000 E0.11653 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.859 Y78.809 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.637 Y78.809 F1800.000 E1.49336 ; perimeter
G1 X97.175 Y79.410 E1.51566 ; perimeter
G1 X96.794 Y80.330 E1.54493 ; perimeter
G1 X96.664 Y81.317 E1.57420 ; perimeter
G1 X96.794 Y82.304 E1.60347 ; perimeter
G1 X96.951 Y82.682 E1.61552 ; perimeter
G1 X97.175 Y83.224 E1.63274 ; perimeter
G1 X97.781 Y84.013 E1.66201 ; perimeter
G1 X98.571 Y84.619 E1.69128 ; perimeter
G1 X99.491 Y85.000 E1.72055 ; perimeter
G1 X100.477 Y85.130 E1.74982 ; perimeter
G1 X101.464 Y85.000 E1.77909 ; perimeter
G1 X102.384 Y84.619 E1.80836 ; perimeter
G1 X102.986 Y84.157 E1.83066 ; perimeter
G1 X102.986 Y87.333 E1.92405 ; perimeter
G1 X102.488 Y86.682 E1.94815 ; perimeter
G1 X101.902 Y86.230 E1.96992 ; perimeter
G1 X101.218 Y85.944 E1.99170 ; perimeter
G1 X100.484 Y85.846 E2.01348 ; perimeter
G1 X99.750 Y85.941 E2.03526 ; perimeter
G1 X99.065 Y86.223 E2.05703 ; perimeter
G1 X98.476 Y86.672 E2.07881 ; perimeter
G1 X98.024 Y87.259 E2.10059 ; perimeter
G1 X97.739 Y87.942 E2.12237 ; perimeter
G1 X97.641 Y88.676 E2.14415 ; perimeter
G1 X97.735 Y89.411 E2.16592 ; perimeter
G1 X98.017 Y90.096 E2.18770 ; perimeter
G1 X98.467 Y90.684 E2.20948 ; perimeter
G1 X99.124 Y91.191 E2.23389 ; perimeter
G1 X82.363 Y91.191 E2.72676 ; perimeter
G1 X82.825 Y90.589 E2.74906 ; perimeter
G1 X83.206 Y89.670 E2.77833 ; perimeter
G1 X83.336 Y88.683 E2.80760 ; perimeter
G1 X83.206 Y87.696 E2.83687 ; perimeter
G1 X82.825 Y86.776 E2.86614 ; perimeter
G1 X82.219 Y85.987 E2.89541 ; perimeter
G1 X81.429 Y85.381 E2.92468 ; perimeter
G1 X80.888 Y85.157 E2.94191 ; perimeter
G1 X80.509 Y85.000 E2.95395 ; perimeter
G1 X79.522 Y84.870 E2.98322 ; perimeter
G1 X78.536 Y85.000 E3.01249 ; perimeter
G1 X77.616 Y85.381 E3.04176 ; perimeter
G1 X77.014 Y85.843 E3.06406 ; perimeter
G1 X77.014 Y82.685 E3.15692 ; perimeter
G1 X77.559 Y83.364 E3.18252 ; perimeter
G1 X78.155 Y83.803 E3.20430 ; perimeter
G1 X78.845 Y84.072 E3.22608 ; perimeter
G1 X79.581 Y84.153 E3.24786 ; perimeter
G1 X80.314 Y84.041 E3.26964 ; perimeter
G1 X80.992 Y83.744 E3.29141 ; perimeter
G1 X81.570 Y83.281 E3.31319 ; perimeter
G1 X82.008 Y82.684 E3.33497 ; perimeter
G1 X82.278 Y81.994 E3.35675 ; perimeter
G1 X82.312 Y81.679 E3.36606 ; perimeter
G1 X82.359 Y81.258 E3.37852 ; perimeter
G1 X82.247 Y80.526 E3.40030 ; perimeter
G1 X81.949 Y79.848 E3.42208 ; perimeter
G1 X81.486 Y79.270 E3.44386 ; perimeter
G1 X80.922 Y78.855 E3.46445 ; perimeter
G1 X80.859 Y78.809 E3.46675 ; perimeter
G1 F1800.000 E2.46675 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X77.014 Y78.809 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X78.155 Y78.809 F1440.000 E1.03354 ; perimeter
G1 X77.475 Y79.353 E1.05914 ; perimeter
G1 X77.014 Y79.980 E1.08203 ; perimeter
G1 X77.014 Y78.887 E1.11419 ; perimeter
G1 X77.014 Y78.809 E1.11648 ; perimeter
G1 X76.495 Y78.289 F7800.000 ; move to first perimeter point
G1 X99.067 Y78.289 F1800.000 E1.78023 ; perimeter
G1 X98.152 Y78.991 E1.81415 ; perimeter
G1 X97.629 Y79.673 E1.83940 ; perimeter
G1 X97.301 Y80.466 E1.86464 ; perimeter
G1 X97.189 Y81.317 E1.88989 ; perimeter
G1 X97.301 Y82.168 E1.91514 ; perimeter
G1 X97.629 Y82.961 E1.94038 ; perimeter
G1 X98.152 Y83.643 E1.96563 ; perimeter
G1 X98.833 Y84.165 E1.99088 ; perimeter
G1 X99.626 Y84.494 E2.01612 ; perimeter
G1 X100.477 Y84.606 E2.04137 ; perimeter
G1 X101.329 Y84.494 E2.06662 ; perimeter
G1 X102.122 Y84.165 E2.09186 ; perimeter
G1 X102.803 Y83.643 E2.11711 ; perimeter
G1 X103.505 Y82.727 E2.15103 ; perimeter
G1 X103.505 Y91.711 E2.41519 ; perimeter
G1 X80.933 Y91.711 E3.07895 ; perimeter
G1 X81.848 Y91.009 E3.11287 ; perimeter
G1 X82.371 Y90.327 E3.13812 ; perimeter
G1 X82.699 Y89.534 E3.16336 ; perimeter
G1 X82.811 Y88.683 E3.18861 ; perimeter
G1 X82.699 Y87.832 E3.21385 ; perimeter
G1 X82.371 Y87.039 E3.23910 ; perimeter
G1 X81.848 Y86.357 E3.26435 ; perimeter
G1 X81.438 Y86.042 E3.27956 ; perimeter
G1 X81.167 Y85.835 E3.28959 ; perimeter
G1 X80.374 Y85.506 E3.31484 ; perimeter
G1 X79.522 Y85.394 E3.34009 ; perimeter
G1 X78.671 Y85.506 E3.36533 ; perimeter
G1 X77.878 Y85.835 E3.39058 ; perimeter
G1 X77.197 Y86.357 E3.41583 ; perimeter
G1 X76.495 Y87.273 E3.44975 ; perimeter
G1 X76.495 Y78.367 E3.71162 ; perimeter
G1 X76.495 Y78.289 E3.71391 ; perimeter
G1 F1800.000 E2.71391 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.495 Y90.093 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.197 Y91.009 F1440.000 E1.03392 ; perimeter
G1 X78.112 Y91.711 E1.06784 ; perimeter
G1 X76.495 Y91.711 E1.11541 ; perimeter
G1 X76.495 Y90.171 E1.16068 ; perimeter
G1 X76.495 Y90.093 E1.16297 ; perimeter
G1 F1800.000 E0.16297 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.888 Y78.289 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.505 Y78.289 F1440.000 E1.04756 ; perimeter
G1 X103.505 Y79.907 E1.09513 ; perimeter
G1 X102.803 Y78.991 E1.12905 ; perimeter
G1 X101.950 Y78.337 E1.16068 ; perimeter
G1 X101.888 Y78.289 E1.16297 ; perimeter
G1 F1800.000 E0.16297 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X104.025 Y77.770 F7800.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.025 Y92.230 F1800.000 E1.42523 ; perimeter
G1 X75.975 Y92.230 E2.25005 ; perimeter
G1 X75.975 Y77.770 E2.67528 ; perimeter
G1 X103.947 Y77.770 E3.49781 ; perimeter
G1 X104.025 Y77.770 E3.50010 ; perimeter
G1 X103.765 Y78.220 F7800.000 ; move inwards before travel
G1 F1800.000 E2.50010 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X96.640 Y83.054 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X92.749 Y79.163 F3600.000 E1.16439 ; fill
G1 X93.495 Y79.163 E1.18669 ; fill
G1 X96.380 Y82.048 E1.30858 ; fill
G1 X96.336 Y81.257 E1.33226 ; fill
G1 X94.242 Y79.163 E1.42072 ; fill
G1 X94.988 Y79.163 E1.44302 ; fill
G1 X96.422 Y80.597 E1.50361 ; fill
G1 X96.594 Y80.022 E1.52154 ; fill
G1 X95.735 Y79.163 E1.55782 ; fill
G1 X96.482 Y79.163 E1.58012 ; fill
G1 X96.812 Y79.494 E1.59410 ; fill
G1 F1800.000 E0.59410 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X98.434 Y86.342 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X91.255 Y79.163 F3600.000 E1.30330 ; fill
G1 X92.002 Y79.163 E1.32560 ; fill
G1 X98.858 Y86.019 E1.61524 ; fill
G1 X99.359 Y85.773 E1.63191 ; fill
G1 X98.740 Y85.155 E1.65804 ; fill
G1 F1800.000 E0.65804 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X83.519 Y90.837 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X83.188 Y90.506 F3600.000 E1.01398 ; fill
G1 X83.406 Y89.978 E1.03105 ; fill
G1 X84.265 Y90.837 E1.06733 ; fill
G1 X85.012 Y90.837 E1.08963 ; fill
G1 X83.578 Y89.403 E1.15022 ; fill
G1 X83.664 Y88.743 E1.17009 ; fill
G1 X85.758 Y90.837 E1.25855 ; fill
G1 X86.505 Y90.837 E1.28086 ; fill
G1 X83.620 Y87.952 E1.40275 ; fill
G1 X83.360 Y86.946 E1.43379 ; fill
G1 X87.251 Y90.837 E1.59818 ; fill
G1 X87.998 Y90.837 E1.62048 ; fill
G1 X81.148 Y83.987 E1.90989 ; fill
G1 X81.562 Y83.655 E1.92575 ; fill
G1 X88.745 Y90.837 E2.22919 ; fill
G1 X89.491 Y90.837 E2.25149 ; fill
G1 X81.931 Y83.277 E2.57090 ; fill
G1 X82.247 Y82.846 E2.58685 ; fill
G1 X90.238 Y90.837 E2.92444 ; fill
G1 X90.984 Y90.837 E2.94675 ; fill
G1 X82.475 Y82.328 E3.30624 ; fill
G1 X82.644 Y81.750 E3.32423 ; fill
G1 X91.731 Y90.837 E3.70815 ; fill
G1 X92.477 Y90.837 E3.73045 ; fill
G1 X82.717 Y81.076 E4.14283 ; fill
G1 X82.572 Y80.185 E4.16980 ; fill
G1 X93.224 Y90.837 E4.61984 ; fill
G1 X93.971 Y90.837 E4.64214 ; fill
G1 X82.297 Y79.163 E5.13535 ; fill
G1 X83.043 Y79.163 E5.15765 ; fill
G1 X94.717 Y90.837 E5.65086 ; fill
G1 X95.464 Y90.837 E5.67316 ; fill
G1 X83.790 Y79.163 E6.16636 ; fill
G1 X84.536 Y79.163 E6.18867 ; fill
G1 X96.210 Y90.837 E6.68187 ; fill
G1 X96.957 Y90.837 E6.70418 ; fill
G1 X85.283 Y79.163 E7.19738 ; fill
G1 X86.029 Y79.163 E7.21968 ; fill
G1 X97.703 Y90.837 E7.71289 ; fill
G1 X97.444 Y89.831 E7.74393 ; fill
G1 X86.776 Y79.163 E8.19463 ; fill
G1 X87.523 Y79.163 E8.21693 ; fill
G1 X97.294 Y88.934 E8.62975 ; fill
G1 X97.360 Y88.254 E8.65017 ; fill
G1 X88.269 Y79.163 E9.03426 ; fill
G1 X89.016 Y79.163 E9.05656 ; fill
G1 X97.524 Y87.671 E9.41600 ; fill
G1 X97.747 Y87.147 E9.43299 ; fill
G1 X89.762 Y79.163 E9.77031 ; fill
G1 X90.509 Y79.163 E9.79261 ; fill
G1 X98.072 Y86.726 E10.11212 ; fill
G1 F1800.000 E9.11212 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X81.260 Y84.845 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X80.641 Y84.227 F3600.000 E1.02611 ; fill
G1 F1800.000 E0.02611 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X79.643 Y91.939 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X79.444 Y91.740 F1200.000 E1.00894 ; fill
G1 X80.143 Y91.648 E1.03127 ; fill
G1 X80.343 Y91.847 E1.04021 ; fill
G1 X78.902 Y91.848 F7800.000 ; move to first fill point
G1 X78.702 Y91.648 F1200.000 E1.04708 ; fill
G1 X79.402 Y91.740 E1.06422 ; fill
G1 X79.601 Y91.939 E1.07108 ; fill
G1 F1800.000 E0.07108 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.558 Y89.503 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.358 Y89.303 F1200.000 E1.00687 ; fill
G1 X76.466 Y88.804 E1.01929 ; fill
G1 X76.266 Y88.604 E1.02614 ; fill
G1 X76.466 Y88.762 F7800.000 ; move to first fill point
G1 X76.266 Y88.562 F1200.000 E1.03508 ; fill
G1 X76.558 Y88.062 E1.05340 ; fill
G1 X76.358 Y87.863 E1.06234 ; fill
G1 F1800.000 E0.06234 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X77.699 Y85.018 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.368 Y84.687 F3600.000 E1.02446 ; fill
G1 X78.307 Y84.319 E1.07715 ; fill
G1 X78.637 Y84.649 E1.10161 ; fill
G1 X77.899 Y84.883 F7800.000 ; move to first fill point
G1 X77.437 Y84.421 F1200.000 E1.12845 ; fill
G1 F1800.000 E0.12845 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.998 Y82.014 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.798 Y81.814 F1200.000 E1.00502 ; fill
G1 F1800.000 E0.00502 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X79.025 Y78.793 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X78.825 Y78.593 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X99.857 Y78.352 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.657 Y78.153 F1200.000 E1.00894 ; fill
G1 X100.357 Y78.061 E1.03127 ; fill
G1 X100.556 Y78.260 E1.04021 ; fill
G1 X100.598 Y78.260 F7800.000 ; move to first fill point
G1 X100.399 Y78.061 F1200.000 E1.04707 ; fill
G1 X101.098 Y78.152 E1.06420 ; fill
G1 X101.298 Y78.352 E1.07107 ; fill
G1 F1800.000 E0.07107 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.734 Y81.396 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.534 Y81.196 F1200.000 E1.00686 ; fill
G1 X103.642 Y80.697 E1.01927 ; fill
G1 X103.442 Y80.497 E1.02614 ; fill
G1 X103.642 Y82.137 F7800.000 ; move to first fill point
G1 X103.442 Y81.938 F1200.000 E1.03508 ; fill
G1 X103.734 Y81.438 E1.05341 ; fill
G1 X103.534 Y81.238 E1.06235 ; fill
G1 F1800.000 E0.06235 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X102.139 Y85.755 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.677 Y85.293 F1200.000 E1.02684 ; fill
G1 X101.703 Y85.680 F7800.000 ; move to first fill point
G1 X101.372 Y85.349 F3600.000 E1.05110 ; fill
G1 X102.301 Y84.982 E1.10285 ; fill
G1 X102.632 Y85.313 E1.12711 ; fill
G1 F1800.000 E0.12711 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.212 Y89.332 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.012 Y89.132 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z2.200 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X100.029 Y91.418 F7800.000 ; move to first fill point
G1 Z1.200 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.828 Y91.218 F1200.000 E1.00502 ; fill
G1 F1800.000 E0.00502 ; retract
G1 Z2.600 ; move to next layer (3) and lift
G92 E0 ; reset extrusion distance
G1 X99.873 Y90.916 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.316 Y90.683 F1440.000 E1.01775 ; perimeter
G1 X99.200 Y90.593 E1.02208 ; perimeter
G1 X98.838 Y90.315 E1.03551 ; perimeter
G1 X98.472 Y89.835 E1.05326 ; perimeter
G1 X98.242 Y89.276 E1.07102 ; perimeter
G1 X98.165 Y88.677 E1.08877 ; perimeter
G1 X98.225 Y88.225 E1.10220 ; perimeter
G1 X98.245 Y88.079 E1.10653 ; perimeter
G1 X98.477 Y87.522 E1.12428 ; perimeter
G1 X98.846 Y87.044 E1.14204 ; perimeter
G1 X99.326 Y86.677 E1.15979 ; perimeter
G1 X99.884 Y86.447 E1.17754 ; perimeter
G1 X100.483 Y86.370 E1.19530 ; perimeter
G1 X101.082 Y86.450 E1.21305 ; perimeter
G1 X101.639 Y86.683 E1.23081 ; perimeter
G1 X102.117 Y87.051 E1.24856 ; perimeter
G1 X102.483 Y87.531 E1.26632 ; perimeter
G1 X102.713 Y88.090 E1.28407 ; perimeter
G1 X102.790 Y88.689 E1.30183 ; perimeter
G1 X102.710 Y89.287 E1.31958 ; perimeter
G1 X102.534 Y89.708 E1.33301 ; perimeter
G1 X102.478 Y89.844 E1.33733 ; perimeter
G1 X102.109 Y90.322 E1.35509 ; perimeter
G1 X101.629 Y90.689 E1.37284 ; perimeter
G1 X101.071 Y90.919 E1.39060 ; perimeter
G1 X100.472 Y90.996 E1.40835 ; perimeter
G1 X99.951 Y90.926 E1.42381 ; perimeter
G1 X99.873 Y90.916 E1.42611 ; perimeter
G1 X100.010 Y90.410 F7800.000 ; move to first perimeter point
G1 X99.579 Y90.230 F1440.000 E1.43984 ; perimeter
G1 X99.517 Y90.182 E1.44215 ; perimeter
G1 X99.210 Y89.945 E1.45357 ; perimeter
G1 X98.926 Y89.574 E1.46730 ; perimeter
G1 X98.749 Y89.142 E1.48103 ; perimeter
G1 X98.689 Y88.679 E1.49476 ; perimeter
G1 X98.740 Y88.294 E1.50618 ; perimeter
G1 X98.751 Y88.216 E1.50849 ; perimeter
G1 X98.931 Y87.785 E1.52222 ; perimeter
G1 X99.216 Y87.415 E1.53596 ; perimeter
G1 X99.587 Y87.132 E1.54969 ; perimeter
G1 X100.019 Y86.954 E1.56342 ; perimeter
G1 X100.482 Y86.894 E1.57715 ; perimeter
G1 X100.945 Y86.956 E1.59088 ; perimeter
G1 X101.376 Y87.136 E1.60461 ; perimeter
G1 X101.745 Y87.421 E1.61834 ; perimeter
G1 X102.029 Y87.792 E1.63207 ; perimeter
G1 X102.206 Y88.224 E1.64581 ; perimeter
G1 X102.266 Y88.687 E1.65954 ; perimeter
G1 X102.204 Y89.150 E1.67327 ; perimeter
G1 X102.055 Y89.508 E1.68468 ; perimeter
G1 X102.024 Y89.581 E1.68700 ; perimeter
G1 X101.739 Y89.951 E1.70073 ; perimeter
G1 X101.368 Y90.234 E1.71446 ; perimeter
G1 X100.936 Y90.412 E1.72819 ; perimeter
G1 X100.473 Y90.472 E1.74192 ; perimeter
G1 X100.088 Y90.420 E1.75336 ; perimeter
G1 X100.010 Y90.410 E1.75565 ; perimeter
G1 X99.626 Y90.760 F7800.000 ; move inwards before travel
G1 F1800.000 E0.75565 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X100.478 Y84.082 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.762 Y83.988 F1440.000 E1.02122 ; perimeter
G1 X99.095 Y83.711 E1.04245 ; perimeter
G1 X98.523 Y83.272 E1.06367 ; perimeter
G1 X98.083 Y82.699 E1.08489 ; perimeter
G1 X97.807 Y82.033 E1.10612 ; perimeter
G1 X97.713 Y81.317 E1.12734 ; perimeter
G1 X97.807 Y80.601 E1.14856 ; perimeter
G1 X98.083 Y79.935 E1.16979 ; perimeter
G1 X98.523 Y79.362 E1.19101 ; perimeter
G1 X99.095 Y78.923 E1.21223 ; perimeter
G1 X99.762 Y78.646 E1.23346 ; perimeter
G1 X100.477 Y78.552 E1.25468 ; perimeter
G1 X101.193 Y78.646 E1.27590 ; perimeter
G1 X101.860 Y78.923 E1.29713 ; perimeter
G1 X102.432 Y79.362 E1.31835 ; perimeter
G1 X102.872 Y79.935 E1.33957 ; perimeter
G1 X103.148 Y80.601 E1.36080 ; perimeter
G1 X103.242 Y81.317 E1.38202 ; perimeter
G1 X103.148 Y82.033 E1.40324 ; perimeter
G1 X102.872 Y82.699 E1.42447 ; perimeter
G1 X102.432 Y83.272 E1.44569 ; perimeter
G1 X101.860 Y83.711 E1.46691 ; perimeter
G1 X101.193 Y83.988 E1.48813 ; perimeter
G1 X100.555 Y84.072 E1.50707 ; perimeter
G1 X100.478 Y84.082 E1.50936 ; perimeter
G1 X100.198 Y84.520 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50936 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X81.769 Y81.869 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X81.549 Y82.432 F1440.000 E1.01775 ; perimeter
G1 X81.192 Y82.918 E1.03551 ; perimeter
G1 X80.720 Y83.296 E1.05326 ; perimeter
G1 X80.167 Y83.538 E1.07102 ; perimeter
G1 X79.571 Y83.629 E1.08877 ; perimeter
G1 X78.970 Y83.563 E1.10653 ; perimeter
G1 X78.408 Y83.344 E1.12428 ; perimeter
G1 X78.289 Y83.257 E1.12861 ; perimeter
G1 X77.921 Y82.986 E1.14204 ; perimeter
G1 X77.544 Y82.515 E1.15979 ; perimeter
G1 X77.301 Y81.962 E1.17754 ; perimeter
G1 X77.210 Y81.365 E1.19530 ; perimeter
G1 X77.260 Y80.911 E1.20873 ; perimeter
G1 X77.276 Y80.765 E1.21305 ; perimeter
G1 X77.496 Y80.202 E1.23081 ; perimeter
G1 X77.853 Y79.716 E1.24856 ; perimeter
G1 X78.325 Y79.338 E1.26632 ; perimeter
G1 X78.878 Y79.096 E1.28407 ; perimeter
G1 X79.474 Y79.005 E1.30183 ; perimeter
G1 X80.075 Y79.071 E1.31958 ; perimeter
G1 X80.637 Y79.290 E1.33733 ; perimeter
G1 X80.756 Y79.377 E1.34166 ; perimeter
G1 X81.124 Y79.648 E1.35509 ; perimeter
G1 X81.501 Y80.119 E1.37284 ; perimeter
G1 X81.744 Y80.672 E1.39060 ; perimeter
G1 X81.835 Y81.269 E1.40835 ; perimeter
G1 X81.777 Y81.792 E1.42382 ; perimeter
G1 X81.769 Y81.869 E1.42611 ; perimeter
G1 X81.260 Y81.744 F7800.000 ; move to first perimeter point
G1 X81.090 Y82.179 F1440.000 E1.43984 ; perimeter
G1 X80.813 Y82.555 E1.45357 ; perimeter
G1 X80.449 Y82.847 E1.46730 ; perimeter
G1 X80.021 Y83.035 E1.48103 ; perimeter
G1 X79.560 Y83.105 E1.49476 ; perimeter
G1 X79.096 Y83.054 E1.50849 ; perimeter
G1 X78.661 Y82.884 E1.52223 ; perimeter
G1 X78.597 Y82.838 E1.52454 ; perimeter
G1 X78.284 Y82.608 E1.53596 ; perimeter
G1 X77.992 Y82.243 E1.54969 ; perimeter
G1 X77.805 Y81.816 E1.56342 ; perimeter
G1 X77.734 Y81.354 E1.57715 ; perimeter
G1 X77.777 Y80.968 E1.58857 ; perimeter
G1 X77.785 Y80.890 E1.59088 ; perimeter
G1 X77.955 Y80.455 E1.60461 ; perimeter
G1 X78.232 Y80.079 E1.61834 ; perimeter
G1 X78.596 Y79.787 E1.63207 ; perimeter
G1 X79.024 Y79.599 E1.64581 ; perimeter
G1 X79.485 Y79.529 E1.65954 ; perimeter
G1 X79.949 Y79.580 E1.67327 ; perimeter
G1 X80.384 Y79.750 E1.68700 ; perimeter
G1 X80.761 Y80.026 E1.70073 ; perimeter
G1 X81.053 Y80.391 E1.71446 ; perimeter
G1 X81.240 Y80.818 E1.72819 ; perimeter
G1 X81.311 Y81.280 E1.74192 ; perimeter
G1 X81.268 Y81.666 E1.75336 ; perimeter
G1 X81.260 Y81.744 E1.75565 ; perimeter
G1 X81.619 Y82.120 F7800.000 ; move inwards before travel
G1 F1800.000 E0.75565 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X80.238 Y86.012 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X80.905 Y86.289 F1440.000 E1.02122 ; perimeter
G1 X81.477 Y86.728 E1.04245 ; perimeter
G1 X81.917 Y87.301 E1.06367 ; perimeter
G1 X82.193 Y87.967 E1.08489 ; perimeter
G1 X82.287 Y88.683 E1.10612 ; perimeter
G1 X82.193 Y89.399 E1.12734 ; perimeter
G1 X81.917 Y90.065 E1.14856 ; perimeter
G1 X81.543 Y90.553 E1.16664 ; perimeter
G1 X81.477 Y90.638 E1.16979 ; perimeter
G1 X80.905 Y91.077 E1.19101 ; perimeter
G1 X80.238 Y91.354 E1.21223 ; perimeter
G1 X79.522 Y91.448 E1.23346 ; perimeter
G1 X78.807 Y91.354 E1.25468 ; perimeter
G1 X78.140 Y91.077 E1.27590 ; perimeter
G1 X77.568 Y90.638 E1.29713 ; perimeter
G1 X77.128 Y90.065 E1.31835 ; perimeter
G1 X76.852 Y89.399 E1.33957 ; perimeter
G1 X76.758 Y88.683 E1.36080 ; perimeter
G1 X76.852 Y87.967 E1.38202 ; perimeter
G1 X77.128 Y87.301 E1.40324 ; perimeter
G1 X77.568 Y86.728 E1.42447 ; perimeter
G1 X78.140 Y86.289 E1.44569 ; perimeter
G1 X78.807 Y86.012 E1.46691 ; perimeter
G1 X79.522 Y85.918 E1.48813 ; perimeter
G1 X80.161 Y86.002 E1.50707 ; perimeter
G1 X80.238 Y86.012 E1.50936 ; perimeter
G1 X80.621 Y85.661 F7800.000 ; move inwards before travel
G1 F1800.000 E0.50936 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.827 Y91.191 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.479 Y90.694 F1440.000 E1.02410 ; perimeter
G1 X102.986 Y90.036 E1.04851 ; perimeter
G1 X102.986 Y91.191 E1.08247 ; perimeter
G1 X101.905 Y91.191 E1.11424 ; perimeter
G1 X101.827 Y91.191 E1.11653 ; perimeter
G1 F1800.000 E0.11653 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X102.986 Y87.333 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.488 Y86.682 F1800.000 E1.02410 ; perimeter
G1 X101.902 Y86.229 E1.04588 ; perimeter
G1 X101.218 Y85.944 E1.06765 ; perimeter
G1 X100.484 Y85.846 E1.08943 ; perimeter
G1 X99.750 Y85.941 E1.11121 ; perimeter
G1 X99.065 Y86.223 E1.13299 ; perimeter
G1 X98.476 Y86.672 E1.15476 ; perimeter
G1 X98.024 Y87.259 E1.17654 ; perimeter
G1 X97.739 Y87.942 E1.19832 ; perimeter
G1 X97.641 Y88.676 E1.22010 ; perimeter
G1 X97.735 Y89.411 E1.24188 ; perimeter
G1 X98.017 Y90.096 E1.26365 ; perimeter
G1 X98.467 Y90.684 E1.28543 ; perimeter
G1 X99.124 Y91.191 E1.30985 ; perimeter
G1 X82.363 Y91.191 E1.80271 ; perimeter
G1 X82.825 Y90.589 E1.82501 ; perimeter
G1 X83.206 Y89.670 E1.85428 ; perimeter
G1 X83.335 Y88.683 E1.88355 ; perimeter
G1 X83.206 Y87.696 E1.91282 ; perimeter
G1 X82.825 Y86.776 E1.94209 ; perimeter
G1 X82.219 Y85.987 E1.97136 ; perimeter
G1 X81.429 Y85.381 E2.00063 ; perimeter
G1 X80.735 Y85.093 E2.02273 ; perimeter
G1 X80.509 Y85.000 E2.02990 ; perimeter
G1 X79.522 Y84.870 E2.05917 ; perimeter
G1 X78.536 Y85.000 E2.08844 ; perimeter
G1 X77.616 Y85.381 E2.11771 ; perimeter
G1 X77.014 Y85.843 E2.14002 ; perimeter
G1 X77.014 Y82.685 E2.23287 ; perimeter
G1 X77.559 Y83.364 E2.25848 ; perimeter
G1 X78.155 Y83.803 E2.28026 ; perimeter
G1 X78.845 Y84.072 E2.30203 ; perimeter
G1 X79.581 Y84.153 E2.32381 ; perimeter
G1 X80.314 Y84.041 E2.34559 ; perimeter
G1 X80.992 Y83.744 E2.36737 ; perimeter
G1 X81.570 Y83.281 E2.38914 ; perimeter
G1 X82.008 Y82.684 E2.41092 ; perimeter
G1 X82.278 Y81.994 E2.43270 ; perimeter
G1 X82.359 Y81.258 E2.45448 ; perimeter
G1 X82.247 Y80.526 E2.47626 ; perimeter
G1 X81.949 Y79.848 E2.49803 ; perimeter
G1 X81.486 Y79.270 E2.51981 ; perimeter
G1 X80.859 Y78.809 E2.54270 ; perimeter
G1 X97.637 Y78.809 E3.03606 ; perimeter
G1 X97.175 Y79.410 E3.05836 ; perimeter
G1 X96.794 Y80.330 E3.08763 ; perimeter
G1 X96.664 Y81.317 E3.11690 ; perimeter
G1 X96.794 Y82.304 E3.14617 ; perimeter
G1 X97.175 Y83.224 E3.17544 ; perimeter
G1 X97.781 Y84.013 E3.20471 ; perimeter
G1 X98.378 Y84.471 E3.22681 ; perimeter
G1 X98.571 Y84.619 E3.23398 ; perimeter
G1 X99.491 Y85.000 E3.26325 ; perimeter
G1 X100.478 Y85.130 E3.29252 ; perimeter
G1 X101.464 Y85.000 E3.32179 ; perimeter
G1 X102.384 Y84.619 E3.35106 ; perimeter
G1 X102.986 Y84.157 E3.37336 ; perimeter
G1 X102.986 Y87.255 E3.46445 ; perimeter
G1 X102.986 Y87.333 E3.46675 ; perimeter
G1 F1800.000 E2.46675 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X78.155 Y78.809 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.475 Y79.353 F1440.000 E1.02560 ; perimeter
G1 X77.014 Y79.980 E1.04849 ; perimeter
G1 X77.014 Y78.809 E1.08294 ; perimeter
G1 X78.077 Y78.809 E1.11419 ; perimeter
G1 X78.155 Y78.809 E1.11648 ; perimeter
G1 X76.495 Y78.289 F7800.000 ; move to first perimeter point
G1 X99.067 Y78.289 F1800.000 E1.78023 ; perimeter
G1 X98.152 Y78.991 E1.81415 ; perimeter
G1 X97.629 Y79.673 E1.83940 ; perimeter
G1 X97.301 Y80.466 E1.86465 ; perimeter
G1 X97.189 Y81.317 E1.88989 ; perimeter
G1 X97.301 Y82.168 E1.91514 ; perimeter
G1 X97.629 Y82.961 E1.94039 ; perimeter
G1 X98.152 Y83.643 E1.96563 ; perimeter
G1 X98.833 Y84.165 E1.99088 ; perimeter
G1 X99.626 Y84.494 E2.01612 ; perimeter
G1 X100.478 Y84.606 E2.04137 ; perimeter
G1 X101.329 Y84.494 E2.06662 ; perimeter
G1 X102.122 Y84.165 E2.09186 ; perimeter
G1 X102.803 Y83.643 E2.11711 ; perimeter
G1 X103.505 Y82.727 E2.15103 ; perimeter
G1 X103.505 Y91.711 E2.41520 ; perimeter
G1 X80.933 Y91.711 E3.07895 ; perimeter
G1 X81.848 Y91.009 E3.11287 ; perimeter
G1 X82.371 Y90.327 E3.13812 ; perimeter
G1 X82.699 Y89.534 E3.16336 ; perimeter
G1 X82.811 Y88.683 E3.18861 ; perimeter
G1 X82.699 Y87.832 E3.21386 ; perimeter
G1 X82.371 Y87.039 E3.23910 ; perimeter
G1 X81.848 Y86.357 E3.26435 ; perimeter
G1 X81.167 Y85.835 E3.28960 ; perimeter
G1 X80.374 Y85.506 E3.31484 ; perimeter
G1 X79.522 Y85.394 E3.34009 ; perimeter
G1 X78.671 Y85.506 E3.36534 ; perimeter
G1 X77.878 Y85.835 E3.39058 ; perimeter
G1 X77.197 Y86.357 E3.41583 ; perimeter
G1 X76.495 Y87.273 E3.44975 ; perimeter
G1 X76.495 Y78.367 E3.71162 ; perimeter
G1 X76.495 Y78.289 E3.71391 ; perimeter
G1 F1800.000 E2.71391 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.495 Y90.093 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.197 Y91.009 F1440.000 E1.03392 ; perimeter
G1 X78.112 Y91.711 E1.06784 ; perimeter
G1 X76.495 Y91.711 E1.11541 ; perimeter
G1 X76.495 Y90.171 E1.16068 ; perimeter
G1 X76.495 Y90.093 E1.16297 ; perimeter
G1 F1800.000 E0.16297 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.888 Y78.289 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.505 Y78.289 F1440.000 E1.04756 ; perimeter
G1 X103.505 Y79.907 E1.09513 ; perimeter
G1 X102.803 Y78.991 E1.12905 ; perimeter
G1 X101.950 Y78.337 E1.16068 ; perimeter
G1 X101.888 Y78.289 E1.16297 ; perimeter
G1 F1800.000 E0.16297 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X104.025 Y77.770 F7800.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X104.025 Y92.230 F1800.000 E1.42523 ; perimeter
G1 X75.975 Y92.230 E2.25005 ; perimeter
G1 X75.975 Y77.770 E2.67528 ; perimeter
G1 X103.947 Y77.770 E3.49781 ; perimeter
G1 X104.025 Y77.770 E3.50010 ; perimeter
G1 X103.765 Y78.220 F7800.000 ; move inwards before travel
G1 F1800.000 E2.50010 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X98.769 Y85.880 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.370 Y85.279 F3000.000 E1.02527 ; fill
G1 X98.845 Y85.061 E1.04218 ; fill
G1 X93.069 Y90.837 E1.28501 ; fill
G1 X92.326 Y90.837 E1.30710 ; fill
G1 X98.351 Y84.813 E1.56038 ; fill
G1 X97.930 Y84.490 E1.57614 ; fill
G1 X91.583 Y90.837 E1.84298 ; fill
G1 X90.840 Y90.837 E1.86507 ; fill
G1 X97.525 Y84.152 E2.14613 ; fill
G1 X97.203 Y83.732 E2.16188 ; fill
G1 X90.097 Y90.837 E2.46061 ; fill
G1 X89.354 Y90.837 E2.48270 ; fill
G1 X96.882 Y83.309 E2.79920 ; fill
G1 X96.665 Y82.784 E2.81610 ; fill
G1 X88.611 Y90.837 E3.15469 ; fill
G1 X87.868 Y90.837 E3.17678 ; fill
G1 X96.451 Y82.254 E3.53762 ; fill
G1 X96.365 Y81.598 E3.55730 ; fill
G1 X87.125 Y90.837 E3.94574 ; fill
G1 X86.382 Y90.837 E3.96783 ; fill
G1 X96.342 Y80.878 E4.38656 ; fill
G1 X96.458 Y80.019 E4.41233 ; fill
G1 X85.639 Y90.837 E4.86717 ; fill
G1 X84.896 Y90.837 E4.88926 ; fill
G1 X96.571 Y79.163 E5.38008 ; fill
G1 X95.828 Y79.163 E5.40216 ; fill
G1 X84.154 Y90.837 E5.89298 ; fill
G1 X83.411 Y90.837 E5.91507 ; fill
G1 X95.085 Y79.163 E6.40588 ; fill
G1 X94.342 Y79.163 E6.42797 ; fill
G1 X83.548 Y89.956 E6.88176 ; fill
G1 X83.661 Y89.101 E6.90741 ; fill
G1 X93.599 Y79.163 E7.32523 ; fill
G1 X92.856 Y79.163 E7.34732 ; fill
G1 X83.633 Y88.386 E7.73506 ; fill
G1 X83.547 Y87.729 E7.75475 ; fill
G1 X92.113 Y79.163 E8.11489 ; fill
G1 X91.370 Y79.163 E8.13698 ; fill
G1 X83.330 Y87.203 E8.47501 ; fill
G1 X83.112 Y86.678 E8.49191 ; fill
G1 X90.627 Y79.163 E8.80786 ; fill
G1 X89.884 Y79.163 E8.82995 ; fill
G1 X82.789 Y86.258 E9.12823 ; fill
G1 X82.467 Y85.837 E9.14399 ; fill
G1 X89.141 Y79.163 E9.42460 ; fill
G1 X88.398 Y79.163 E9.44668 ; fill
G1 X82.059 Y85.502 E9.71319 ; fill
G1 X81.639 Y85.179 E9.72894 ; fill
G1 X87.655 Y79.163 E9.98188 ; fill
G1 X86.912 Y79.163 E10.00396 ; fill
G1 X81.142 Y84.933 E10.24657 ; fill
G1 X80.616 Y84.716 E10.26347 ; fill
G1 X81.209 Y84.123 E10.28839 ; fill
G1 X82.348 Y82.984 F7800.000 ; move to first fill point
G1 X86.169 Y79.163 F3000.000 E10.44903 ; fill
G1 X85.426 Y79.163 E10.47112 ; fill
G1 X82.660 Y81.929 E10.58740 ; fill
G1 X82.680 Y81.166 E10.61007 ; fill
G1 X84.683 Y79.163 E10.69430 ; fill
G1 X83.940 Y79.163 E10.71639 ; fill
G1 X82.577 Y80.527 E10.77372 ; fill
G1 X82.350 Y80.010 E10.79048 ; fill
G1 X83.197 Y79.163 E10.82610 ; fill
G1 X82.454 Y79.163 E10.84819 ; fill
G1 X82.124 Y79.494 E10.86210 ; fill
G1 F1800.000 E9.86210 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X97.858 Y90.506 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X97.527 Y90.837 F3000.000 E1.01391 ; fill
G1 X96.784 Y90.837 E1.03600 ; fill
G1 X97.641 Y89.980 E1.07204 ; fill
G1 X97.425 Y89.453 E1.08896 ; fill
G1 X96.041 Y90.837 E1.14714 ; fill
G1 X95.298 Y90.837 E1.16923 ; fill
G1 X97.321 Y88.814 E1.25429 ; fill
G1 X97.344 Y88.048 E1.27705 ; fill
G1 X94.555 Y90.837 E1.39430 ; fill
G1 X93.812 Y90.837 E1.41639 ; fill
G1 X97.677 Y86.972 E1.57888 ; fill
G1 F1800.000 E0.57888 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X100.045 Y91.220 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.845 Y91.420 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.212 Y89.132 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.012 Y89.332 F1200.000 E1.00502 ; fill
G1 F1800.000 E0.00502 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X102.563 Y85.505 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X102.101 Y85.967 F1200.000 E1.02684 ; fill
G1 F1800.000 E0.02684 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X103.642 Y81.937 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X103.442 Y82.137 F1200.000 E1.00687 ; fill
G1 X103.534 Y81.438 E1.02401 ; fill
G1 X103.734 Y81.238 E1.03087 ; fill
G1 X103.734 Y81.196 F7800.000 ; move to first fill point
G1 X103.534 Y81.396 F1200.000 E1.03981 ; fill
G1 X103.442 Y80.696 E1.06214 ; fill
G1 X103.642 Y80.497 E1.07108 ; fill
G1 F1800.000 E0.07108 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X101.298 Y78.153 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X101.098 Y78.352 F1200.000 E1.00894 ; fill
G1 X100.598 Y78.061 E1.02726 ; fill
G1 X100.399 Y78.260 E1.03620 ; fill
G1 X100.556 Y78.061 F7800.000 ; move to first fill point
G1 X100.357 Y78.260 F1200.000 E1.04306 ; fill
G1 X99.857 Y78.152 E1.05547 ; fill
G1 X99.657 Y78.352 E1.06235 ; fill
G1 F1800.000 E0.06235 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X79.108 Y78.580 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X78.909 Y78.780 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.998 Y81.815 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.799 Y82.014 F1200.000 E1.00501 ; fill
G1 F1800.000 E0.00501 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X78.319 Y84.247 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X77.857 Y84.709 F1200.000 E1.02684 ; fill
G1 F1800.000 E0.02684 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X76.466 Y88.562 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X76.266 Y88.762 F1200.000 E1.00686 ; fill
G1 X76.358 Y88.063 E1.02399 ; fill
G1 X76.558 Y87.863 E1.03086 ; fill
G1 X76.558 Y89.304 F7800.000 ; move to first fill point
G1 X76.358 Y89.503 F1200.000 E1.03980 ; fill
G1 X76.266 Y88.804 E1.06213 ; fill
G1 X76.466 Y88.604 E1.07107 ; fill
G1 F1800.000 E0.07107 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
G1 X79.601 Y91.740 F7800.000 ; move to first fill point
G1 Z1.600 ; restore layer Z
G1 F1800.000 E1.00000 ; compensate retraction
G1 X79.402 Y91.939 F1200.000 E1.00894 ; fill
G1 X78.902 Y91.648 E1.02726 ; fill
G1 X78.702 Y91.847 E1.03620 ; fill
G1 X80.343 Y91.648 F7800.000 ; move to first fill point
G1 X80.143 Y91.848 F1200.000 E1.04307 ; fill
G1 X79.643 Y91.740 E1.05549 ; fill
G1 X79.444 Y91.939 E1.06234 ; fill
G1 F1800.000 E0.06234 ; retract
G1 Z2.600 ; lift plate during travel
G92 E0 ; reset extrusion distance
M104 S0 ; turn off extruder heater
M140 S0 ; turn off bed heater
G28 X0  ; home X axis
G28 Y0  ; home Y axis
M84     ; disable motors
; filament used = 91.0mm (0.6cm3)

; acceleration = 0
; bed_size = 180,170
; bed_temperature = 60
; bottom_solid_layers = 3
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_width = 0
; complete_objects = 0
; cooling = 
; disable_fan_first_layers = 2
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = M104 S0 ; turn off extruder heater\nM140 S0 ; turn off bed heater\nG28 X0  ; home X axis\nG28 Y0  ; home Y axis\nM84     ; disable motors
; external_perimeter_speed = 100%
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 
; fan_below_layer_time = 60
; filament_diameter = 3
; fill_angle = 45
; fill_density = 0.40
; fill_pattern = rectilinear
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 200%
; first_layer_height = 100%
; first_layer_speed = 50%
; first_layer_temperature = 185
; g0 = 0
; gap_fill_speed = 20
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_speed = 60
; layer_gcode = 
; layer_height = 0.4
; max_fan_speed = 100
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.5
; only_retract_when_crossing_perimeters = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 25
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 30
; perimeters = 3
; post_process = 
; print_center = 90,85
; randomize_start = 1
; retract_before_travel = 2
; retract_length = 1
; retract_length_toolchange = 3
; retract_lift = 1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 30
; rotate = 0
; scale = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 15
; small_perimeter_speed = 24
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_speed = 60
; start_gcode = G28 ; home all axes\nG92 E0 ;reset extruder
; support_material = 0
; support_material_angle = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 45
; temperature = 185
; threads = 2
; top_solid_infill_speed = 50
; top_solid_layers = 3
; travel_speed = 130
; use_relative_e_distances = 0
; vibration_limit = 0
; z_offset = 0
